{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"ROF Forecast\",\"ROF OrderPlan\",\"Non Executable\",\"Pipeline\",\"FlashBudget\",\"EOP\",\"ROF BudgetPlan\",\"ColWkSorting\",\"Geo Master\",\"Geo Bridge\",\"Prod Bridge\",\"RowWkSorting\",\"Prod Master\",\"DBConnection\",\"CurrWeek\",\"Calcs\",\"DataRefreshConfig\",\"Date Last Refreshed\",\"ROF Pipeline\",\"UAM Attributes\",\"rpt dim_current_date_rof\",\"Load Bookings\",\"Month new\",\"dim ROF_WeekNO\",\"Metric Definitions\",\"CurrWeek1\",\"Custom notifications\",\"ROF_Clari_Final\",\"ROF_Clari_Final_Split\",\"Metrics\",\"TOPN\",\"w / wo Decimal\",\"rpt flashbudget_OR\",\"dim GeoProduct\",\"Date\",\"Pipeline_Services\",\"ROF_NEO\",\"Sort Forecast Category\",\"Geo Master Sorting\",\"Table_TempSecurity\",\"Prod Master Sorting (Prod categ)\",\"Prod Master Sorting (BU)\",\"Prod Master Sorting (Alternate BU)\",\"Limit\",\"OrdersDetailed\",\"QTD Plans\",\"fact ROF_Actuals_PQ\",\"Metric Table\",\"Table_OL\",\"TableNew\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.952.0 (24.04)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "DBConnection",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\")",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "f2c0784a-31c1-4721-a71a-4de33d0ca733",
        "queryGroup": "ROF Group"
      },
      {
        "name": "CurrWeek",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
          "    #\"ROF_WeekNO_Sheet\" = Source{[Schema=\"dim\",Item=\"ROF_WeekNO\"]}[Data],",
          "    #\"Changed Type\" = Table.TransformColumnTypes(ROF_WeekNO_Sheet,{{\"CloseDate\", type datetime}, {\"Day\", type datetime}}),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"IsCurrentWeek\", each Date.From(DateTime.LocalNow()) = Date.From([CloseDate])),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each ([IsCurrentWeek] = true)),",
          "    #\"Removed Other Columns\" = #\"Filtered Rows\"{0}[WeekNo1]",
          "in",
          "    #\"Removed Other Columns\""
        ],
        "kind": "m",
        "lineageTag": "3de56bb3-3205-4a71-87c4-357e55397f77",
        "queryGroup": "ROF Group"
      },
      {
        "name": "CurrWeek1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Number"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\", [Query=\"select fiscal_week from [rpt].[dim_current_date_rof]\"]),",
          "    #\"Removed Other Columns\" = Source{0}[fiscal_week]",
          "in",
          "    #\"Removed Other Columns\""
        ],
        "kind": "m",
        "lineageTag": "3b43084e-0a31-43b3-a199-f71dafb554f2",
        "queryGroup": "ROF Group"
      },
      {
        "name": "ROF_Clari_Final",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
          "    fact_ROF_Clari_Final = Source{[Schema=\"fact\",Item=\"ROF_Clari_Final\"]}[Data],",
          "    #\"Added Custom\" = Table.AddColumn(fact_ROF_Clari_Final, \"Clari/ROF\", each \"Unadjusted (Clari)\"),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\",{\"Total\", \"CountryCode\", \"BusinessAreaCode\"})",
          "in",
          "    #\"Removed Columns\""
        ],
        "kind": "m",
        "lineageTag": "88370f26-8bb8-40af-be1f-8c41aaab593e",
        "queryGroup": "ROF Group\\Facts"
      },
      {
        "name": "Limit",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "expression": "0 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a3ba6f90-af99-43a1-bda2-ad401c296ebd"
      }
    ],
    "perspectives": [
      {
        "name": "Custom Report",
        "tables": [
          {
            "name": "Geo Master",
            "columns": [
              {
                "name": "Region"
              },
              {
                "name": "SubRegion1"
              },
              {
                "name": "SubRegion2"
              },
              {
                "name": "SubRegion3"
              },
              {
                "name": "Country"
              },
              {
                "name": "RegionMoBo"
              }
            ]
          },
          {
            "name": "ColWkSorting",
            "columns": [
              {
                "name": "Weeks"
              }
            ]
          },
          {
            "name": "Prod Master",
            "columns": [
              {
                "name": "BU 1"
              },
              {
                "name": "BU 2"
              },
              {
                "name": "BU 3"
              },
              {
                "name": "BU 4"
              },
              {
                "name": "Prod Categ"
              }
            ]
          },
          {
            "name": "Calcs",
            "measures": [
              {
                "name": "BBL"
              },
              {
                "name": "EBBL"
              },
              {
                "name": "Non Exec Cum"
              },
              {
                "name": "Non Exec Total"
              },
              {
                "name": "vs Order Budget Plan"
              },
              {
                "name": "vs Order Budget Plan Cum"
              },
              {
                "name": "vs Plan_M1"
              },
              {
                "name": "vs Week Forecast"
              },
              {
                "name": "vs Rev Flash"
              },
              {
                "name": "vs Rev Budget"
              },
              {
                "name": "vs Flash w/o BBL"
              },
              {
                "name": "vs Plan_M2"
              },
              {
                "name": "vs Plan Cum_M1"
              },
              {
                "name": "vs Plan Cum_M2"
              },
              {
                "name": "vs Plan_M3"
              },
              {
                "name": "vs Plan Cum_M3"
              },
              {
                "name": "Commit"
              },
              {
                "name": "Late Stage (SS 4-5)"
              },
              {
                "name": "Total C + U + LS"
              },
              {
                "name": "Upside"
              },
              {
                "name": "Won"
              },
              {
                "name": "Total Funnel"
              },
              {
                "name": "Early Stage (SS 1-3)"
              },
              {
                "name": "Order Budget Plan"
              },
              {
                "name": "M1 EOP Value"
              },
              {
                "name": "Revenue Flash"
              },
              {
                "name": "Revenue Budget"
              },
              {
                "name": "M1 Order Plan+Task"
              },
              {
                "name": "M2 Order Plan+Task"
              },
              {
                "name": "M3 Order Plan+Task"
              },
              {
                "name": "M2 EOP Value"
              },
              {
                "name": "M3 EOP Value"
              },
              {
                "name": "Deal Based Indirect"
              },
              {
                "name": "Total Judgement"
              },
              {
                "name": "Deal Based Direct"
              },
              {
                "name": "Deal Based"
              },
              {
                "name": "Judge Down (Non Deal)"
              },
              {
                "name": "Run Rate (Non Deal)"
              },
              {
                "name": "Stretch (Non Deal)"
              },
              {
                "name": "Task (Non Deal)"
              },
              {
                "name": "Non Deal Based"
              },
              {
                "name": "vs Prior Wk Fcst (ROF)"
              },
              {
                "name": "Cum M1 Order Plan + Task"
              },
              {
                "name": "Cum M2 Order Plan + Task"
              },
              {
                "name": "Cum M3 Order Plan + Task"
              },
              {
                "name": "vs Order Plan Cum"
              },
              {
                "name": "Orders"
              },
              {
                "name": "Cum Orders"
              },
              {
                "name": "Curr Wk Forecast ROF"
              },
              {
                "name": "Cum Orders + Forecast (ROF)"
              }
            ]
          },
          {
            "name": "RowWkSorting",
            "columns": [
              {
                "name": "Week"
              }
            ]
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "ROF Group"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "ROF Group\\Facts"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "ROF Group\\Dims"
      }
    ],
    "relationships": [
      {
        "name": "50818cfd-947a-40b7-85c9-4412b0c5764a",
        "fromColumn": "GeoKey",
        "fromTable": "ROF Forecast",
        "toColumn": "GeoKey",
        "toTable": "Geo Master"
      },
      {
        "name": "d5e56432-bea2-48d6-8c8e-ea00d8a551db",
        "fromColumn": "GeoKey",
        "fromTable": "ROF OrderPlan",
        "toColumn": "GeoKey",
        "toTable": "Geo Master"
      },
      {
        "name": "9c64b879-879e-412d-81eb-6d1cd00bc7ff",
        "fromColumn": "GeoKey",
        "fromTable": "Non Executable",
        "toColumn": "GeoKey",
        "toTable": "Geo Master"
      },
      {
        "name": "0904678a-c2eb-43bf-bf18-523379a3da64",
        "fromColumn": "GeoKey",
        "fromTable": "ROF BudgetPlan",
        "toColumn": "GeoKey",
        "toTable": "Geo Master"
      },
      {
        "name": "0ea3bf8e-fb0c-4c3f-ba16-59e8959828f5",
        "fromColumn": "ProductKey",
        "fromTable": "ROF Forecast",
        "toColumn": "ProductKey",
        "toTable": "Prod Master"
      },
      {
        "name": "fa5725a4-910a-44ad-b7b9-364cd1673ac3",
        "fromColumn": "ProductKey",
        "fromTable": "ROF OrderPlan",
        "toColumn": "ProductKey",
        "toTable": "Prod Master"
      },
      {
        "name": "78f8b18c-d59a-433e-a95e-92b4f8114758",
        "fromColumn": "ProductKey",
        "fromTable": "Non Executable",
        "toColumn": "ProductKey",
        "toTable": "Prod Master"
      },
      {
        "name": "8ff0e179-e59e-4e38-9f36-9861eb8647e5",
        "fromColumn": "ProductKey",
        "fromTable": "FlashBudget",
        "toColumn": "ProductKey",
        "toTable": "Prod Master"
      },
      {
        "name": "29ff5bd8-8b15-4d49-b59c-7a5f36453421",
        "fromColumn": "ProductKey",
        "fromTable": "EOP",
        "toColumn": "ProductKey",
        "toTable": "Prod Master"
      },
      {
        "name": "f649d709-7907-4d84-8f5a-1fc74a619a9b",
        "fromColumn": "ProductKey",
        "fromTable": "ROF BudgetPlan",
        "toColumn": "ProductKey",
        "toTable": "Prod Master"
      },
      {
        "name": "e1d5da02-0861-4662-8153-dc59c31f832c",
        "fromColumn": "WeekNo",
        "fromTable": "EOP",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "97137a70-e6e6-440b-8ce6-3355d26a25cb",
        "fromColumn": "ColumnWeek",
        "fromTable": "ROF Forecast",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "4b5de6db-333f-4a16-afd7-d7ce0c3edc89",
        "fromColumn": "Weekno",
        "fromTable": "Non Executable",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "de6e207a-14da-4b52-9a51-1ecd33db61fd",
        "fromColumn": "WeekNo",
        "fromTable": "ROF OrderPlan",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "ce1727fb-e127-4e22-aa48-1e10c8783573",
        "fromColumn": "WeekNo",
        "fromTable": "ROF BudgetPlan",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "f2a89d3e-c954-4a0d-acf3-30ef55c7bdbd",
        "fromColumn": "WeekNo",
        "fromTable": "ROF Forecast",
        "toColumn": "Week",
        "toTable": "RowWkSorting"
      },
      {
        "name": "53046a5b-98f4-44ce-a64e-c3b4d5f97c64",
        "fromColumn": "ProductKey",
        "fromTable": "Pipeline",
        "toColumn": "ProductKey",
        "toTable": "Prod Master"
      },
      {
        "name": "9a7ff38d-1e26-4399-8a82-e5f74072dde8",
        "fromColumn": "GeoKey",
        "fromTable": "FlashBudget",
        "toColumn": "GeoKey",
        "toTable": "Geo Master"
      },
      {
        "name": "6c463a26-952c-4155-bfdb-6bf0d2707620",
        "fromColumn": "GeoKey",
        "fromTable": "Pipeline",
        "toColumn": "GeoKey",
        "toTable": "Geo Master"
      },
      {
        "name": "10b9b208-50b9-4d42-bd64-948dcea8f374",
        "fromColumn": "ROFGeoKey",
        "fromTable": "ROF Pipeline",
        "toColumn": "GeoKey",
        "toTable": "Geo Master"
      },
      {
        "name": "84a2daef-1a45-4a73-9213-f0441f570615",
        "fromColumn": "ROFProductKey",
        "fromTable": "ROF Pipeline",
        "toColumn": "ProductKey",
        "toTable": "Prod Master"
      },
      {
        "name": "51ce03de-8122-481f-b4f9-cdb29ea26d83",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Value",
        "fromTable": "Dummy Table",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "97b5a02b-3590-409e-adff-388e5aa807bd",
        "fromColumn": "GeoKey",
        "fromTable": "EOP",
        "toColumn": "GeoKey",
        "toTable": "Geo Master"
      },
      {
        "name": "f92d0de2-49a9-47ed-8b66-0511326eec5f",
        "fromColumn": "ROFGeoKEY",
        "fromTable": "Geo Bridge",
        "toColumn": "GeoKey",
        "toTable": "Geo Master"
      },
      {
        "name": "4b287a4b-2e66-452f-a675-4a27ee9753aa",
        "fromColumn": "ROFProductKEY",
        "fromTable": "Prod Bridge",
        "toColumn": "ProductKey",
        "toTable": "Prod Master"
      },
      {
        "name": "9f7b7c1f-6344-4e11-9a04-7668aae8945e",
        "fromColumn": "Plan",
        "fromTable": "ROF OrderPlan",
        "toColumn": "Plan",
        "toTable": "Month new"
      },
      {
        "name": "d9f3c6f4-7722-43f1-a407-ab1e2336c14c",
        "fromColumn": "ProductKey",
        "fromTable": "ROF_Clari_Final_Split",
        "toColumn": "ProductKey",
        "toTable": "Prod Master"
      },
      {
        "name": "3d80120b-4d5e-4365-b521-e6a85cdbd0cb",
        "fromColumn": "GeoKey",
        "fromTable": "ROF_Clari_Final_Split",
        "toColumn": "GeoKey",
        "toTable": "Geo Master"
      },
      {
        "name": "a6b34acc-035b-4657-a894-291895bd4d25",
        "fromColumn": "ColumnWeek",
        "fromTable": "ROF_Clari_Final_Split",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "dc7dfef9-2ff1-40f7-8d4c-cfbfea374f05",
        "fromColumn": "WeekNo",
        "fromTable": "ROF_Clari_Final_Split",
        "toColumn": "Week",
        "toTable": "RowWkSorting"
      },
      {
        "name": "c496ffa3-7a00-4fcb-a928-ec2dc257fd54",
        "fromColumn": "WeekNo",
        "fromTable": "Pipeline",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "525ce4fe-ce86-4d30-a5a5-335f67a50046",
        "fromColumn": "ProductKey",
        "fromTable": "dim GeoProduct",
        "toColumn": "ProductKey",
        "toTable": "Prod Bridge"
      },
      {
        "name": "a967b787-8bfb-45d0-92e3-54a75c2c8c2b",
        "fromColumn": "GeoKey",
        "fromTable": "dim GeoProduct",
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "d2f727ff-53df-44b8-a24f-310e3ff8d8db",
        "fromColumn": "fiscalquarter",
        "fromTable": "rpt flashbudget_OR",
        "toCardinality": "many",
        "toColumn": "fiscalyrQtr",
        "toTable": "Date"
      },
      {
        "name": "d4397b63-f33e-4409-9743-4bdf8a106657",
        "fromColumn": "fiscalweekkey",
        "fromTable": "Load Bookings",
        "toColumn": "fiscal_weekkey",
        "toTable": "Date"
      },
      {
        "name": "3192ac4f-add1-4fda-99f5-afddd05929a2",
        "fromColumn": "GP_Key",
        "fromTable": "Pipeline_Services",
        "toColumn": "GP_Key",
        "toTable": "dim GeoProduct"
      },
      {
        "name": "3694b64c-9e36-4d4a-8d4c-a3fe0b3550ea",
        "fromColumn": "GP_Key",
        "fromTable": "Load Bookings",
        "toColumn": "GP_Key",
        "toTable": "dim GeoProduct"
      },
      {
        "name": "07ce4f04-1f3e-4b3f-8e64-4434f7209ca0",
        "fromColumn": "GP_Key",
        "fromTable": "rpt flashbudget_OR",
        "toColumn": "GP_Key",
        "toTable": "dim GeoProduct"
      },
      {
        "name": "40a004bf-8bec-4cbf-a13e-0144263c91fd",
        "fromColumn": "WeekNo",
        "fromTable": "Pipeline_Services",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "cc18d9c9-edf9-48b3-a654-a34d9b01a242",
        "fromColumn": "GeoKey",
        "fromTable": "ROF_NEO",
        "toColumn": "GeoKey",
        "toTable": "Geo Master"
      },
      {
        "name": "6ed7a9b3-ac39-456e-9c42-b75822a1a69c",
        "fromColumn": "ProductKey",
        "fromTable": "ROF_NEO",
        "toColumn": "ProductKey",
        "toTable": "Prod Master"
      },
      {
        "name": "d04b1910-8be1-4f8e-b2f2-3b2a279de6fe",
        "fromColumn": "WeekNo",
        "fromTable": "ROF_NEO",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "1df639fd-0f6d-4ba1-b75e-b7c4d11ef577",
        "fromColumn": "Forecast Category",
        "fromTable": "ROF Pipeline",
        "toColumn": "Fcst Category",
        "toTable": "Sort Forecast Category"
      },
      {
        "name": "1238f4ec-a88b-c7e3-0c81-7ef52d340a74",
        "fromColumn": "WeekNo",
        "fromTable": "ROF Pipeline",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "2ea47660-72a0-47e6-a22c-30e3a59d7024",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "SubRegion1",
        "fromTable": "Geo Master",
        "securityFilteringBehavior": "bothDirections",
        "toColumn": "SubRegion1",
        "toTable": "Geo Master Sorting"
      },
      {
        "name": "2c17ef13-b166-4c3a-942a-500bc48c6ebb",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Prod Categ",
        "fromTable": "Table_TempSecurity",
        "toColumn": "Prod Categ",
        "toTable": "Prod Master"
      },
      {
        "name": "ec1992dd-1cdf-41f8-96e5-6037928d2b59",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Prod Categ",
        "fromTable": "Prod Master Sorting (Prod categ)",
        "toColumn": "Prod Categ",
        "toTable": "Prod Master"
      },
      {
        "name": "f3669a16-90f6-4622-b0d6-06dd5d6b6054",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "BU 2",
        "fromTable": "Prod Master",
        "toColumn": "BU 2",
        "toTable": "Prod Master Sorting (BU)"
      },
      {
        "name": "4148eb55-8fa0-471a-9cc6-d7ae068f03a4",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "BU 1",
        "fromTable": "Prod Master",
        "toColumn": "Alternate BU",
        "toTable": "Prod Master Sorting (Alternate BU)"
      },
      {
        "name": "68276482-409f-41e5-b971-ec56a80884d5",
        "fromColumn": "Sort",
        "fromTable": "Prod Master",
        "isActive": false,
        "toColumn": "Sort",
        "toTable": "Geo Master Sorting"
      },
      {
        "name": "7fa8d3c2-1039-4e9e-87cf-6a8c4186067e",
        "fromColumn": "weekno",
        "fromTable": "Load Bookings",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "8fb44079-b51c-4f32-975a-436e58ec4272",
        "fromColumn": "ProductKey",
        "fromTable": "OrdersDetailed",
        "toColumn": "ProductKey",
        "toTable": "Prod Bridge"
      },
      {
        "name": "5445d1d8-d018-409c-b07d-697fb75420e9",
        "fromColumn": "Geokey",
        "fromTable": "OrdersDetailed",
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "61859cb0-0e54-4f94-8660-1d3b6f386855",
        "fromColumn": "Week No New",
        "fromTable": "OrdersDetailed",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "952311c3-a0a0-4663-ab07-df3aebd6cf1a",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Column1",
        "fromTable": "Calcs",
        "toColumn": "Column1",
        "toTable": "QTD Plans"
      },
      {
        "name": "1022a01b-718a-4566-839a-0c0a27f0a045",
        "fromColumn": "ProductKey",
        "fromTable": "fact ROF_Actuals_PQ",
        "toColumn": "ProductKey",
        "toTable": "Prod Master"
      },
      {
        "name": "f89a36d4-cc8f-4517-a978-890399b5187d",
        "fromColumn": "GeoKey",
        "fromTable": "ROF Forecast",
        "isActive": false,
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "f7311d02-b3ea-4f17-a6e3-54c9f1be96b8",
        "fromColumn": "GeoKey",
        "fromTable": "ROF OrderPlan",
        "isActive": false,
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "4acae0f0-4b4d-4b4b-a10d-24e6de3314d8",
        "fromColumn": "GeoKey",
        "fromTable": "Non Executable",
        "isActive": false,
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "666e8f09-5437-45e9-b7bf-a0015b3263ac",
        "fromColumn": "GeoKey",
        "fromTable": "Pipeline",
        "isActive": false,
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "a9d2ce75-650a-451b-a82f-3191942c0948",
        "fromColumn": "GeoKey",
        "fromTable": "FlashBudget",
        "isActive": false,
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "fc7bfbcb-9eed-4d73-a012-8518ceb36458",
        "fromColumn": "GeoKey",
        "fromTable": "EOP",
        "isActive": false,
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "fb47ac3b-2622-4e1b-8238-bfd9b7720fc6",
        "fromColumn": "GeoKey",
        "fromTable": "ROF BudgetPlan",
        "isActive": false,
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "d790e986-e4ab-4306-a4ce-728543ee1faf",
        "fromColumn": "geokey",
        "fromTable": "Load Bookings",
        "isActive": false,
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "8c1fd842-3bb9-4770-822e-f00fd3c1ec11",
        "fromColumn": "GeoKey",
        "fromTable": "ROF_Clari_Final_Split",
        "isActive": false,
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "3e259276-766d-4bf9-ab42-bfea96b4bffc",
        "fromColumn": "geokey",
        "fromTable": "rpt flashbudget_OR",
        "isActive": false,
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "298454af-3c27-4781-ac89-40701e801e52",
        "fromColumn": "GeoKey",
        "fromTable": "Pipeline_Services",
        "isActive": false,
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "478d7d46-92bd-4b52-8f0c-df404126f1b8",
        "fromColumn": "GeoKey",
        "fromTable": "ROF_NEO",
        "isActive": false,
        "toColumn": "GeoKey",
        "toTable": "Geo Bridge"
      },
      {
        "name": "58cba29f-ea63-4722-a6c4-0d699aa3e457",
        "fromColumn": "productkey",
        "fromTable": "Load Bookings",
        "isActive": false,
        "toColumn": "ProductKey",
        "toTable": "Prod Bridge"
      },
      {
        "name": "be42b00f-52d3-4fd1-950a-717f980b93cf",
        "fromColumn": "productkey",
        "fromTable": "rpt flashbudget_OR",
        "isActive": false,
        "toColumn": "ProductKey",
        "toTable": "Prod Bridge"
      },
      {
        "name": "2b82d809-7b63-4998-b3fa-9350dc7196d5",
        "fromColumn": "ProductKey",
        "fromTable": "Pipeline_Services",
        "isActive": false,
        "toColumn": "ProductKey",
        "toTable": "Prod Bridge"
      },
      {
        "name": "38b7e5bf-ec20-4942-aa40-ccf85042d04e",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "SortOrder",
        "fromTable": "RowWkSorting",
        "isActive": false,
        "toColumn": "SortOrder",
        "toTable": "ColWkSorting"
      },
      {
        "name": "a354d555-c707-4c9e-8c9c-c3fdf644da9d",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Sort Order",
        "fromTable": "Sort Forecast Category",
        "isActive": false,
        "toColumn": "SortOrder",
        "toTable": "ColWkSorting"
      },
      {
        "name": "34f66312-4c21-4894-bede-0f892fd3a810",
        "fromColumn": "SubRegion1",
        "fromTable": "Geo Bridge",
        "isActive": false,
        "toColumn": "SubRegion1",
        "toTable": "Geo Master Sorting"
      },
      {
        "name": "366669e8-36e2-488c-8fa5-1ec3d1186267",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Prod Categ",
        "fromTable": "Prod Master Sorting (Prod categ)",
        "isActive": false,
        "toColumn": "Prod Categ",
        "toTable": "Table_TempSecurity"
      },
      {
        "name": "818211ef-dc8c-4f5a-8973-4a8058465f68",
        "fromColumn": "Sort",
        "fromTable": "Prod Bridge",
        "isActive": false,
        "toColumn": "Sort",
        "toTable": "Prod Master Sorting (Prod categ)"
      },
      {
        "name": "24eef508-9c04-4780-ba58-1d54470add13",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Sort",
        "fromTable": "Geo Master Sorting",
        "isActive": false,
        "toColumn": "Sort",
        "toTable": "Prod Master Sorting (Prod categ)"
      },
      {
        "name": "a3fee7e6-9772-4f46-b1b2-60edd6414040",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Sort",
        "fromTable": "Prod Master Sorting (BU)",
        "isActive": false,
        "toColumn": "Sort",
        "toTable": "Prod Master Sorting (Prod categ)"
      },
      {
        "name": "587c560b-344e-4321-9515-bee452253cc3",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Sort",
        "fromTable": "Prod Master Sorting (Alternate BU)",
        "isActive": false,
        "toColumn": "Sort",
        "toTable": "Prod Master Sorting (Prod categ)"
      },
      {
        "name": "bffb906e-f751-4b33-bb50-f8eab6f95f33",
        "fromColumn": "FiscalWeekKey",
        "fromTable": "Pipeline_Services",
        "toColumn": "fiscal_weekkey",
        "toTable": "Date"
      },
      {
        "name": "7b1bba22-75b6-440c-81bc-4513606823ac",
        "fromColumn": "BU",
        "fromTable": "Non Executable",
        "isActive": false,
        "toColumn": "BU 2",
        "toTable": "Prod Master Sorting (BU)"
      },
      {
        "name": "7b767372-7c8e-48a5-9d6c-6fbe18667356",
        "fromColumn": "BU",
        "fromTable": "ROF BudgetPlan",
        "isActive": false,
        "toColumn": "BU 2",
        "toTable": "Prod Master Sorting (BU)"
      },
      {
        "name": "9ea958d6-66a2-43fc-8413-ecd3a04b165e",
        "fromColumn": "WeekNo",
        "fromTable": "fact ROF_Actuals_PQ",
        "toColumn": "Week",
        "toTable": "RowWkSorting"
      },
      {
        "name": "971e21a7-ac51-4e14-9f4d-15b5256f6a95",
        "fromColumn": "ColumnWeek",
        "fromTable": "fact ROF_Actuals_PQ",
        "toColumn": "Weeks",
        "toTable": "ColWkSorting"
      },
      {
        "name": "2ec88198-adcd-42d1-b907-eb8a23ca5c17",
        "fromColumn": "GeoKey",
        "fromTable": "fact ROF_Actuals_PQ",
        "toColumn": "GeoKey",
        "toTable": "Geo Master"
      }
    ],
    "roles": [
      {
        "name": "UAM Role",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e0895e4cf18440e2bef459a817043e98"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Prod Master",
            "filterExpression": [
              "If (\"Rolling Order Forecast\" IN CALCULATETABLE(VALUES('UAM Attributes'[DATAVALUE]),FILTER (ALL ('UAM Attributes'),'UAM Attributes'[EmailAddress]=USERNAME() && 'UAM Attributes'[ATTRIBUTE]=\"Modules\" && 'UAM Attributes'[DATAVALUE]=\"Rolling Order Forecast\")),",
              "",
              "If(",
              "MaxX(",
              "Filter(",
              "'UAM Attributes',",
              "'UAM Attributes'[EmailAddress]=USERPRINCIPALNAME() && 'UAM Attributes'[ATTRIBUTE]=\"BU\"",
              ")",
              ",'UAM Attributes'[DATAVALUE])<>\"All BUs\",",
              "[SecurityBU1] IN",
              "CALCULATETABLE(",
              "VALUES('UAM Attributes'[DATAVALUE]),",
              "FILTER (",
              "ALL ( 'UAM Attributes'),",
              "'UAM Attributes'[EmailAddress]=USERPRINCIPALNAME()&& 'UAM Attributes'[ATTRIBUTE]=\"BU\"))",
              "||",
              "[SecurityBU2] IN",
              "CALCULATETABLE(",
              "VALUES('UAM Attributes'[DATAVALUE]),",
              "FILTER (",
              "ALL ( 'UAM Attributes'),",
              "'UAM Attributes'[EmailAddress]=USERPRINCIPALNAME()&& 'UAM Attributes'[ATTRIBUTE]=\"BU\"))",
              "||",
              "[SecurityBU3] IN",
              "CALCULATETABLE(",
              "VALUES('UAM Attributes'[DATAVALUE]),",
              "FILTER (",
              "ALL ( 'UAM Attributes'),",
              "'UAM Attributes'[EmailAddress]=USERPRINCIPALNAME()&& 'UAM Attributes'[ATTRIBUTE]=\"BU\"))",
              "",
              "||",
              "[BU 3] IN",
              "CALCULATETABLE(",
              "VALUES('UAM Attributes'[DATAVALUE]),",
              "FILTER (",
              "ALL ( 'UAM Attributes'),",
              "'UAM Attributes'[EmailAddress]=USERPRINCIPALNAME()&& 'UAM Attributes'[ATTRIBUTE]=\"BU\"))",
              "",
              ",1=1))",
              ""
            ]
          },
          {
            "name": "Geo Master",
            "filterExpression": [
              "If (\"Rolling Order Forecast\" IN CALCULATETABLE(VALUES('UAM Attributes'[DATAVALUE]),FILTER ( ALL ('UAM Attributes'),'UAM Attributes'[EmailAddress]=USERPRINCIPALNAME() && 'UAM Attributes'[ATTRIBUTE]=\"Modules\" && 'UAM Attributes'[DATAVALUE]=\"Rolling Order Forecast\")),",
              "",
              "If(",
              "MaxX(",
              "Filter(",
              "'UAM Attributes',",
              "'UAM Attributes'[EmailAddress]=USERPRINCIPALNAME()",
              "&& 'UAM Attributes'[ATTRIBUTE]=\"Regions / Subregions\"",
              ")",
              ",'UAM Attributes'[DATAVALUE])<>\"All Geos\",",
              "",
              "(",
              "[Region] IN",
              "CALCULATETABLE(",
              "VALUES('UAM Attributes'[DATAVALUE]),",
              "FILTER (",
              "ALL ( 'UAM Attributes'),",
              "'UAM Attributes'[EmailAddress]=USERPRINCIPALNAME()",
              "&& 'UAM Attributes'[ATTRIBUTE]=\"Regions / Subregions\"))",
              "||",
              "[SubRegion1] IN",
              "CALCULATETABLE(",
              "VALUES('UAM Attributes'[DATAVALUE]),",
              "FILTER (",
              "ALL ( 'UAM Attributes'),",
              "'UAM Attributes'[EmailAddress]=USERPRINCIPALNAME()",
              "&& 'UAM Attributes'[ATTRIBUTE]=\"Regions / Subregions\"))",
              "|| [SubRegion2] IN",
              "CALCULATETABLE(",
              "VALUES('UAM Attributes'[DATAVALUE]),",
              "FILTER (",
              "ALL ( 'UAM Attributes'),",
              "'UAM Attributes'[EmailAddress]=USERPRINCIPALNAME()&& 'UAM Attributes'[ATTRIBUTE]=\"Regions / Subregions\")",
              ")",
              "|| [SubRegion3] IN",
              "CALCULATETABLE(",
              "VALUES('UAM Attributes'[DATAVALUE]),",
              "FILTER (",
              "ALL ( 'UAM Attributes'),",
              "'UAM Attributes'[EmailAddress]=USERPRINCIPALNAME()&& 'UAM Attributes'[ATTRIBUTE]=\"Regions / Subregions\")",
              ")",
              "|| [Country] IN",
              "CALCULATETABLE(",
              "VALUES('UAM Attributes'[DATAVALUE]),",
              "FILTER (",
              "ALL ( 'UAM Attributes'),",
              "'UAM Attributes'[EmailAddress]=USERPRINCIPALNAME()&& 'UAM Attributes'[ATTRIBUTE]=\"Regions / Subregions\")",
              "))",
              ",1=1))"
            ]
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "ROF Forecast",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "FiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb08bc9d-bcb9-4c2b-99bb-ae7a3f82bc5d",
            "sourceColumn": "FiscalQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "153ac0c3-2981-40c6-9764-c794893b446b",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Geography",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6bcce2f4-8c9c-47e7-88f8-2b484675a8a9",
            "sourceColumn": "Geography",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68b90f18-45db-43ea-95f4-52f7b7107a24",
            "sourceColumn": "WeekNo",
            "summarizeBy": "none"
          },
          {
            "name": "BackLog",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2e1fb203-8ff7-40c4-b28b-32aa7fa3aff8",
            "sourceColumn": "BackLog",
            "summarizeBy": "sum"
          },
          {
            "name": "execBacklog",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1fca044a-c1b0-4614-9972-f7f6ef538c23",
            "sourceColumn": "execBacklog",
            "summarizeBy": "sum"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f173be4e-3798-4399-b655-15d645c8f105",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbd19afa-06c2-40e6-9fb0-9b1c5564926a",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ColumnWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50f5d12c-6a43-4594-a46e-e04629070ebb",
            "sourceColumn": "ColumnWeek",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b02e4c15-2ba6-4755-b24d-d7b32c194dbe",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Prod Master'[ProductKey])",
            "isDataTypeInferred": true,
            "lineageTag": "3d8c76cf-ff04-4230-87d6-69d2eea72fde",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Clari/ROF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d59fc2d7-7aaf-41da-8537-bfccc23e994f",
            "sourceColumn": "Clari/ROF",
            "summarizeBy": "none"
          },
          {
            "name": "Forecast Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF('ROF Forecast'[Clari/ROF]=\"Unadjusted (Clari)\",RELATED('Geo Master'[Clari Forecast Toggle]),\"ROF Forecast\")",
            "isDataTypeInferred": true,
            "lineageTag": "4d20c1e2-ecac-40cb-971b-8110ca6b5746",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "f3c130a6-80b7-4d99-b2a0-2f6179606b0d",
        "partitions": [
          {
            "name": "ROF Forecast-e4596ecb-ff4b-4dd9-a758-892308ac8241",
            "mode": "import",
            "queryGroup": "ROF Group\\Facts",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"fact ROF_Forecast_Sheet\" = Source{[Schema=\"fact\",Item=\"ROF_Forecast\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"fact ROF_Forecast_Sheet\",{\"CountryCode\", \"BusinessAreaCode\", \"Geo\", \"budget\",  \"id\", \"UpdatedBy\", \"UpdatedTime\", \"Total\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Columns\", \"Clari/ROF\", each \"ROF\"),",
                "    #\"Appended Query\" = Table.Combine({#\"Added Custom\", ROF_Clari_Final}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Appended Query\", {\"FiscalQuarter\", \"Region\", \"BU\", \"WeekNo\", \"GeoKey\", \"ProductKey\", \"BackLog\", \"execBacklog\",\"Geography\",\"Clari/ROF\",\"DataType\",\"Country\"}, \"ColumnWeek\", \"Value\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Unpivoted Other Columns\",{{\"FiscalQuarter\", type text}, {\"Region\", type text}, {\"BU\", type text}, {\"WeekNo\", type text}, {\"GeoKey\", type text}, {\"ProductKey\", type text}, {\"ColumnWeek\", type text}, {\"Value\", type number}, {\"BackLog\", type number}, {\"execBacklog\", type number}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each true),",
                "    #\"Filled Down\" = Table.FillDown(#\"Filtered Rows\",{\"FiscalQuarter\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Filled Down\",{\"BU\", \"Country\", \"DataType\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ROF OrderPlan",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "fiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55160050-b8af-441e-9ffb-7722922006f0",
            "sourceColumn": "fiscalQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d054ddb0-8d09-45f0-add8-2b6f3da11639",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Geography",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "767e216e-f81b-4a30-a9ed-cbb8da819223",
            "sourceColumn": "Geography",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2cbe9d2-72f2-4c04-9b0d-d10949e518ed",
            "sourceColumn": "WeekNo",
            "summarizeBy": "none"
          },
          {
            "name": "OrderPlanValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "28a83a6e-0d54-4347-b6c0-90d1a2988fca",
            "sourceColumn": "OrderPlanValue",
            "summarizeBy": "sum"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06cfc470-ab03-482e-870e-c339f57e5658",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Geo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec6eb20e-6599-427f-b772-670fe77058c6",
            "sourceColumn": "Geo",
            "summarizeBy": "none"
          },
          {
            "name": "Plan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "373af0f6-18a3-4cc2-923c-4379e25dca6c",
            "sourceColumn": "Plan",
            "summarizeBy": "none"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f527bd3b-b160-4871-a03f-b8965b410f4b",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7be5cdd2-d84e-447d-a5e8-af4663ca2aac",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e758b9f1-bd70-4817-871c-c2e107ec9cde",
        "partitions": [
          {
            "name": "ROF OrderPlan-3067cae7-b374-452b-8d2a-08cc58a89989",
            "mode": "import",
            "queryGroup": "ROF Group\\Facts",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"fact ROF_Forecast_Sheet\" = Source{[Schema=\"fact\",Item=\"ROF_OrderPlan\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"fact ROF_Forecast_Sheet\",{\"fiscalQuarter\", \"Region\", \"Geography\", \"BU\", \"WeekNo\", \"OrderPlanValue\", \"Status\", \"Geo\", \"Plan\", \"GeoKey\", \"ProductKey\", \"BusinessAreaCode\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Other Columns\",{{\"fiscalQuarter\", type text}, {\"Region\", type text}, {\"Geography\", type text}, {\"BU\", type text}, {\"WeekNo\", type text}, {\"OrderPlanValue\", type number}, {\"Status\", type text}, {\"Geo\", type text}, {\"Plan\", type text}, {\"GeoKey\", type text}, {\"ProductKey\", type text}, {\"BusinessAreaCode\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"BusinessAreaCode\", \"BU\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Non Executable",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7949b9fc-f805-4e1b-b45c-68c9c5e7bc27",
            "sourceColumn": "FiscalQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e9dd4b1-d3fe-4e90-8831-3a5c12236f78",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Geography",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8c39a8d-d6e6-40ee-93bc-13fb6ef018b2",
            "sourceColumn": "Geography",
            "summarizeBy": "none"
          },
          {
            "name": "BU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c376a5d-ee8c-4cdf-a3dc-88df8b7d20ea",
            "sourceColumn": "BU",
            "summarizeBy": "none"
          },
          {
            "name": "Weekno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a35ebc2-1c7d-45ea-aff0-bd7ea308b1c0",
            "sourceColumn": "Weekno",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "85179dee-c23c-4d8b-8b6e-46567cf5f0aa",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58bf2c1b-52e0-4383-8c9e-e0c204b11b5a",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4eda77f-30f5-4dad-8fc0-885e2ea3ae90",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87dd8c33-cccc-4544-ae02-126b15d609ad",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessAreaCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8b49db3-26a7-4c22-b8b2-4da3adc004c0",
            "sourceColumn": "BusinessAreaCode",
            "summarizeBy": "none"
          },
          {
            "name": "MonthPlan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4d4d5e1-83f6-4371-b3d6-f885bfd23492",
            "sourceColumn": "MonthPlan",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "67e828a3-9519-4b22-93ed-a790d86d99aa",
        "partitions": [
          {
            "name": "Non Executable-1b939eb4-1be1-4fb1-80cb-21d8a5a20467",
            "mode": "import",
            "queryGroup": "ROF Group\\Facts",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"fact ROF_NonExecutableOrders_Sheet\" = Source{[Schema=\"fact\",Item=\"ROF_NonExecutableOrders\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"fact ROF_NonExecutableOrders_Sheet\", each true),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"FiscalQuarter\", type text}, {\"Region\", type text}, {\"Geography\", type text}, {\"BU\", type text}, {\"Weekno\", type text}, {\"Value\", type number}, {\"UpdatedBy\", type any}, {\"UpdatedTime\", type any}, {\"id\", type text}, {\"GeoKey\", type text}, {\"CountryCode\", type any}, {\"ProductKey\", type text}, {\"BusinessAreaCode\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"UpdatedBy\", \"UpdatedTime\", \"CountryCode\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Pipeline",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ForecastCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d0b5fe3-6e29-4b26-90b7-e174fc06766e",
            "sourceColumn": "ForecastCategory",
            "summarizeBy": "none"
          },
          {
            "name": "SalesStage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77ecd9f1-c6d2-4f77-ae9a-23f4507be998",
            "sourceColumn": "SalesStage",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "08a872a1-930a-4e8d-a158-f09b4d8962ea",
            "sourceColumn": "Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d0f800a-5e14-4a64-aedc-1ae9a943e8bc",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cbd4b6b-ba4c-4d75-9cff-a5dac97096b7",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d59f07f-300f-4940-bab8-bac3cce42fbb",
            "sourceColumn": "WeekNo",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1e41dd25-acbb-4e1f-ba64-ea90ba7a9d32",
        "partitions": [
          {
            "name": "Pipeline-e2d9dbad-3bb2-470d-b639-5bf78e01ef03",
            "mode": "import",
            "queryGroup": "ROF Group\\Facts",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"fact ROF_Pipeline_Sheet\" = Source{[Schema=\"fact\",Item=\"ROF_Pipeline\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"fact ROF_Pipeline_Sheet\",{{\"Country\", type text}, {\"ForecastCategory\", type text}, {\"SalesStage\", type text}, {\"WeekNo\", type text}, {\"Revenue\", type number}, {\"GeoKey\", type text}, {\"ProductKey\", type text}, {\"BusinessAreaCode\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"WeekNo\", \"WeekNo1\"}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Renamed Columns\", \"WeekNo\", each if [WeekNo1] = \"W1\" then \"W2\" else if [WeekNo1] = \"W13-1\" then \"W13\" else [WeekNo1]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"BusinessAreaCode\", \"Country\", \"DealBased_In/Out\", \"WeekNo1\", \"SalesMotion\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FlashBudget",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "416d1433-d4c6-46b9-83f3-bf420b3365ba",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "109747d8-4113-4687-9462-b39a81c321d1",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "Level_5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5581018-7db5-483d-a917-c7a2c2234280",
            "sourceColumn": "Level_5",
            "summarizeBy": "none"
          },
          {
            "name": "Flash",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "243b2e65-811c-4bbf-a232-a935dff3c5f5",
            "sourceColumn": "Flash",
            "summarizeBy": "sum"
          },
          {
            "name": "Budget",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7010726a-8938-4af7-9cc7-b466702a27d1",
            "sourceColumn": "Budget",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "bc4d5059-1cfb-4425-bd41-ddc82aaec59b",
        "partitions": [
          {
            "name": "FlashBudget-f700cd7c-f574-469f-825a-f5aab5f43edc",
            "mode": "import",
            "queryGroup": "ROF Group\\Facts",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"ROF_FlashBudget_Sheet\" = Source{[Schema=\"fact\",Item=\"ROF_FlashBudget\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(ROF_FlashBudget_Sheet,{\"FiscalQuarter\", \"CountryCode\", \"GeoKey\", \"Country\", \"BusinessAreaCode\", \"ProductKey\", \"Level_5\", \"Flash\", \"Budget\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Other Columns\",{ {\"FiscalQuarter\", type text}, {\"CountryCode\", type text}, {\"GeoKey\", type text}, {\"Country\", type text}, {\"BusinessAreaCode\", type text}, {\"ProductKey\", type text}, {\"Level_5\", type text}, {\"Flash\", type number}, {\"Budget\", type number}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"BusinessAreaCode\", \"Country\", \"CountryCode\", \"FiscalQuarter\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EOP",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0545ede1-c4d0-4c79-9e6b-15d43e53c3ae",
            "sourceColumn": "WeekNo",
            "summarizeBy": "none"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5dcce7a5-97d9-40b8-98c4-a7495ae7ca62",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "107a9ac9-120b-4091-a282-5b5f3bef6b7f",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "EOPValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7490bc7a-4092-41d6-a917-fc5a33814130",
            "sourceColumn": "EOPValue",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthPlan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be270b08-a9fe-4ee6-8228-4ef7133e2f95",
            "sourceColumn": "MonthPlan",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6818aee6-1556-4794-9f74-194de656932f",
        "partitions": [
          {
            "name": "EOP-4d8e885a-f58b-4341-b4c2-fb651ff43406",
            "mode": "import",
            "queryGroup": "ROF Group\\Facts",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"ROF_ExecutableOrdersPlan_Sheet\" = Source{[Schema=\"fact\",Item=\"ROF_ExecutableOrdersPlan\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(ROF_ExecutableOrdersPlan_Sheet,{{\"FiscalQuarter\", type text}, {\"WeekNo\", type text}, {\"Country\", type text}, {\"GeoKey\", type text}, {\"BU\", type text}, {\"ProductKey\", type text}, {\"BusinessAreaCode\", type text}, {\"EOPValue\", type number}, {\"MonthPlan\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"BU\", \"BusinessAreaCode\", \"Country\", \"FiscalQuarter\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ROF BudgetPlan",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "fiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d13acd6-f56b-448d-84f7-c56f6459bdcd",
            "sourceColumn": "fiscalQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "Geography",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49050bf0-cd8e-4fb0-b82e-d77de7cb3c62",
            "sourceColumn": "Geography",
            "summarizeBy": "none"
          },
          {
            "name": "BU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee9a373a-fce4-4e7c-87a4-333cb14abc78",
            "sourceColumn": "BU",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48517724-9ad4-4880-819b-19750bfd4749",
            "sourceColumn": "WeekNo",
            "summarizeBy": "none"
          },
          {
            "name": "BudgetPlanValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "da7d7976-6673-4a75-b1d3-37966c429e34",
            "sourceColumn": "BudgetPlanValue",
            "summarizeBy": "sum"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85f6a939-51ce-450e-8715-99d150561f49",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d032666-bc6c-42f9-97bd-fbce88e75a51",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1fbbc4c-fa67-4e5d-af46-4ba752474314",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "edb9cf16-920c-4c02-a7f6-d6c47afc2473",
        "partitions": [
          {
            "name": "ROF BudgetPlan-ec95973a-e1f3-4a91-a2bd-99f905143284",
            "mode": "import",
            "queryGroup": "ROF Group\\Facts",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"fact ROF_Forecast_Sheet\" = Source{[Schema=\"fact\",Item=\"ROF_BudgetPlan\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"fact ROF_Forecast_Sheet\",{\"CountryCode\", \"Geo\", \"Plan\", \"UpdatedBy\", \"UpdatedTime\", \"Region\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"fiscalQuarter\", type text}, {\"Geography\", type text}, {\"BU\", type text}, {\"WeekNo\", type text}, {\"BudgetPlanValue\", type number}, {\"Status\", type text}, {\"GeoKey\", type text}, {\"ProductKey\", type text}, {\"BusinessAreaCode\", type text}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type\",{\"BusinessAreaCode\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ColWkSorting",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Weeks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "588e33ae-bb16-4943-8ef5-9ff96b88f77a",
            "sortByColumn": "SortOrder",
            "sourceColumn": "Weeks",
            "summarizeBy": "none"
          },
          {
            "name": "SortOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e9f0c77-a1eb-4a2e-9eac-cdc0e6d486bd",
            "sourceColumn": "SortOrder",
            "summarizeBy": "sum"
          },
          {
            "name": "IsCurrentWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7743264-0188-4ab9-aa72-05d19bd59297",
            "sourceColumn": "IsCurrentWeek",
            "summarizeBy": "none"
          },
          {
            "name": "Open/Close",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9534e69b-c4a9-49f0-b843-60d2fa14fbc0",
            "sourceColumn": "Open/Close",
            "summarizeBy": "none"
          },
          {
            "name": "Weeksdyn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(ColWkSorting[IsCurrentWeek]=\"True\", \"CurrWeek\")",
              "/*VAR A = CALCULATE(MAX(ColWkSorting[SortOrder]),FILTER('ColWkSorting',ColWkSorting[IsCurrentWeek]=\"True\"))",
              "VAR B = IF(WEEKDAY(TODAY()) >=4 && VALUES('rpt dim_current_date_rof'[Actualsavaialble])=\"Y\",A+1,A)",
              "--IF(WEEKDAY(TODAY())=4,A+1,A)",
              "Return ",
              "IF(ColWkSorting[SortOrder]=B,\"CurrWeek\",BLANK())*/",
              "",
              "",
              "--IF(ColWkSorting[IsCurrentWeek]=\"True\", \"CurrWeek\")",
              " ",
              "",
              " ",
              "            "
            ],
            "isDataTypeInferred": true,
            "lineageTag": "d528e4a6-1df3-4ae9-a30a-9b94e358a76b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "WKDyn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "VAR A = CALCULATE(MAX(ColWkSorting[SortOrder]),FILTER('ColWkSorting',ColWkSorting[Weeksdyn]=\"CurrWeek\"))",
              "VAR B = IF(WEEKDAY(TODAY()) >=4 && VALUES('rpt dim_current_date_rof'[Actualsavaialble])=\"Y\",A,A-1) --IF(WEEKDAY(TODAY())>=4,A-1,A)",
              "Return ",
              "IF(ColWkSorting[SortOrder]=B,\"CurrWeek-1\",BLANK())",
              "",
              "",
              "--- changed 12-14-2023",
              "/*WKDyn = VAR A = CALCULATE(MAX(ColWkSorting[SortOrder]),FILTER('ColWkSorting',ColWkSorting[Weeksdyn]=\"CurrWeek\"))",
              "VAR B = IF(WEEKDAY(TODAY()) >=4 && VALUES('rpt dim_current_date_rof'[Actualsavaialble])=\"Y\",A,A-1) --IF(WEEKDAY(TODAY())>=4,A-1,A)",
              "Return ",
              "IF(ColWkSorting[SortOrder]=B,\"CurrWeek-1\",BLANK())*/",
              "",
              "",
              "/*",
              "----------",
              "VAR A = CALCULATE(MAX(ColWkSorting[SortOrder]),FILTER('ColWkSorting',ColWkSorting[Weeksdyn]=\"CurrWeek\"))",
              "VAR B = (A-1)",
              "Return",
              "IF(ColWkSorting[SortOrder]=B,\"CurrWeek-1\",BLANK())",
              "----------",
              "*/",
              "/**CALCULATE(MAX(ColWkSorting[SortOrder]),FILTER('ColWkSorting',ColWkSorting[Weeksdyn]=\"CurrWeek\"))",
              "VAR B =  (A+1)",
              "VAR C =  (A+2)",
              "Return",
              "",
              "IF(ColWkSorting[Weeksdyn]=\"CurrWeek\",\"CurrWeek\",",
              "IF(ColWkSorting[SortOrder]=B,\"CurrWeek+1\",",
              "IF(ColWkSorting[SortOrder]=C,\"CurrWeek+2\",BLANK())))**/",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "ab428912-2bde-4960-ab98-e5caf8ad47c9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "WEEKDAY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKDAY(TODAY())",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "68282fe8-6375-4a80-92ff-056254a5d403",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "CLARIWk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "Var Today = TODAY()",
              "Var ClariRefresh = DATEVALUE(CALCULATE(max(DataRefreshConfig[RefreshDate]),FILTER(DataRefreshConfig,DataRefreshConfig[Source]=\"Clari\")))",
              "Var DayinWeek= WEEKDAY(Today,2)",
              "--Var WK = CALCULATE(MAX(ColWkSorting[SortOrder]),FILTER('ColWkSorting',ColWkSorting[Weeksdyn]=\"CurrWeek\"))",
              "Var WK = CALCULATE(MAX(ColWkSorting[SortOrder]),FILTER('ColWkSorting',ColWkSorting[IsCurrentWeek]=\"True\"))",
              "Var Wk_Next = Wk+1",
              "",
              "Var ClariWktoShow = IF(DayinWeek=1 && ClariRefresh<Today,Wk,",
              "                         IF(DayinWeek=1 && ClariRefresh=Today,WK_Next,",
              "                             IF(DayinWeek in {2,3},WK_Next,",
              "                                 IF(DayinWeek >3,WK))))",
              "Return ",
              "--IF(DayinWeek=1 && ClariRefresh=Today,WK_Next,0)",
              "IF(ClariWktoShow=ColWkSorting[SortOrder],\"Curr Wk\",ColWkSorting[Weeks])",
              ""
            ],
            "lineageTag": "71bf498a-e171-4813-a39c-78e7364cc240",
            "sortByColumn": "SortOrder",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QTD Monthly Plan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF('ColWkSorting'[Weeks] in {\"W1\",\"W2\",\"W3\",\"W4\",\"W5\"},\"QTD M1 Plan\",",
              "IF(ColWkSorting[Weeks] in {\"W6\",\"W7\",\"W8\",\"W9\",\"W10\"},\"QTD M2 Plan\",\"QTD M3 Plan\"))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "cfa82ad5-3bda-4851-be2a-1a23f4efc5b6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "8c2f4f7c-1a97-49fd-959d-d8126ebb3019",
        "partitions": [
          {
            "name": "ColWkSorting-db2008e9-6e4b-4d6c-9ac8-f4b860f9f3d8",
            "mode": "import",
            "queryGroup": "ROF Group\\Dims",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"Nc3JDcAgEEPRXuZMJMxOJTkg+m8jHkxuz5Klv5a9sGCwHchEJjGTWSxkEStZxUY2sZNdHOQQJzlFRG/EO07wFuFJ3CY8ivyP5xxZ3h8=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Weeks = _t, SortOrder = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Weeks\", type text}, {\"SortOrder\", Int64.Type}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"IsCurrentWeek\", each if [SortOrder] = CurrWeek1 then \"True\" else \"False\"),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"Open/Close\", each if [SortOrder]>=CurrWeek1 then \"Open\" else \"Close\")",
                "in",
                "    #\"Added Custom1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Geo Master",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62d0039c-819a-466a-aaa3-94b4164995aa",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "SubRegion1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1a8e574-7548-4756-835d-970cf22709bb",
            "sortByColumn": "Sort",
            "sourceColumn": "SubRegion1",
            "summarizeBy": "none"
          },
          {
            "name": "SubRegion2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f804f325-fbb6-4bb3-9ee9-4ea7edab03b5",
            "sourceColumn": "SubRegion2",
            "summarizeBy": "none"
          },
          {
            "name": "SubRegion3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc48dddc-dc7e-4922-816f-0459ab2647bf",
            "sourceColumn": "SubRegion3",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ec9b290-971f-46bc-9164-fa4f2a122487",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74649b86-34e7-40fe-914a-28ab082e2cb0",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "MOBORegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc76b253-95ac-45f0-91d9-7dddeafb998e",
            "sourceColumn": "MOBORegion",
            "summarizeBy": "none"
          },
          {
            "name": "SLICER_region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF('Geo Master'[MOBORegion] = \"Y\", \"MOBO\")",
            "isDataTypeInferred": true,
            "lineageTag": "d9ad0a4f-1ac3-4d75-827e-7fcea058a147",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Clari Forecast Toggle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "     IF('Geo Master'[Country] in {\"India\",\"Japan\"} || (SEARCH(\"HQ\",'Geo Master'[Country],1,0)>0 && 'Geo Master'[Country]<>\"MCA HQ\" && 'Geo Master'[Country]<>\"Germany HQ\"),\"GEO Forecast\",\"Country Forecast\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2a1d6a09-1df6-42e7-a72e-025515303bba",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "RegionMoBo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "595d13e9-af22-4a0a-af0e-61fc0fac1b1d",
            "sourceColumn": "RegionMoBo",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RELATED('Geo Master Sorting'[Sort])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "006dbbb5-6e52-4461-8818-007b1f1ae706",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "354305d6-2c1a-42a3-86c3-500f363ab8a0",
        "partitions": [
          {
            "name": "Geo Master-6d08d331-9d47-4975-8bdd-42fe794831aa",
            "mode": "import",
            "queryGroup": "ROF Group\\Dims",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"ROF_Geography_Sheet\" = Source{[Schema=\"dim\",Item=\"ROF_Geography\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(ROF_Geography_Sheet,{{\"Region\", type text}, {\"SubRegion1\", type text}, {\"SubRegion2\", type text}, {\"SubRegion3\", type text}, {\"Country\", type text}, {\"CountryCode\", type text}, {\"GeoKey\", type text}, {\"KeyType\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"CountryCode\", \"KeyType\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "RowWkSorting",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fad2045-73a8-4cf2-9617-2f66be9fd74a",
            "sortByColumn": "SortOrder",
            "sourceColumn": "Week",
            "summarizeBy": "none"
          },
          {
            "name": "SortOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4c4466a1-2d5e-41a4-aa31-869e6373d0dc",
            "sourceColumn": "SortOrder",
            "summarizeBy": "sum"
          },
          {
            "name": "IsCurrentWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cff9aab1-250f-45c2-a7db-b589c5c38645",
            "sourceColumn": "IsCurrentWeek",
            "summarizeBy": "none"
          },
          {
            "name": "Open/Close",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bc5b202-bf18-4308-93ea-1dcbdf3ed0c7",
            "sourceColumn": "Open/Close",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e55ec34e-a3f9-4312-b971-60ffc1401177",
        "partitions": [
          {
            "name": "RowWkSorting-e5b3447c-4704-4c27-9bf0-1a9823e3368d",
            "mode": "import",
            "queryGroup": "ROF Group\\Dims",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"Lc67EcAgEAPRVjyXmgDxpxIHDP23YYkjfBvtWvbheR9kCwbbgU5yopM7y6Czu8iRLu5KT7I6GznI5uxkJ7tzkI0czklWcjoR6aKVeIPmztudg+40h3uHs6dw96A/7YF/+wc=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Week = _t, SortOrder = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Week\", type text}, {\"SortOrder\", Int64.Type}}),",
                "    Custom1 = Table.AddColumn(#\"Changed Type\", \"IsCurrentWeek\", each if [SortOrder] = CurrWeek1 then \"True\" else \"False\"),",
                "    Custom2 = Table.AddColumn(#\"Custom1\", \"Open/Close\", each if [SortOrder]>=CurrWeek1 then \"Open\" else \"Close\")",
                "in",
                "    Custom2"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Prod Master",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "BU 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "20ac41c0-1598-4e58-9038-5a104132ceb1",
            "sortByColumn": "Sort 3",
            "sourceColumn": "BU 1",
            "summarizeBy": "none"
          },
          {
            "name": "BU 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "e50e70b0-6579-4e40-9ec3-2de5fa0b7a7a",
            "sortByColumn": "Sort",
            "sourceColumn": "BU 2",
            "summarizeBy": "none"
          },
          {
            "name": "BU 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b30905bb-c38c-43af-aa2e-6fffb6a59a46",
            "sourceColumn": "BU 3",
            "summarizeBy": "none"
          },
          {
            "name": "BU 4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "388b4c3c-0f81-4c34-9311-7067408421fc",
            "sourceColumn": "BU 4",
            "summarizeBy": "none"
          },
          {
            "name": "Prod Categ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d5d8008-d51d-4142-8aa4-60293113ea9e",
            "sortByColumn": "Sort1",
            "sourceColumn": "Prod Categ",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bc3fd1f-2cfd-4204-bc84-c460d8375ee9",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "SecurityBU1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a67a2c9-40e4-4768-bab6-4030c2bb88d4",
            "sourceColumn": "SecurityBU1",
            "summarizeBy": "none"
          },
          {
            "name": "SecurityBU2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb8df147-c2e3-4966-a0ee-38fdcc3ab3d9",
            "sourceColumn": "SecurityBU2",
            "summarizeBy": "none"
          },
          {
            "name": "SecurityBU3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae6c1155-4193-4ec7-a843-15095e8f7d40",
            "sourceColumn": "SecurityBU3",
            "summarizeBy": "none"
          },
          {
            "name": "Sort1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "int64",
            "expression": "RELATED('Prod Master Sorting (Prod categ)'[Sort])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "8ce91beb-37a9-4811-94d7-65c5ace6e668",
            "sortByColumn": "Sort",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Sort 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RELATED('Prod Master Sorting (BU)'[Sort])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "13fccf73-42fe-46a6-b731-b38e706c7757",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Sort 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RELATED('Prod Master Sorting (Alternate BU)'[Sort])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a6a80cdf-d4f8-41aa-9987-c8214851c2c6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "level_0",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66742802-384f-4cf6-9b0c-61e77bd557e3",
            "sourceColumn": "level_0",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5a03f412-b882-438f-8fc7-66918ecb8646",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3c996550-e1aa-42b8-b8b0-0185a162034e",
        "partitions": [
          {
            "name": "Prod Master-e2678f14-498e-4190-9083-6e47c2b3606d",
            "mode": "import",
            "queryGroup": "ROF Group\\Dims",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"ROF_Product_Sheet\" = Source{[Schema=\"dim\",Item=\"ROF_Product\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(ROF_Product_Sheet,{{\"Level_1\", type text}, {\"Level_2\", type text}, {\"Level_3\", type text}, {\"Level_4\", type text}, {\"Level_5\", type text}, {\"ProductKey\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Level_1\", \"BU 1\"}, {\"Level_2\", \"BU 2\"}, {\"Level_3\", \"BU 3\"}, {\"Level_4\", \"BU 4\"}, {\"Level_5\", \"Prod Categ\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calcs",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "27c1ed25-26db-454b-a3a0-75e603d3fada",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9268681a-580f-44c8-bf19-d9083ca30fc0",
        "measures": [
          {
            "name": "Forecast Value",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR DisplayValue =",
              "SUMX(",
              "    SUMMARIZE(",
              "        'ROF Forecast',",
              "        'ROF Forecast'[GeoKey],",
              "        'ROF Forecast'[ProductKey],",
              "        ColWkSorting[SortOrder],",
              "        ColWkSorting[Weeks],",
              "        RowWkSorting[Week],",
              "        RowWkSorting[SortOrder],",
              "        'ROF Forecast'[Value]",
              "    ),",
              "    'ROF Forecast'[Value]",
              ")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "11f0e3b4-a418-404a-8e52-68085477acf4"
          },
          {
            "name": "BBL",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Other Measures",
            "expression": [
              "VAR DisplayValue =",
              "SUMX(",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            'ROF Forecast',",
              "            'ROF Forecast'[GeoKey],",
              "            'ROF Forecast'[ProductKey]",
              "        ),",
              "        \"MAXVal\",",
              "        CALCULATE(MAX('ROF Forecast'[BackLog]),ALL('ROF Forecast'[Clari/ROF]),ALL('ROF Forecast'[Forecast Level]))",
              "    ),",
              "    [MAXVal]",
              ")",
              " Var Result = if([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "63e5c741-0799-4eec-8aab-35cd569fb7f3"
          },
          {
            "name": "EBBL",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Other Measures",
            "expression": [
              "VAR DisplayValue =",
              "SUMX(",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            'ROF Forecast',",
              "            'Geo Master'[GeoKey],",
              "            'Prod Master'[ProductKey]",
              "        ),",
              "        \"MAXVal\",",
              "        CALCULATE(MAX('ROF Forecast'[execBacklog]),ALL('ROF Forecast'[Clari/ROF]),ALL('ROF Forecast'[Forecast Level]))",
              "    ),",
              "    [MAXVal]",
              ")",
              "Var Result = if([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "6e36f19e-120b-4aae-beea-74d146d63ca3"
          },
          {
            "name": "vs Order Budget Plan",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "VAR DisplayValue =",
              "[Current Wk Forecast] - [Order Budget Plan]",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "",
              "Return",
              "Result"
            ],
            "formatString": "0.0",
            "lineageTag": "46f4105e-15a8-4506-9970-2bdf64d6c03b"
          },
          {
            "name": "vs Order Budget Plan Cum",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    [vs Order Budget Plan],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "d7ea09d3-f198-4df0-9942-1f474da5a44d"
          },
          {
            "name": "vs Plan_M1",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "",
              "VAR MonthValue = \"M1\"",
              "VAR TaskOption = SELECTEDVALUE('Task Option'[Value])",
              "VAR ConcatMonthValue = ",
              "    IF(",
              "        TaskOption = \"W Task\",",
              "        MonthValue & \"-Plan + Task\",",
              "        MonthValue & \"-Plan\"",
              "    )",
              "VAR MonthPlanTask = ",
              "    CALCULATE(",
              "        SUM('ROF OrderPlan'[OrderPlanValue]),",
              "        KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)",
              "    )",
              "VAR DisplayValue = [Current Wk Forecast] - MonthPlanTask",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "            IF(",
              "                TaskOption = \"W Task\",",
              "                MonthValue  ,",
              "                MonthValue",
              "            ),",
              "            Result",
              "        ),",
              "        Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "lineageTag": "697eb34a-36b8-4616-a3dc-f71ea3269ab5"
          },
          {
            "name": "vs Week Forecast",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "VAR DisplayValue =",
              " [Total C + U + LS] - [Forecast Value 1]",
              " VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "9394e81f-9768-4399-9d92-d3d92672b02f"
          },
          {
            "name": "% Executable",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([EBBL], [BBL]) ",
            "formatString": "0%;-0%;0%",
            "lineageTag": "5570fb1f-9e7f-4684-8322-fc5c12b8acbc"
          },
          {
            "name": "vs Rev Flash",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "",
              "VAR FlashTotal = [Revenue Flash]",
              "VAR Cumu_W14_Actuals = ",
              "    CALCULATE(",
              "        [Forecast Value],",
              "        FILTER(",
              "            ALL(ColWkSorting),",
              "            ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "        )",
              "        ,",
              "        KEEPFILTERS(RowWkSorting[Week] = \"W13 + 1\")",
              "   )",
              "RETURN",
              "  DIVIDE(",
              "        [EBBL] +",
              "        Cumu_W14_Actuals -",
              "        [Non Exec Cum],",
              "        FlashTotal",
              "    )",
              "   "
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "be25a23a-9392-4221-bfad-19f52de10cda"
          },
          {
            "name": "vs Rev Budget",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "",
              "VAR BudgetTotal = [Revenue Budget]",
              "VAR Cumu_W14_Actuals = ",
              "    CALCULATE(",
              "        [Forecast Value],",
              "        FILTER(",
              "            ALL(ColWkSorting),",
              "            ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "        )",
              "        ,",
              "       KEEPFILTERS(RowWkSorting[Week] = \"W13 + 1\")",
              "    )",
              "RETURN",
              "",
              "",
              " DIVIDE(",
              "        [EBBL] +",
              "        Cumu_W14_Actuals -",
              "        [Non Exec Cum],",
              "        BudgetTotal",
              "    )",
              "",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "c955850c-6b2b-42f8-921c-ed9bbfe61a15"
          },
          {
            "name": "Dummy Metric",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "\"XX\"",
            "lineageTag": "61f7d5fd-acd9-4be9-9c42-972184455755"
          },
          {
            "name": "Dummy2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "10^6",
            "formatString": "0",
            "lineageTag": "aed8d21d-67bc-4254-94b3-0dd33b4ebca0"
          },
          {
            "name": "Diagonal CF",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR CurrentRow = SELECTEDVALUE(RowWkSorting[SortOrder])",
              "VAR CurrentCol = SELECTEDVALUE(ColWkSorting[SortOrder])",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        --SELECTEDVALUE(ColWkSorting[IsCurrentWeek]) = \"TRUE\", \"#CAE4EB\",",
              "        CurrentRow >= CurrentCol && CurrentCol <> BLANK() && CurrentRow <> BLANK(), \"#D9D9D9\"",
              "    )"
            ],
            "lineageTag": "1c4b9da4-1b68-4468-937a-0405d6d9021a"
          },
          {
            "name": "CurrentWeek CFFont",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE(ColWkSorting[IsCurrentWeek]) = \"TRUE\", \"#000000\"",
              ")"
            ],
            "lineageTag": "067c4b4d-47f5-416a-b5df-c8e2c15e1f5c"
          },
          {
            "name": "CurrentWeek CF",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE(ColWkSorting[IsCurrentWeek]) = \"TRUE\", \"#CAE4EB\"",
              ")"
            ],
            "lineageTag": "7bf6b46e-ac19-4872-b615-4932c8a8957d"
          },
          {
            "name": "Non Exec Cum",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Other Measures",
            "expression": [
              "VAR DisplayValue =",
              "CALCULATE(",
              "    [Non Exec Total],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")",
              "Var Result = if([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "5f42d24e-fa57-4114-a8f5-a913f65f59cb"
          },
          {
            "name": "Non Exec Total",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Other Measures",
            "expression": [
              "",
              "VAR DisplayValue =calculate(SUM('Non Executable'[Value]),'Non Executable'[MonthPlan]=\"M1\")",
              "Var Result = if([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result"
            ],
            "formatString": "0.0",
            "lineageTag": "7c16e0e8-b69b-41d0-808d-34b8906d2ff1"
          },
          {
            "name": "Commit",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Pipeline Measures",
            "expression": [
              "VAR DisplayValue =",
              "CALCULATE(",
              "    [Total Revenue],",
              "    KEEPFILTERS('Pipeline'[ForecastCategory] = \"Commit\" )",
              ")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "",
              "Return",
              "Result",
              "",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "2688cdb9-75f7-48b9-9f42-f93802387c62"
          },
          {
            "name": "Late Stage (SS 4-5)",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Pipeline Measures",
            "expression": [
              "VAR DisplayValue =",
              "    CALCULATE(",
              "        [Total Revenue],",
              "        KEEPFILTERS( 'Pipeline'[ForecastCategory] = \"Pipeline LS\" )",
              "    )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "",
              "Return",
              "Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "2228a810-95ef-48ca-b05a-ab7432d24427"
          },
          {
            "name": "Total C + U + LS",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Pipeline Measures",
            "expression": [
              "VAR DisplayValue = CALCULATE(",
              "    [Total Revenue], 'Pipeline'[ForecastCategory] IN{ \"Upside\",\"Commit\",\"Pipeline LS\"} )",
              "--[Commit] + [Late Stage (SS 4-5)] + [Upside]",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "--CONVERT(FORMAT(DisplayValue,\"0.0\"),DOUBLE),",
              "Return",
              "Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "5170b69e-c685-4d1a-9bd5-88c7b136d3d5"
          },
          {
            "name": "Total Revenue",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE(SUM(Pipeline[Revenue]), 10^6)",
            "formatString": "0.0",
            "lineageTag": "3e8590bb-4aca-4097-9df4-bd637732cc06"
          },
          {
            "name": "Upside",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Pipeline Measures",
            "expression": [
              "VAR DisplayValue =",
              "CALCULATE(",
              "    [Total Revenue],",
              "    KEEPFILTERS( 'Pipeline'[ForecastCategory] = \"Upside\" )",
              ")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "",
              "Return",
              "Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "4e320a37-b3d7-4d2c-8e68-ce7e2035be53"
          },
          {
            "name": "Plan + Task_M1",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR MonthValue =\"M1\"",
              "VAR ConcatMonthValue = MonthValue & \"-Plan + Task\"",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        SUM('ROF OrderPlan'[OrderPlanValue]), FILTER('ROF OrderPlan', 'ROF OrderPlan'[Plan]= ConcatMonthValue)",
              "       /* KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)*/",
              "    )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\"))) ",
              "RETURN",
              "IF(",
              "    ISINSCOPE(ColWkSorting[Weeks]),",
              "    IF(",
              "        SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "      LEFT(ConcatMonthValue,2),IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\"},BLANK(),",
              "      --LEFT(ConcatMonthValue,2),IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\",\"W2\"},BLANK(),",
              "            Result)",
              "        ",
              "    ),",
              "    Result",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "25cf3957-e93a-4ad9-b423-7b9bbd34cdc4"
          },
          {
            "name": "Order Budget Plan",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": [
              "",
              "--CALCULATE(",
              "  VAR Displayvalue =   SUM('ROF BudgetPlan'[BudgetPlanValue])--,",
              "    --'ROF OrderPlan'[Plan] = \"M1-Plan\"",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "--)",
              "Return",
              "IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\"},BLANK(),",
              "--IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\",\"W2\"},BLANK(),",
              "           Result)"
            ],
            "formatString": "#,0.0",
            "lineageTag": "e5ab2f12-0c39-489a-a1d4-484ab43a9f0a"
          },
          {
            "name": "M1 EOP Value",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": [
              "",
              "VAR CurrentMonth = \"M1\"",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        SUM(EOP[EOPValue]),FILTER(EOP,EOP[MonthPlan]=CurrentMonth)",
              "        /*KEEPFILTERS(EOP[MonthPlan] = CurrentMonth*/",
              "    )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))   ",
              "    RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "             CurrentMonth, IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\"},BLANK(),",
              "             --CurrentMonth, IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\",\"W2\"},BLANK(),",
              "            Result)",
              "        ),",
              "      Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "lineageTag": "f2174487-84fd-42e6-9d59-34e1a62bebdc"
          },
          {
            "name": "Revenue Flash",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": [
              "VAR DisplayValue = SUM(FlashBudget[Flash])",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "bb9ff2e7-9992-4f82-8d19-bafd81a0a2ca"
          },
          {
            "name": "Revenue Budget",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": [
              "VAR DisplayValue = SUM(FlashBudget[Budget])",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "51525b0e-bf59-459c-abab-4a9e353ad5c2"
          },
          {
            "name": "EBBL+CumAct-CumNonExeOrders",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR Cumu_W14_Actuals = ",
              "CALCULATE(",
              "[Forecast Value],",
              "FILTER(",
              "ALL(ColWkSorting),",
              "ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              ")",
              ",",
              "KEEPFILTERS(RowWkSorting[Week] = \"W13 + 1\")",
              ")",
              "RETURN",
              "([EBBL] +Cumu_W14_Actuals) -[Non Exec Cum]",
              "",
              "/*",
              "VAR Cumu_W14_Actuals = ",
              "CALCULATE(",
              "[Forecast Value],",
              "FILTER(",
              "ALL(ColWkSorting),",
              "ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              ")",
              ",",
              "KEEPFILTERS(RowWkSorting[Week] = \"W11 + 3\")",
              ")",
              "RETURN",
              "([EBBL] +Cumu_W14_Actuals) -[Non Exec Cum]",
              "*/"
            ],
            "formatString": "#,0.0",
            "lineageTag": "31106aab-33cf-454a-be1a-75ab57d85809"
          },
          {
            "name": "Current Wk Forecast",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [Forecast Value],",
              "    KEEPFILTERS(RowWkSorting[IsCurrentWeek] = \"TRUE\")",
              ")",
              "",
              "",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "9674cb1b-8adc-4d7f-ae81-3a33d67dae99"
          },
          {
            "name": "CF Arrows",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR M1Plan = [M1_M2_M3 MIX]",
              "VAR CurrRowWk = SELECTEDVALUE(RowWkSorting[SortOrder])",
              "VAR CurrColWk = SELECTEDVALUE(ColWkSorting[SortOrder])",
              "",
              "VAR CurrentWeek =CALCULATE([Forecast Value], ",
              "                    FILTER('ROF Forecast',",
              "                        CurrColWk = CurrRowWk",
              "                        )",
              "                )",
              "",
              "// VAR PrevWeek = // CALCULATE(",
              "// [Forecast Value],",
              "// FILTER(",
              "// ALL(ColWkSorting),",
              "// ColWkSorting[SortOrder] = CurrColWk - 1",
              "// ),",
              "// FILTER(",
              "// ALL(RowWkSorting),",
              "// RowWkSorting[SortOrder] = CurrRowWk - 1",
              "// )",
              "// )",
              "",
              "RETURN",
              "IF(",
              "    CurrColWk = CurrRowWk,",
              "        SWITCH(",
              "            TRUE(),",
              "                CurrentWeek > M1Plan, 1,",
              "                CurrentWeek = M1Plan, 2,",
              "                3",
              ")",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6d5c39bc-303f-4c89-9b77-7b6a18af224e"
          },
          {
            "name": "Orders",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Actuals & Forecast Measures",
            "expression": [
              "",
              "VAR Weekdisplayed = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(RowWkSorting[Week]),",
              "        RowWkSorting[IsCurrentWeek] = \"TRUE\"",
              "    )",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        [Forecast Value],",
              "        KEEPFILTERS(RowWkSorting[IsCurrentWeek] = \"TRUE\"), ",
              "        KEEPFILTERS(ColWkSorting[Open/Close] = \"Close\" || ColWkSorting[IsCurrentWeek]=\"True\" && VALUES('rpt dim_current_date_rof'[Actualsavaialble])=\"Y\"),",
              "        KEEPFILTERS('ROF Forecast'[Clari/ROF] = \"ROF\")",
              "",
              "    )",
              "  VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]), ",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(), ",
              "            Weekdisplayed, ",
              "            Result",
              "        ),",
              "        Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "lineageTag": "42a902cf-fa25-4126-8dc0-09fdbb79aab6"
          },
          {
            "name": "Cum Orders",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Actuals & Forecast Measures",
            "expression": [
              "",
              "VAR Weekdisplayed = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(RowWkSorting[Week]),",
              "        RowWkSorting[IsCurrentWeek] = \"TRUE\"",
              "    )",
              "VAR ValueDisplayed = ",
              "    IF(",
              "        [Orders]<> BLANK(),",
              "        CALCULATE(",
              "            [Forecast Value],",
              "            KEEPFILTERS(RowWkSorting[IsCurrentWeek] = \"TRUE\"), ",
              "            KEEPFILTERS(ColWkSorting[Open/Close] = \"Close\" ||ColWkSorting[IsCurrentWeek]=\"True\" && VALUES('rpt dim_current_date_rof'[Actualsavaialble])=\"Y\"),",
              "            KEEPFILTERS('ROF Forecast'[Clari/ROF] = \"ROF\"),",
              "            FILTER(",
              "                ALL(ColWkSorting),",
              "                ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "            )",
              "        )",
              "    )",
              "RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]), ",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(), ",
              "            Weekdisplayed, ",
              "            ValueDisplayed",
              "        ),",
              "        ValueDisplayed",
              "    )"
            ],
            "formatString": "#,0.0",
            "lineageTag": "ee5d2cf4-601a-4bc5-9d76-c701c7a35abd"
          },
          {
            "name": "M1_M2_M3 MIX",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR M1 = ",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W2\",\"W3\",\"W4\",\"W5\"}",
              "    )",
              "VAR M2 =  IF( [M2 Order Plan+Task]=0,",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W6\",\"W7\",\"W8\",\"W9\"}",
              "  ),CALCULATE(",
              "        [M2 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W6\",\"W7\",\"W8\",\"W9\"}))",
              "VAR M3 = IF([M3 Order Plan+Task]=0,",
              "            IF([M2 Order Plan+Task]=0,",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W10\",\"W11\",\"W12\",\"W13\"}),",
              "    ",
              "    CALCULATE(",
              "        [M2 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W10\",\"W11\",\"W12\",\"W13\"})),",
              "       ",
              "    CALCULATE(",
              "        [M3 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W10\",\"W11\",\"W12\",\"W13\"}",
              "    ))",
              "VAR DisplayValue =M1+M2+M3",
              "",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",CONVERT(FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\"),INTEGER)))",
              "RETURN",
              "Result",
              "    -- M1+M2+M3",
              "",
              "/*VAR M1 = ",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W3\",\"W4\",\"W5\",\"W6\"}",
              "    )",
              "VAR M2 =  IF( [M2 Order Plan+Task]=0,",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W7\",\"W8\",\"W9\",\"W10\"}",
              "  ),CALCULATE(",
              "        [M2 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W7\",\"W8\",\"W9\",\"W10\"}))",
              "VAR M3 = IF([M3 Order Plan+Task]=0,",
              "            IF([M2 Order Plan+Task]=0,",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W11\",\"W12\",\"W13\",\"W13-1\"}),",
              "    ",
              "    CALCULATE(",
              "        [M2 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W11\",\"W12\",\"W13\",\"W13-1\"})),",
              "       ",
              "    CALCULATE(",
              "        [M3 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W11\",\"W12\",\"W13\",\"W13-1\"}",
              "    ))",
              "VAR DisplayValue =M1+M2+M3",
              "",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",CONVERT(FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\"),INTEGER)))",
              "RETURN",
              "Result",
              "    -- M1+M2+M3",
              "    */",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "4497fe3f-ab00-4624-bc5a-9d1bb151d713"
          },
          {
            "name": "V/S Order Plan",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "IFERROR(",
              "    DIVIDE(",
              "        [Orders],",
              "        [M1_M2_M3 MIX]",
              "    ),",
              "    BLANK()",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "d327dde2-f327-4bb0-88f2-3d1b1698ef54"
          },
          {
            "name": "V/S Cum Order Plan",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "IFERROR(",
              "    DIVIDE(",
              "        [Cum Orders],",
              "        [Cum M1_M2_M3]",
              "    ),",
              "    BLANK()",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "fc887951-0c41-489a-b4eb-97fcbe4c62e6"
          },
          {
            "name": "M1 Order Plan+Task",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": [
              "VAR DisplayValue =",
              "CALCULATE(",
              "    SUM('ROF OrderPlan'[OrderPlanValue]),",
              "    'ROF OrderPlan'[Plan] = \"M1-Plan + Task\"",
              ")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))   ",
              "    Return",
              "    Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "82d89356-4fb3-4a24-8997-12cc7554b8d7"
          },
          {
            "name": "M2 Order Plan+Task",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": [
              "VAR DisplayValue =",
              "CALCULATE(",
              "    SUM('ROF OrderPlan'[OrderPlanValue]),",
              "    'ROF OrderPlan'[Plan] = \"M2-Plan + Task\"",
              ")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))   ",
              "    Return",
              " Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "db22a4ef-3640-4651-b53c-103e4b3ade95"
          },
          {
            "name": "M3 Order Plan+Task",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": [
              "VAR DisplayValue =",
              "CALCULATE(",
              "    SUM('ROF OrderPlan'[OrderPlanValue]),",
              "    'ROF OrderPlan'[Plan] = \"M3-Plan + Task\"",
              ")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))   ",
              "    Return",
              "    Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "bd24deee-0914-4a6d-8394-f01f0fe9cec7"
          },
          {
            "name": "V/S M1 Plan Cum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DisplayValue =",
              "CALCULATE(",
              "    CALCULATE(",
              "        [Current Wk Forecast]-[M1 Order Plan+Task],",
              "        'ROF Forecast'[Clari/ROF]=\"ROF\"",
              "    ),",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))   ",
              "    Return",
              "    Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "45b04301-84ba-4a80-af75-6ebc2fa2caa6"
          },
          {
            "name": "V/S M2 Plan Cum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DisplayValue = IF([M2 Order Plan+Task]=0,0,",
              "CALCULATE(",
              "    CALCULATE(",
              "        [Current Wk Forecast]-[M2 Order Plan+Task],",
              "    'ROF Forecast'[Clari/ROF]=\"ROF\"",
              "    ),",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              "))",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\"))) ",
              "    Return",
              "    Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "b2a69c65-f7c5-4cc1-a3fa-ea4489e545ea"
          },
          {
            "name": "V/S M3 Plan Cum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              " VAR DisplayValue = IF([M3 Order Plan+Task]=0,0,",
              "CALCULATE(",
              "    CALCULATE(",
              "        [Current Wk Forecast]-[M3 Order Plan+Task],",
              "    'ROF Forecast'[Clari/ROF]=\"ROF\"",
              "    ),",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              "))",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\"))) ",
              "    Return",
              "    Result",
              " ",
              " ",
              " ",
              " ",
              " ",
              " ",
              " ",
              " /*",
              " Var TaskOption = BLANK()  Var Monthvalue = BLANK()",
              "vAR Displayvalue = CALCULATE( If([M3 Order Plan+Task] =0 , 0,",
              "    CALCULATE(",
              "        [Forecast Value]-[M3 Order Plan+Task],",
              "        RowWkSorting[SortOrder] = 13",
              "    )),",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\"))) ",
              "Return ",
              " IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "            IF(",
              "                TaskOption ,",
              "                MonthValue,",
              "                MonthValue",
              "            ),",
              "            Result",
              "        ),",
              "        Result",
              "    )*/",
              "   \t/*",
              "Var TaskOption = BLANK()  Var Monthvalue = BLANK()",
              "vAR Displayvalue = CALCULATE( If([M3 Order Plan+Task] =0 , 0,",
              "    CALCULATE(",
              "        [Forecast Value]-[M3 Order Plan+Task],",
              "        RowWkSorting[SortOrder] = 14",
              "    )),",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\"))) ",
              "Return ",
              " IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "            IF(",
              "                TaskOption ,",
              "                MonthValue,",
              "                MonthValue",
              "            ),",
              "            Result",
              "        ),",
              "        Result",
              "    )",
              "   \t",
              "    */",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "8c926efb-337a-467d-a547-60c031713a13"
          },
          {
            "name": "QTD v/s Plan",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR DisplayValue =",
              "[Orders] - [M1_M2_M3 MIX]",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "3963c1d8-7a7b-410b-b310-be02e7e860c7"
          },
          {
            "name": "Blank",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "lineageTag": "0b633f85-032b-42f7-807e-964f18bf4d8f"
          },
          {
            "name": "Won",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Pipeline Measures",
            "expression": [
              "VAR DisplayValue =",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('Pipeline'[Revenue]),",
              "        KEEPFILTERS(Pipeline[ForecastCategory] = \"Won\")",
              "    ), ",
              "    10^6",
              ")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\"))) ",
              "    Return",
              "    Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "55cd5206-aa5f-4789-8290-80b1ef0c1047"
          },
          {
            "name": "Total Funnel",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Pipeline Measures",
            "expression": [
              "VAR DisplayValue =",
              "",
              "    [Total Revenue]",
              "",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "",
              "Return",
              "Result",
              "",
              "",
              "--[Won] + [Commit] + [Upside] + [Late Stage (SS 4-5)] + [Early Stage (SS 1-3)]"
            ],
            "formatString": "#,0.0",
            "lineageTag": "21d78030-0fe8-4931-99cc-2477f2655fe0"
          },
          {
            "name": "Cum M1_M2_M3",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [M1_M2_M3 MIX],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "60a7f3d4-c3c0-4595-b1f7-ca331f645428"
          },
          {
            "name": "Total ROF Pipeline Detailed",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CALCULATE(SUM('ROF Pipeline'[Value]),ALL('Prod Master'))",
              "",
              "--DIVIDE(SUM('ROF Pipeline'[Value]),10^6)",
              " ",
              " --CALCULATE(SUM('ROF Pipeline'[Value]),ALL('Prod Master'))",
              ""
            ],
            "lineageTag": "95720c01-f8ac-4e42-b27a-451bcd4c1f98"
          },
          {
            "name": "Forecast Value 1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(SUM('ROF Forecast'[Value]),FILTER('ROF Forecast','ROF Forecast'[WeekNo]=\"W13 + 1\"))"
            ],
            "lineageTag": "0250b807-5493-49a0-8af5-da13fb6dade0"
          },
          {
            "name": "Curr Week Single Value",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR InflightWeekNo = MAX('rpt dim_current_date_rof'[fiscal_week]) ",
              "VAR InflightWeekForecast=",
              "        CALCULATE(",
              "             [Forecast Value],",
              "                 RowWkSorting[SortOrder] = InflightWeekNo -1,",
              "                 ColWkSorting[SortOrder] = InflightWeekNo,",
              "                'ROF Forecast'[Clari/ROF]=\"ROF\"",
              "        )",
              "VAR Displayvalue = InflightWeekForecast",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",CONVERT(Displayvalue,INTEGER)))",
              "",
              "RETURN Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "29b3ceef-da08-4dc6-ae81-fc69d1205ce5"
          },
          {
            "name": "WTD Orders",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR InflightWeek = [Inflight Wk]",
              "VAR CumCurrWk = ",
              "    CALCULATE(",
              "        SUM('Load Bookings'[Bookings]) / 10^6,",
              "        ColWkSorting[Weeks] = InflightWeek",
              "    )",
              "VAR CumLastWk = ",
              "    VAR LastWkValue = ",
              "        CALCULATE(",
              "            SELECTEDVALUE(ColWkSorting[SortOrder]) - 1,",
              "            ColWkSorting[Weeks] = InflightWeek",
              "        )",
              "    VAR BookingValue = ",
              "        CALCULATE(",
              "            SUM('Load Bookings'[Bookings]) / 10^6,",
              "            ColWkSorting[SortOrder] = LastWkValue",
              "        )",
              "    RETURN",
              "        BookingValue",
              "RETURN",
              "    CumCurrWk - CumLastWk"
            ],
            "formatString": "0.0",
            "lineageTag": "aee655dc-a25a-4a03-9be0-4122778aa164"
          },
          {
            "name": "Inflight Wk",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CONCATENATE(\"W\",(MAX('rpt dim_current_date_rof'[fiscal_week])))",
              "--CALCULATE(",
              " --   selectedvalue('ColWkSorting'[Weeks]),",
              " --   ColWkSorting[IsCurrentWeek] = \"TRUE\"",
              "--)",
              ""
            ],
            "lineageTag": "c708da0b-fc3d-488d-9c8e-060d1f2b8dd4"
          },
          {
            "name": "WTD/Day",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR DayToday = FORMAT(TODAY(), \"ddd\")",
              "VAR DaysPassed = ",
              "    CALCULATE(",
              "        SELECTEDVALUE( 'Days Table'[Number] ),",
              "        'Days Table'[Day] = DayToday",
              "    )",
              "    VAR DisplayValue = DIVIDE(",
              "        CALCULATE([WTD Orders]),",
              "        DaysPassed",
              "    )",
              "    VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "RETURN",
              "    Result",
              "",
              "/* VAR DisplayValue = DIVIDE(",
              "        CALCULATE([WTD Orders],USERELATIONSHIP('Prod Bridge'[ProductKey],'Load Bookings'[ProductKey]),USERELATIONSHIP('Geo Bridge'[GeoKey],'Load Bookings'[GeoKey]),'Load Bookings'[FinancialOrderFlag]=\"Y\"),",
              "        DaysPassed",
              "        */"
            ],
            "formatString": "0.0",
            "lineageTag": "cd45803c-5a93-43e2-8785-33a58c9d31b0"
          },
          {
            "name": "WTDToGo/Day",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DayToday = FORMAT(TODAY(), \"ddd\")",
              "VAR DaystoGo= ",
              "    CALCULATE(",
              "        SELECTEDVALUE( 'Days Table'[To Go] ),",
              "        'Days Table'[Day] = DayToday",
              "    )",
              "    VAR DisplayValue = DIVIDE(",
              "   [Delta] * - 1,",
              "   DaystoGo",
              ")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "RETURN",
              "Result",
              "    "
            ],
            "formatString": "#,0.0",
            "lineageTag": "251442b9-72ad-44ba-894f-c43889cad8fa"
          },
          {
            "name": "Delta",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DisplayValue =",
              "[WTD Orders 1] - [Curr Week Single Value]",
              " Var Result = if([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "99e91ee9-a699-4309-9082-90e3fb97a250"
          },
          {
            "name": "vs Flash w/o BBL",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": "IF([Revenue Flash]=0,0, Calcs[Cum Actuals]-[Non Exec Cum])/[Revenue Flash]",
            "formatString": "0%;-0%;0%",
            "lineageTag": "f4c6e5a4-eb90-4688-b85f-33e603dce672"
          },
          {
            "name": "Plan + Task_M2",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR MonthValue =\"M2\"",
              "VAR ConcatMonthValue = MonthValue & \"-Plan + Task\"",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        SUM('ROF OrderPlan'[OrderPlanValue]), FILTER('ROF OrderPlan', 'ROF OrderPlan'[Plan]= ConcatMonthValue)",
              "       /* KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)*/",
              "    )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))   ",
              "RETURN",
              "IF(",
              "    ISINSCOPE(ColWkSorting[Weeks]),",
              "    IF(",
              "        SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "      LEFT(ConcatMonthValue,2),IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\"},BLANK(),",
              "      --LEFT(ConcatMonthValue,2),IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\",\"W2\"},BLANK(),",
              "            Result)",
              "        ",
              "    ),",
              "    Result",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "4a57ede4-c448-431e-bf92-f147c72f2655"
          },
          {
            "name": "Plan + Task_M3",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR MonthValue =\"M3\"",
              "VAR ConcatMonthValue = MonthValue & \"-Plan + Task\"",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        SUM('ROF OrderPlan'[OrderPlanValue]), FILTER('ROF OrderPlan','ROF OrderPlan'[Plan]=ConcatMonthValue)",
              "        /*KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)*/",
              "    )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(DisplayValue,\"0\")))   ",
              "RETURN",
              "IF(",
              "    ISINSCOPE(ColWkSorting[Weeks]),",
              "    IF(",
              "        SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "      LEFT(ConcatMonthValue,2),IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\"},BLANK(),",
              "      --LEFT(ConcatMonthValue,2),IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\",\"W2\"},BLANK(),",
              "            Result)",
              "        ",
              "    ),",
              "    Result",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "3f1013c9-8c2f-4049-abdc-75ce0dbc05e3"
          },
          {
            "name": "M2 EOP Value",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": [
              "",
              "VAR CurrentMonth = \"M2\"",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        SUM(EOP[EOPValue]),FILTER(EOP,EOP[MonthPlan]=CurrentMonth)",
              "        /*KEEPFILTERS(EOP[MonthPlan] = CurrentMonth*/",
              "    )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),BLANK(),DisplayValue),\"#,0\")))   ",
              "    RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "             CurrentMonth, IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\"},BLANK(),",
              "             --CurrentMonth, IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\",\"W2\"},BLANK(),",
              "            Result)",
              "        ),",
              "      Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "lineageTag": "6359fa17-d42c-46d4-9b23-cfde5301df04"
          },
          {
            "name": "M3 EOP Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": [
              "",
              "VAR CurrentMonth = \"M3\"",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        SUM(EOP[EOPValue]),FILTER(EOP,EOP[MonthPlan]=CurrentMonth)",
              "        /*KEEPFILTERS(EOP[MonthPlan] = CurrentMonth*/",
              "    )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))  ",
              "    RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "             CurrentMonth, IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\"},BLANK(),",
              "             --CurrentMonth, IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\",\"W2\"},BLANK(),",
              "            Result)",
              "        ),",
              "      Result",
              "    )"
            ],
            "lineageTag": "1551d637-2e7d-48b4-b712-a5ba57099738"
          },
          {
            "name": "vs Plan_M2",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "",
              "VAR MonthValue = \"M2\"",
              "VAR TaskOption = SELECTEDVALUE('Task Option'[Value])",
              "VAR ConcatMonthValue = ",
              "    IF(",
              "        TaskOption = \"W Task\",",
              "        MonthValue & \"-Plan + Task\",",
              "        MonthValue & \"-Plan\"",
              "    )",
              "VAR MonthPlanTask = ",
              "    CALCULATE(",
              "        SUM('ROF OrderPlan'[OrderPlanValue]),",
              "        KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)",
              "    )",
              "VAR DisplayValue = IF([Plan + Task_M2]=0,0, [Current Wk Forecast] - MonthPlanTask)",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "            IF(",
              "                TaskOption = \"W Task\",",
              "                MonthValue,",
              "                MonthValue",
              "            ),",
              "            Result",
              "        ),",
              "        Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "lineageTag": "84069584-d9d0-49b1-97fa-11fe0af9498f"
          },
          {
            "name": "vs Plan Cum_M1",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "",
              "VAR MonthValue = \"M1\"",
              "VAR TaskOption = SELECTEDVALUE('Task Option'[Value])",
              "VAR ConcatMonthValue = ",
              "    IF(",
              "        TaskOption = \"W Task\",",
              "        MonthValue & \"-Plan + Task\",",
              "        MonthValue & \"-Plan\"",
              "    )",
              "VAR MonthPlanTask = ",
              "    CALCULATE(",
              "        SUM('ROF OrderPlan'[OrderPlanValue]),",
              "        KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)",
              "    )",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        [Current Wk Forecast] ",
              "        - ",
              "        CALCULATE(",
              "            SUM('ROF OrderPlan'[OrderPlanValue]),",
              "            KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)",
              "        ),",
              "        FILTER(",
              "            ALL(ColWkSorting),",
              "            ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "        )",
              "    )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))    ",
              "RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "            IF(",
              "                TaskOption = \"W Task\",",
              "                MonthValue,",
              "                MonthValue",
              "            ),",
              "        Result",
              "        ),",
              "        Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "lineageTag": "3987e854-0af9-4d19-92dd-c4bfe83caeb2"
          },
          {
            "name": "vs Plan Cum_M2",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "",
              "VAR MonthValue = \"M2\"",
              "VAR TaskOption = SELECTEDVALUE('Task Option'[Value])",
              "VAR ConcatMonthValue = ",
              "    IF(",
              "        TaskOption = \"W Task\",",
              "        MonthValue & \"-Plan + Task\",",
              "        MonthValue & \"-Plan\"",
              "    )",
              "VAR MonthPlanTask = ",
              "    CALCULATE(",
              "        SUM('ROF OrderPlan'[OrderPlanValue]),",
              "        KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)",
              "    )",
              "VAR DisplayValue = IF([Plan + Task_M2]=0,0,",
              "    CALCULATE(",
              "        [Current Wk Forecast] ",
              "        - ",
              "        CALCULATE(",
              "            SUM('ROF OrderPlan'[OrderPlanValue]),",
              "            KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)",
              "        ),",
              "        FILTER(",
              "            ALL(ColWkSorting),",
              "            ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "        )",
              "    ))",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "            IF(",
              "                TaskOption = \"W Task\",",
              "                MonthValue ,",
              "                MonthValue",
              "            ),",
              "        Result",
              "        ),",
              "        Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "lineageTag": "c6171391-f1af-488c-86e4-2736e1afe49d"
          },
          {
            "name": "vs Plan_M3",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "",
              "VAR MonthValue = \"M3\"",
              "VAR TaskOption = SELECTEDVALUE('Task Option'[Value])",
              "VAR ConcatMonthValue = ",
              "    IF(",
              "        TaskOption = \"W Task\",",
              "        MonthValue & \"-Plan + Task\",",
              "        MonthValue & \"-Plan\"",
              "    )",
              "VAR MonthPlanTask = ",
              "    CALCULATE(",
              "        SUM('ROF OrderPlan'[OrderPlanValue]),",
              "        KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)",
              "    )",
              "VAR DisplayValue = IF([Plan + Task_M3]=0,0, [Current Wk Forecast] - MonthPlanTask)",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = \"W10\",0,",
              "            IF(SELECTEDVALUE(ColWkSorting[Weeks]) = Blank(),  MonthValue,Result",
              "            )",
              "        ),",
              "        Result",
              "    )"
            ],
            "formatString": "0.0",
            "lineageTag": "64192f3d-cb04-4521-8c0d-877e06542593"
          },
          {
            "name": "vs Plan Cum_M3",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "",
              "VAR MonthValue = \"M3\"",
              "VAR TaskOption = SELECTEDVALUE('Task Option'[Value])",
              "VAR ConcatMonthValue = ",
              "    IF(",
              "        TaskOption = \"W Task\",",
              "        MonthValue & \"-Plan + Task\",",
              "        MonthValue & \"-Plan\"",
              "    )",
              "VAR MonthPlanTask = ",
              "    CALCULATE(",
              "        SUM('ROF OrderPlan'[OrderPlanValue]),",
              "        KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)",
              "    )",
              "VAR DisplayValue = IF([Plan + Task_M3]=0,0,",
              "    CALCULATE(",
              "        [Current Wk Forecast] ",
              "        - ",
              "        CALCULATE(",
              "            SUM('ROF OrderPlan'[OrderPlanValue]),",
              "            KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)",
              "        ),",
              "        FILTER(",
              "            ALL(ColWkSorting),",
              "            ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "        )",
              "    ))",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = \"W10\",0,",
              "            IF(SELECTEDVALUE(ColWkSorting[Weeks]) = Blank(),  MonthValue,Result",
              "            )",
              "        ),",
              "        Result",
              "    )",
              "",
              "",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "a23bffe1-17ee-4bbe-b599-127fbafd2a80"
          },
          {
            "name": "Cum Actuals",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "[Forecast Value],",
              "FILTER(",
              "ALL(ColWkSorting),",
              "ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              ")",
              ",",
              "KEEPFILTERS(RowWkSorting[Week] = \"W13 + 1\")",
              ")"
            ],
            "lineageTag": "c36b199c-3762-45e1-8f59-9773c897862a"
          },
          {
            "name": "EOP Value",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "Var M1=[M1 EOP Value]",
              "Var M2= If([M2 EOP Value]=BLANK(),M1,[M2 EOP Value])",
              "Var M3=If([M3 EOP Value]=BLANK(),M2,[M3 EOP Value])",
              "Return",
              "IF(\"W\"& MAX('rpt dim_current_date_rof'[fiscal_week]) IN {\"W2\",\"W3\",\"W4\",\"W5\"},M1,",
              "IF(\"W\"& MAX('rpt dim_current_date_rof'[fiscal_week]) IN {\"W6\",\"W7\",\"W8\",\"W9\"},M2,M3))",
              "--IF(\"W\"& MAX('rpt dim_current_date'[fiscal_week]) IN {\"W11\",\"W12\",\"W13\",\"W13-1\"},M3)))"
            ],
            "formatString": "#,0.0",
            "lineageTag": "9ce76a86-346e-4bf0-b09a-c728be7509fa"
          },
          {
            "name": "vs Plan_M3_Test",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR MonthValue = \"M3\"",
              "VAR TaskOption = SELECTEDVALUE('Task Option'[Value])",
              "VAR ConcatMonthValue = ",
              "    IF(",
              "        TaskOption = \"W Task\",",
              "        MonthValue & \"-Plan + Task\",",
              "        MonthValue & \"-Plan\"",
              "    )",
              "VAR MonthPlanTask = ",
              "    CALCULATE(",
              "        SUM('ROF OrderPlan'[OrderPlanValue]),",
              "        KEEPFILTERS('ROF OrderPlan'[Plan] = ConcatMonthValue)",
              "    )",
              "VAR DisplayValue = IF((MonthPlanTask= 0 ) || (MonthPlanTask= BLANK())  , 0, [Current Wk Forecast]  - MonthPlanTask)",
              "RETURN MonthPlanTask",
              "  /* IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "            IF(",
              "                TaskOption = \"W Task\",",
              "                MonthValue,",
              "                MonthValue",
              "            ),",
              "            DisplayValue",
              "        ),",
              "        DisplayValue",
              "    ) */",
              "   "
            ],
            "lineageTag": "28a52aea-c5c4-485b-bd89-f2bdd79e427a"
          },
          {
            "name": "Early Stage (SS 1-3)",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Pipeline Measures",
            "expression": [
              "VAR DisplayValue =",
              "    CALCULATE(",
              "        [Total Revenue],",
              "        KEEPFILTERS( 'Pipeline'[ForecastCategory] = \"Pipeline ES\" )",
              "    )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "28c5641a-4e55-42c3-8ed0-40f4ed5327ea"
          },
          {
            "name": "Deal Based Indirect",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Clari Detailed Measures",
            "expression": [
              "",
              " VAR DisplayValue = CALCULATE(Calcs[Total Judgement],ROF_Clari_Final_Split[ForecastEntryType]=\"Deal Based Indirect\")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result",
              "   "
            ],
            "formatString": "#,0.0",
            "lineageTag": "e0abb187-4976-4370-817b-65193f630aa3"
          },
          {
            "name": "Clari Forecast Value",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    SUMMARIZE(",
              "        'ROF_Clari_Final_Split',",
              "        'ROF_Clari_Final_Split'[GeoKey],",
              "        'ROF_Clari_Final_Split'[ProductKey],",
              "        ColWkSorting[SortOrder],",
              "        ColWkSorting[Weeks],",
              "        RowWkSorting[Week],",
              "        RowWkSorting[SortOrder],",
              "        'ROF_Clari_Final_Split'[Value]",
              "    ),",
              "    'ROF_Clari_Final_Split'[Value]",
              ")",
              "",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "bb2c2e5e-8430-4d00-8ebe-ae06c734da17"
          },
          {
            "name": "Total Judgement",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Clari Detailed Measures",
            "expression": [
              "",
              "VAR DisplayValue = CALCULATE(Calcs[Clari Forecast Value],RowWkSorting[IsCurrentWeek]=\"TRUE\")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "f52833e8-9d18-400a-836f-81e4e167359f"
          },
          {
            "name": "Deal Based Direct",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Clari Detailed Measures",
            "expression": [
              "",
              "   VAR DisplayValue =  CALCULATE(Calcs[Total Judgement],ROF_Clari_Final_Split[ForecastEntryType]=\"Deal Based Direct\")",
              "    VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result",
              "",
              "/*VAR Weekdisplayed = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(RowWkSorting[Week]),",
              "        RowWkSorting[IsCurrentWeek] = \"TRUE\")",
              "VAR Valuedisplayed =*/",
              "/*RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]), ",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(), ",
              "            Weekdisplayed, ",
              "            Valuedisplayed",
              "        ),",
              "        Valuedisplayed",
              "    )*/"
            ],
            "formatString": "#,0.0",
            "lineageTag": "bb510e54-a3ea-4231-a127-84fcd6ed4c57"
          },
          {
            "name": "Deal Based",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Clari Detailed Measures",
            "expression": [
              "VAR DisplayValue =  CALCULATE(Calcs[Total Judgement],ROF_Clari_Final_Split[ForecastEntryType] in {\"Deal Based Direct\",\"Deal Based Indirect\"})",
              "    VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result",
              "",
              "",
              "",
              "--[Deal Based Direct]+[Deal Based Indirect]",
              "  "
            ],
            "formatString": "#,0.0",
            "lineageTag": "79299663-9f00-4613-bf3a-a1e24c0c96de"
          },
          {
            "name": "Judge Down (Non Deal)",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Clari Detailed Measures",
            "expression": [
              "",
              "VAR DisplayValue = CALCULATE(Calcs[Total Judgement],ROF_Clari_Final_Split[ForecastEntryType]=\"Judge Down\")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "2569e773-b305-47fa-893c-9a4cc02f989f"
          },
          {
            "name": "Run Rate (Non Deal)",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Clari Detailed Measures",
            "expression": [
              "",
              "  VAR DisplayValue = CALCULATE(Calcs[Total Judgement],ROF_Clari_Final_Split[ForecastEntryType]=\"Run Rate\")",
              "  VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result",
              " "
            ],
            "formatString": "#,0.0",
            "lineageTag": "d700bb6e-e50c-456d-ac2a-da9fd685b5b7"
          },
          {
            "name": "Stretch (Non Deal)",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Clari Detailed Measures",
            "expression": [
              "",
              "VAR DisplayValue = CALCULATE(Calcs[Total Judgement],ROF_Clari_Final_Split[ForecastEntryType]=\"Stretch\")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "9756f7a1-436a-4a3e-92d1-2dea18912706"
          },
          {
            "name": "Task (Non Deal)",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Clari Detailed Measures",
            "expression": [
              "",
              "VAR DisplayValue = CALCULATE(Calcs[Total Judgement],ROF_Clari_Final_Split[ForecastEntryType]=\"Task\")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "69b8cd6a-c26b-4296-a633-8280f8879820"
          },
          {
            "name": "Non Deal Based",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Clari Detailed Measures",
            "expression": [
              "VAR DisplayValue = CALCULATE(Calcs[Total Judgement],ROF_Clari_Final_Split[ForecastEntryType] in {\"Run Rate\",\"Stretch\",\"Task\",\"Judge Down\"})",
              "  VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result",
              "",
              " --[Judge Down (Non Deal)]+[Run Rate (Non Deal)]+[Stretch (Non Deal)]+[Task (Non Deal)]",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "52a14dbd-f342-42c2-8f27-b8b6d8d69bd9"
          },
          {
            "name": "Curr Wk Forecast ROF",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Actuals & Forecast Measures",
            "expression": [
              "",
              "VAR DisplayValue = CALCULATE([Current Wk Forecast],'ROF Forecast'[Clari/ROF]=\"ROF\")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "b4041641-ec76-46aa-abfa-e9120eb57db9"
          },
          {
            "name": "SC_Prior WK Fcst",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR CurrWeek = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(RowWkSorting[SortOrder]) ,",
              "        RowWkSorting[IsCurrentWeek] = \"TRUE\"",
              "    )",
              "VAR PrevWeekDisplayed = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(RowWkSorting[Week]),",
              "        RowWkSorting[SortOrder] = CurrWeek - 1",
              "    )",
              "VAR ValueDisplayed = ",
              "    CALCULATE(",
              "        [Forecast Value],",
              "        RowWkSorting[SortOrder] = CurrWeek - 1",
              "    )",
              "RETURN",
              "IF(",
              "    ISINSCOPE(ColWkSorting[Weeks]),",
              "    IF(",
              "        SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "        PrevWeekDisplayed,",
              "        ValueDisplayed",
              "    ),",
              "    ValueDisplayed",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "623c363c-4780-4567-bf54-9d8de2b8e701"
          },
          {
            "name": "SC_ Cumu Pre WK Forecast",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [SC_Prior WK Fcst],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "4e12ac55-d6b3-4e12-82e0-35f8d7f0f713"
          },
          {
            "name": "SC_Cumu VS Prior Wk Fcst",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              " VAR DisplayValue = CALCULATE(",
              "           [vsPriorwkforecasttable],",
              "            ",
              "            FILTER(",
              "                ALL(ColWkSorting),",
              "                ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "            )",
              "        )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(if(DisplayValue=BLANK(),0,DisplayValue),\"0\"))) ",
              "",
              "    Return",
              "    Result",
              "",
              "",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "04d562d5-e1f3-4f9a-a226-ee6c8ce48bb8"
          },
          {
            "name": "Actuals vs PW",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR DisplayValue =",
              "[VS Prior Wk Fcst_New]",
              "Var Result = if([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result",
              "",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "5e098977-26a4-4950-a82c-bce5ff0c4ca7"
          },
          {
            "name": "Delta to Flash",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR DisplayValue = [EBBL+CumAct-CumNonExeOrders]-[Revenue Flash]",
              "Var Result = if([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "f386f2ac-b3ec-4cb6-b0b2-9b5698f55154"
          },
          {
            "name": "% of Flash",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([EBBL+CumAct-CumNonExeOrders],[Revenue Flash])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "47d026fa-0a9f-46a7-97f1-2d72acf3c2a3"
          },
          {
            "name": "Current Wk Forecast_New",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Forecast Value],",
              "    KEEPFILTERS(ColWkSorting[IsCurrentWeek] = \"TRUE\")",
              ")"
            ],
            "lineageTag": "64d34c74-b228-49a8-ad03-27eb052c69b9"
          },
          {
            "name": "VS Prior Wk Fcst_New",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "VAR OpenCloseStatus = SELECTEDVALUE(ColWkSorting[Open/Close])",
              "VAR wkday = SELECTEDVALUE('rpt dim_current_date_rof'[weekday])",
              "VAR RowCurrWeek =",
              "    CALCULATE(",
              "    SELECTEDVALUE(RowWkSorting[SortOrder]) ,",
              "    RowWkSorting[IsCurrentWeek] = \"TRUE\"",
              "    )",
              "VAR ColCurrWeek = SELECTEDVALUE(ColWkSorting[SortOrder])",
              "VAR currweekvalue =",
              "        CALCULATE(",
              "        [Forecast Value],",
              "    RowWkSorting[SortOrder] =RowCurrWeek",
              "    )",
              "VAR Days = IF(wkday<=4 && wkday>=2,1,2)",
              "--If( (WEEKDAY(NOW(),1)) <= 4 && (WEEKDAY(NOW(),1) >=2), 1, 2)",
              "",
              "",
              "Var RowcurrWk2= CALCULATE(",
              "        [Forecast Value],",
              "    RowWkSorting[SortOrder] =1)",
              "",
              "",
              "VAR Preweekvalue =",
              "if ( ColCurrWeek = 2,[Plan + Task_M1],",
              "    if (OpenCloseStatus=\"Open\", ",
              "       if(RowCurrWeek=2 ,[Plan + Task_M1],",
              "       if(RowCurrWeek=3 && Days=2,[Plan + Task_M1],",
              "        CALCULATE(",
              "            [Forecast Value],",
              "            RowWkSorting[SortOrder] =RowCurrWeek-Days--,ColWkSorting[IsCurrentWeek]=\"TRUE\"",
              "            ))),",
              "        CALCULATE(",
              "            [Forecast Value],",
              "            RowWkSorting[SortOrder] =ColCurrWeek-1",
              "            )))",
              "",
              "VAR Total =  if(RowCurrWeek=2 ,[Plan + Task_M1],",
              "       if(RowCurrWeek=3 && Days=2,[Plan + Task_M1],CALCULATE( [Forecast Value],RowWkSorting[SortOrder] =RowCurrWeek-Days)))",
              "",
              "",
              "RETURN",
              "",
              "if (ISINSCOPE(ColWkSorting[Weeks]),",
              "    currweekvalue-Preweekvalue,",
              "    --currweekvalue-[Plan + Task_M1]",
              "   currweekvalue-Total",
              ")",
              "",
              "/*",
              "",
              "VAR OpenCloseStatus = SELECTEDVALUE(ColWkSorting[Open/Close])",
              "VAR wkday = SELECTEDVALUE('rpt dim_current_date_rof'[weekday])",
              "VAR RowCurrWeek =",
              "    CALCULATE(",
              "    SELECTEDVALUE(RowWkSorting[SortOrder]) ,",
              "    RowWkSorting[IsCurrentWeek] = \"TRUE\"",
              "    )",
              "VAR ColCurrWeek = SELECTEDVALUE(ColWkSorting[SortOrder])",
              "VAR currweekvalue =",
              "        CALCULATE(",
              "        [Forecast Value],",
              "    RowWkSorting[SortOrder] =RowCurrWeek",
              "    )",
              "VAR Days = IF(wkday<=4 && wkday>=2,1,2)",
              "--If( (WEEKDAY(NOW(),1)) <= 4 && (WEEKDAY(NOW(),1) >=2), 1, 2)",
              "",
              "",
              "Var RowcurrWk2= CALCULATE(",
              "        [Forecast Value],",
              "    RowWkSorting[SortOrder] =2)",
              "",
              "",
              "VAR Preweekvalue =",
              "if ( ColCurrWeek = 3,[Plan + Task_M1],",
              "    if (OpenCloseStatus=\"Open\", ",
              "       if(RowCurrWeek=3 ,[Plan + Task_M1],",
              "       if(RowCurrWeek=4 && Days=2,[Plan + Task_M1],",
              "        CALCULATE(",
              "            [Forecast Value],",
              "            RowWkSorting[SortOrder] =RowCurrWeek-Days--,ColWkSorting[IsCurrentWeek]=\"TRUE\"",
              "            ))),",
              "        CALCULATE(",
              "            [Forecast Value],",
              "            RowWkSorting[SortOrder] =ColCurrWeek-1",
              "            )))",
              "",
              "VAR Total =  if(RowCurrWeek=3 ,[Plan + Task_M1],",
              "       if(RowCurrWeek=4 && Days=2,[Plan + Task_M1],CALCULATE( [Forecast Value],RowWkSorting[SortOrder] =RowCurrWeek-Days)))",
              "",
              "",
              "RETURN",
              "",
              "if (ISINSCOPE(ColWkSorting[Weeks]),",
              "    currweekvalue-Preweekvalue,",
              "    --currweekvalue-[Plan + Task_M1]",
              "   currweekvalue-Total",
              ")",
              "*/"
            ],
            "lineageTag": "b9afd247-5a6f-4224-ab3a-5bc666524843"
          },
          {
            "name": "vsPriorwkforecasttable",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "sumx(ColWkSorting,[VS Prior Wk Fcst_New])",
            "lineageTag": "58ca6908-c57a-402f-8a77-198dedf859e7"
          },
          {
            "name": "Check Cal",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "",
              "MAX(Metrics[Forecast vs Flash])=\"Actuals vs PW\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[Actuals vs PW],",
              "max(Metrics[Forecast vs Flash])=\"Actuals vs PW\" && MAX(ColWkSorting[WKDyn]) <>\"CurrWeek-1\",BLANK(),",
              "MAX(Metrics[Forecast vs Flash])=\"Actuals vs PW (Cum)\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[SC_Cumu VS Prior Wk Fcst],",
              "max(Metrics[Forecast vs Flash])=\"Actuals vs PW (Cum)\" && MAX(ColWkSorting[WKDyn]) <>\"CurrWeek-1\",BLANK(),",
              "MAX(Metrics[Forecast vs Flash])=\"Delta to Flash\"&&  MAX(ColWkSorting[Weeks]) in {\"W9\",\"W10\",\"W11\"},[Delta to Flash],",
              "MAX(Metrics[Forecast vs Flash])=\"% of Flash\"&& MAX(ColWkSorting[Weeks]) in {\"W9\",\"W10\",\"W11\"},FORMAT([% of Flash],\"0%\"),",
              "MAX(Metrics[Forecast vs Flash])=\"Delta to Flash\"||MAX(Metrics[Forecast vs Flash])=\"% of Flash\",BLANK())",
              "",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "88b012b4-2e31-437f-8c7f-4a6c3774d222"
          },
          {
            "name": "CF for Actuals VS PW",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR VS = ",
              "if(ISINSCOPE(Metrics[Forecast vs Flash]) && MAX(Metrics[Forecast vs Flash])=\"Actuals vs PW\" && CONVERT([Actuals vs PW],DOUBLE)<0,1,0)",
              "",
              "Return",
              "VS",
              "--IF(VS<0,\"#C00000\")"
            ],
            "formatString": "0",
            "lineageTag": "5ee3b498-4370-4ae3-bdfb-af02e27afbf4"
          },
          {
            "name": "VS Prior Wk Fcst_New_Actuals vs PW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "VAR OpenCloseStatus = SELECTEDVALUE(ColWkSorting[Open/Close])",
              "",
              "VAR RowCurrWeek =",
              "                    CALCULATE(",
              "                    SELECTEDVALUE(RowWkSorting[SortOrder]) ,",
              "                    RowWkSorting[IsCurrentWeek] = \"TRUE\"",
              "                    )",
              "",
              "VAR ColCurrWeek = SELECTEDVALUE(ColWkSorting[SortOrder])",
              "",
              "VAR currweekvalue =",
              "                    CALCULATE(",
              "                    [Forecast Value],",
              "                    RowWkSorting[SortOrder] =RowCurrWeek",
              "                    )",
              "",
              "VAR Days =",
              "                    If( (WEEKDAY(NOW(),14)) >= 1 && (WEEKDAY(NOW(),14) <=7), 1, 0",
              "                    )",
              "",
              "VAR Preweekvalue =",
              "                if ( ColCurrWeek = 2,[Plan + Task_M1],",
              "                    if (OpenCloseStatus=\"Open\",",
              "                            CALCULATE(",
              "                            [Forecast Value],",
              "                            RowWkSorting[SortOrder] =RowCurrWeek-Days--,ColWkSorting[IsCurrentWeek]=\"TRUE\"",
              "                     ),CALCULATE(",
              "                             [Forecast Value],",
              "                            RowWkSorting[SortOrder] =ColCurrWeek-1",
              "                    )))",
              "",
              "RETURN",
              "",
              "if (ISINSCOPE(ColWkSorting[Weeks]),",
              "    currweekvalue-Preweekvalue,currweekvalue-CALCULATE( [Forecast Value],",
              "    RowWkSorting[SortOrder] =RowCurrWeek-Days",
              "",
              "))",
              "/*",
              "",
              "VAR OpenCloseStatus = SELECTEDVALUE(ColWkSorting[Open/Close])",
              "",
              "VAR RowCurrWeek =",
              "",
              "CALCULATE(",
              "",
              "SELECTEDVALUE(RowWkSorting[SortOrder]) ,",
              "",
              "RowWkSorting[IsCurrentWeek] = \"TRUE\"",
              "",
              ")",
              "",
              "VAR ColCurrWeek = SELECTEDVALUE(ColWkSorting[SortOrder])",
              "",
              "",
              "",
              "VAR currweekvalue =",
              "",
              "CALCULATE(",
              "",
              "[Forecast Value],",
              "",
              "RowWkSorting[SortOrder] =RowCurrWeek",
              "",
              ")",
              "",
              "VAR Days =",
              "",
              "If( (WEEKDAY(NOW(),14)) >= 1 && (WEEKDAY(NOW(),14) <=7), 1, 0",
              "",
              ")",
              "",
              "VAR Preweekvalue =",
              "",
              "if ( ColCurrWeek = 3,[Plan + Task_M1],",
              "",
              "if (OpenCloseStatus=\"Open\",",
              "",
              "CALCULATE(",
              "",
              "[Forecast Value],",
              "",
              "RowWkSorting[SortOrder] =RowCurrWeek-Days--,ColWkSorting[IsCurrentWeek]=\"TRUE\"",
              "",
              "),CALCULATE(",
              "",
              "[Forecast Value],",
              "",
              "RowWkSorting[SortOrder] =ColCurrWeek-1",
              "",
              ")))",
              "",
              "RETURN",
              "",
              "if (ISINSCOPE(ColWkSorting[Weeks]),",
              "",
              "currweekvalue-Preweekvalue,currweekvalue-CALCULATE( [Forecast Value],",
              "",
              "RowWkSorting[SortOrder] =RowCurrWeek-Days",
              "",
              "))",
              "*/"
            ],
            "lineageTag": "a15e60e0-48f4-4277-908e-7a781eaad3d4"
          },
          {
            "name": "Compute",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(SUM('ROF Pipeline'[Value]),FILTER('Prod Master','Prod Master'[BU 1]=\"Compute\"))",
            "formatString": "#,0",
            "lineageTag": "87a9334b-e9fe-491c-973b-5a7bc9e01c1c"
          },
          {
            "name": "Edge",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(SUM('ROF Pipeline'[Value]),FILTER('Prod Master','Prod Master'[BU 2]=\"Edge\"))",
            "formatString": "#,0",
            "lineageTag": "20c82c7f-2eef-4207-8f1c-49179fdec271"
          },
          {
            "name": "HPC & AI",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(SUM('ROF Pipeline'[Value]),FILTER('Prod Master','Prod Master'[BU 1]=\"HPC & AI\"))",
            "formatString": "#,0",
            "lineageTag": "be2f0490-dbfe-498f-bee7-b713dc7ef38d"
          },
          {
            "name": "Storage",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(SUM('ROF Pipeline'[Value]),FILTER('Prod Master','Prod Master'[BU 1]=\"Storage\"))",
            "formatString": "#,0",
            "lineageTag": "6bf0d103-7db3-451e-b0ed-c97ca93ec90e"
          },
          {
            "name": "SC_Month Plans",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR MonSel = SELECTEDVALUE('Month Selection'[Month])",
              "VAR Result = ",
              "            SWITCH(TRUE(),",
              "            MonSel=\"M1\",[vs Plan_M1],",
              "            MonSel=\"M2\",[vs Plan_M2],",
              "            MonSel=\"M3\",[vs Plan_M3])",
              "",
              "Return",
              "Result",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "ba3a4587-87f8-4cd1-ab4d-617bb1f4eb54"
          },
          {
            "name": "SC_Cumu Month Plans",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [SC_Month Plans],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "a74c5f1c-e877-4267-b361-22130dfe8037"
          },
          {
            "name": "Current Wk Forecast Clari",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              " VAR DisplayValue = CALCULATE([Current Wk Forecast],'ROF Forecast'[Clari/ROF]=\"Unadjusted (Clari)\",'ROF Forecast'[Forecast Level]=SELECTEDVALUE(ROF_Clari_Final_Split[Forecast Level]))",
              " VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(DisplayValue,\"0\")))",
              "    Return",
              "    Result",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "b3d75000-f19e-4e6d-8043-199277d75e39"
          },
          {
            "name": "Orders Refresh Concat",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "    \"APJ: \" & CALCULATE(FORMAT(MAX(DataRefreshConfig[Refresh Date Copy]),\"mmmm dd,yyyy\"),DataRefreshConfig[DataSet]=\"QTD FinancialOrders\",DataRefreshConfig[DataSetGroup]=\"Except ROF\",DataRefreshConfig[Geo]=\"APJ\")",
              "&",
              "    \" |  EMEA: \"& CALCULATE(FORMAT(MAX(DataRefreshConfig[Refresh Date Copy]),\"mmmm dd,yyyy\"),DataRefreshConfig[DataSet]=\"QTD FinancialOrders\",DataRefreshConfig[DataSetGroup]=\"Except ROF\",DataRefreshConfig[Geo]=\"EMEA\")",
              "&",
              "    \" |  AMS: \" & CALCULATE(FORMAT(MAX(DataRefreshConfig[Refresh Date Copy]),\"mmmm dd,yyyy\"),DataRefreshConfig[DataSet]=\"QTD FinancialOrders\",DataRefreshConfig[DataSetGroup]=\"Except ROF\",DataRefreshConfig[Geo]=\"AMS\")"
            ],
            "lineageTag": "7f814a04-ca7a-48cd-a07f-e9f2800a07cf"
          },
          {
            "name": "DaysToGo",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DayToday = FORMAT(TODAY(), \"ddd\")",
              "VAR DaystoGo= ",
              "    CALCULATE(",
              "        SELECTEDVALUE( 'Days Table'[To Go] ),",
              "        'Days Table'[Day] = DayToday",
              "    )",
              "",
              "RETURN",
              "DaystoGo"
            ],
            "formatString": "0",
            "lineageTag": "94834335-cfac-4e92-b374-5455ef52d3df"
          },
          {
            "name": "DaysPassed",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR DayToday = FORMAT(TODAY(), \"ddd\")",
              "VAR DaysPassed = ",
              "    CALCULATE(",
              "        SELECTEDVALUE( 'Days Table'[Number] ),",
              "        'Days Table'[Day] = DayToday",
              "    )",
              "",
              "RETURN",
              "DaysPassed"
            ],
            "formatString": "0",
            "lineageTag": "3c5d6d64-60ee-419f-86e9-79761d4a6b67"
          },
          {
            "name": "vs Prior Wk Fcst (ROF)",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "VAR DisplayValue =",
              " CALCULATE(([VS Prior Wk Fcst_New]),KEEPFILTERS('ROF Forecast'[Clari/ROF]=\"ROF\"))",
              "VAR Result =",
              "       if( [Sel Decimal]=\"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "        if([Sel Decimal]=\"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "  Result",
              "",
              "",
              "",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "d23192a5-6708-49ad-931c-aa2fa3927171"
          },
          {
            "name": "Cum Order Plan value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [M1_M2_M3 MIX],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")",
              ""
            ],
            "lineageTag": "8ce7af53-839b-4324-8e18-b06c244bb7d1"
          },
          {
            "name": "Cum Forecast",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Current Wk Forecast],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")"
            ],
            "lineageTag": "b034438b-4600-4518-b95b-e73f360f3aee"
          },
          {
            "name": "vs Order Plan Cum",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "",
              "        VAR Num = [Cum Forecast]",
              "        VAR Den = [Cum Order Plan value]",
              "Return",
              "DIVIDE(Num,Den)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "01482ee2-0d7c-472c-b236-bea528d17ecd"
          },
          {
            "name": "Cum M1 Order Plan + Task",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    [M1 Order Plan+Task],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "f68c99f1-9e75-4d1d-989e-8fc76a9bd379"
          },
          {
            "name": "Cum M2 Order Plan + Task",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    [M2 Order Plan+Task],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "d4268226-1cb1-4538-a33d-81e5517b5d0c"
          },
          {
            "name": "Cum M3 Order Plan + Task",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    [M3 Order Plan+Task],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "ddb3557b-4225-47c1-ae12-827ee4873b6a"
          },
          {
            "name": "VS Prior Wk Fcst_New_Decimal",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR DisplayValue = [VS Prior Wk Fcst_New]",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "32593634-5a40-4f6a-8bc5-9187767fc095"
          },
          {
            "name": "Order 2",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR Weekdisplayed = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(RowWkSorting[Week]),",
              "        RowWkSorting[IsCurrentWeek] = \"TRUE\"",
              "    )",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        [Forecast Value],",
              "        KEEPFILTERS(RowWkSorting[IsCurrentWeek] = \"TRUE\"), ",
              "        KEEPFILTERS(ColWkSorting[Open/Close] = \"Close\"),",
              "        KEEPFILTERS('ROF Forecast'[Clari/ROF] = \"ROF\")",
              "",
              "    )",
              "  VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",CONVERT(FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\"),INTEGER)))",
              "RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]), ",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(), ",
              "            Weekdisplayed, ",
              "            Result",
              "        ),",
              "        Result",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "7abd0af4-48db-45e1-b83f-abf309bbefc7"
          },
          {
            "name": "M1_M2_M3 MIX 1",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR M1 = ",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W2\",\"W3\",\"W4\",\"W5\"}",
              "    )",
              "VAR M2 =  IF( [M2 Order Plan+Task]=0,",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W6\",\"W7\",\"W8\",\"W9\"}",
              "  ),CALCULATE(",
              "        [M2 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W6\",\"W7\",\"W8\",\"W9\"}))",
              "VAR M3 = IF([M3 Order Plan+Task]=0,",
              "            IF([M2 Order Plan+Task]=0,",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W10\",\"W11\",\"W12\",\"W13\"}),",
              "    ",
              "    CALCULATE(",
              "        [M2 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W10\",\"W11\",\"W12\",\"W13\"})),",
              "       ",
              "    CALCULATE(",
              "        [M3 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W10\",\"W11\",\"W12\",\"W13\"}",
              "    ))",
              "VAR DisplayValue =M1+M2+M3",
              "",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",CONVERT(FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\"),INTEGER)))",
              "RETURN",
              "Result",
              "    -- M1+M2+M3",
              "",
              "    /*AR M1 = ",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W3\",\"W4\",\"W5\",\"W6\"}",
              "    )",
              "VAR M2 =  IF( [M2 Order Plan+Task]=0,",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W7\",\"W8\",\"W9\",\"W10\"}",
              "  ),CALCULATE(",
              "        [M2 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W7\",\"W8\",\"W9\",\"W10\"}))",
              "VAR M3 = IF([M3 Order Plan+Task]=0,",
              "            IF([M2 Order Plan+Task]=0,",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W11\",\"W12\",\"W13\",\"W13-1\"}),",
              "    ",
              "    CALCULATE(",
              "        [M2 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W11\",\"W12\",\"W13\",\"W13-1\"})),",
              "       ",
              "    CALCULATE(",
              "        [M3 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W11\",\"W12\",\"W13\",\"W13-1\"}",
              "    ))",
              "VAR DisplayValue =M1+M2+M3",
              "",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",CONVERT(FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\"),INTEGER)))",
              "RETURN",
              "Result",
              "    -- M1+M2+M3",
              "*/",
              ""
            ],
            "formatString": "#,0.0",
            "lineageTag": "5cd573dc-f0de-47f5-a36b-47e13c843225"
          },
          {
            "name": "WTD Orders 1",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR DisplayValue = CALCULATE([WTD Orders])",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result",
              "-- VAR DisplayValue = CALCULATE([WTD Orders],USERELATIONSHIP('Prod Bridge'[ProductKey],'Load Bookings'[ProductKey]),USERELATIONSHIP('Geo Bridge'[GeoKey],'Load Bookings'[GeoKey]),'Load Bookings'[FinancialOrderFlag]=\"Y\")"
            ],
            "formatString": "0.0",
            "lineageTag": "8b99e6e4-9eab-4ab6-9440-c2bd0fe4b1c4"
          },
          {
            "name": "Hide Visual",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(SELECTEDVALUE('w / wo Decimal'[Decimal Pointer])=\"w decimal\",1,0)",
            "formatString": "0",
            "lineageTag": "8174b67a-50c7-4d51-bc82-a8221af3231a"
          },
          {
            "name": "WTD Orders 2",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR DisplayValue = CALCULATE([WTD Orders])",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",CONVERT(DisplayValue,INTEGER)))",
              "    Return",
              "    Result",
              "",
              "--VAR DisplayValue = CALCULATE([WTD Orders],USERELATIONSHIP('Prod Bridge'[ProductKey],'Load Bookings'[ProductKey]),USERELATIONSHIP('Geo Bridge'[GeoKey],'Load Bookings'[GeoKey]),'Load Bookings'[FinancialOrderFlag]=\"Y\")"
            ],
            "formatString": "0.0",
            "lineageTag": "cc022343-0ef9-4b79-8e80-10529c9da28b"
          },
          {
            "name": "Delta 1",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DisplayValue =",
              "[WTD Orders 1] - [Curr Week Single Value]",
              " VAR Result = SWITCH(TRUE(),",
              "        [Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    [Sel Decimal]= \"no decimal\",CONVERT(DisplayValue,INTEGER))",
              "    Return",
              "    Result"
            ],
            "formatString": "0.0",
            "lineageTag": "59e58193-c467-4012-8bf2-9b81ed76ca72"
          },
          {
            "name": "Curr Week Single Value 1",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR InflightWeekNo = MAX('rpt dim_current_date_rof'[fiscal_week]) ",
              "VAR InflightWeekForecast=",
              "        CALCULATE(",
              "             [Forecast Value],",
              "                 RowWkSorting[SortOrder] = InflightWeekNo -1,",
              "                 ColWkSorting[SortOrder] = InflightWeekNo,",
              "                'ROF Forecast'[Clari/ROF]=\"ROF\"",
              "        )",
              "VAR Displayvalue = InflightWeekForecast",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(Displayvalue=BLANK(),0,Displayvalue),\"#,0\")))",
              "",
              "RETURN Result"
            ],
            "formatString": "0.0",
            "lineageTag": "0153099a-9e01-47c9-8989-10a512a6d4d7"
          },
          {
            "name": "CF for QTD v/s Plan",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(CONVERT([QTD v/s Plan],DOUBLE)<0,1,0)",
            "formatString": "0",
            "lineageTag": "417eab52-f568-49cc-8c68-b2e33c0f3be7"
          },
          {
            "name": "Diff_fcst",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR CF = CALCULATE([Total Judgement],ROF_Clari_Final_Split[Forecast Level]=\"Country Forecast\")",
              "            VAR GF = CALCULATE([Total Judgement],ROF_Clari_Final_Split[Forecast Level]=\"GEO Forecast\")",
              "            VAR DisplayValue =  if(NOT(ISINSCOPE('Geo Master'[SubRegion1])&&ISINSCOPE(ROF_Clari_Final_Split[Forecast Level])),CF-GF,[Total Judgement])",
              "            VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "            Return",
              "         Result",
              "         "
            ],
            "formatString": "0.0",
            "lineageTag": "bc6048ca-10ad-4bc0-a8f8-fec59e04c979"
          },
          {
            "name": "Linearity",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR Num =[Cum Orders]",
              "",
              "VAR Den = IF([M3 Order Plan+Task]<>0,[M3 Order Plan+Task],",
              "IF([M3 Order Plan+Task]=0 && [M2 Order Plan+Task]<>0,[M2 Order Plan+Task],",
              "IF([M3 Order Plan+Task]=0 && [M2 Order Plan+Task]=0,[M1 Order Plan+Task],[M1 Order Plan+Task])))",
              "VAR Output = ",
              "IFERROR(CALCULATE(DIVIDE( Num,Den),ALL('ROF Forecast'[Clari/ROF]),ALL('ROF Forecast'[Forecast Level])),",
              "    BLANK()",
              ")",
              "Return",
              "",
              "Output"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "8921a2c1-9213-4ec8-8207-91ff10a056e0"
          },
          {
            "name": "ROF Detailed_ROF Forecast",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR OpenCloseStatus = SELECTEDVALUE(ColWkSorting[Open/Close])",
              "VAR wkday = SELECTEDVALUE('rpt dim_current_date_rof'[weekday])",
              "VAR RowCurrWeek =CALCULATE(SELECTEDVALUE(RowWkSorting[SortOrder]) ,RowWkSorting[IsCurrentWeek] = \"TRUE\")",
              "",
              "VAR ColCurrWeek = SELECTEDVALUE(ColWkSorting[SortOrder])",
              "VAR currweekvalue =CALCULATE([Forecast Value],RowWkSorting[SortOrder] =RowCurrWeek)",
              "",
              "VAR Days = IF(wkday<=4 && wkday>=2,1,2)",
              "VAR WK3 = CALCULATE([Plan + Task_M1],ColWkSorting[SortOrder]=2)",
              "VAR RemoveWK3 = CALCULATE( [Forecast Value],RowWkSorting[SortOrder] =2,ColWkSorting[SortOrder]=2)",
              "",
              "--If( (WEEKDAY(NOW(),1)) <= 4 && (WEEKDAY(NOW(),1) >=2), 1, 2)",
              "",
              "VAR Preweekvalue =if ( ColCurrWeek = 2,[Plan + Task_M1],CALCULATE([Forecast Value],RowWkSorting[SortOrder] =ColCurrWeek-1))",
              "VAR TotalFcst = CALCULATE([Plan + Task_M1],'RowWkSorting'[SortOrder] = currweekvalue,'ColWkSorting'[SortOrder] =2)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 2,'ColWkSorting'[SortOrder] =3)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 3,'ColWkSorting'[SortOrder] =4)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 4,'ColWkSorting'[SortOrder] =5)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 5,'ColWkSorting'[SortOrder] =6)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 6,'ColWkSorting'[SortOrder] =7)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 7,'ColWkSorting'[SortOrder] =8)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 8,'ColWkSorting'[SortOrder] =9)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 9,'ColWkSorting'[SortOrder] =10)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 10,'ColWkSorting'[SortOrder] =11)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 11,'ColWkSorting'[SortOrder] =12)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 12,'ColWkSorting'[SortOrder] =13)",
              "",
              "RETURN",
              "",
              "if (ISINSCOPE(ColWkSorting[Weeks]),",
              "",
              "Preweekvalue,TotalFcst)",
              "",
              "/*",
              "VAR OpenCloseStatus = SELECTEDVALUE(ColWkSorting[Open/Close])",
              "VAR wkday = SELECTEDVALUE('rpt dim_current_date_rof'[weekday])",
              "VAR RowCurrWeek =CALCULATE(SELECTEDVALUE(RowWkSorting[SortOrder]) ,RowWkSorting[IsCurrentWeek] = \"TRUE\")",
              "",
              "VAR ColCurrWeek = SELECTEDVALUE(ColWkSorting[SortOrder])",
              "VAR currweekvalue =CALCULATE([Forecast Value],RowWkSorting[SortOrder] =RowCurrWeek)",
              "",
              "VAR Days = IF(wkday<=4 && wkday>=2,1,2)",
              "VAR WK3 = CALCULATE([Plan + Task_M1],ColWkSorting[SortOrder]=3)",
              "VAR RemoveWK3 = CALCULATE( [Forecast Value],RowWkSorting[SortOrder] =3,ColWkSorting[SortOrder]=3)",
              "",
              "--If( (WEEKDAY(NOW(),1)) <= 4 && (WEEKDAY(NOW(),1) >=2), 1, 2)",
              "",
              "VAR Preweekvalue =if ( ColCurrWeek = 3,[Plan + Task_M1],CALCULATE([Forecast Value],RowWkSorting[SortOrder] =ColCurrWeek-1))",
              "VAR TotalFcst = CALCULATE([Plan + Task_M1],'RowWkSorting'[SortOrder] = currweekvalue,'ColWkSorting'[SortOrder] =3)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 3,'ColWkSorting'[SortOrder] =4)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 4,'ColWkSorting'[SortOrder] =5)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 5,'ColWkSorting'[SortOrder] =6)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 6,'ColWkSorting'[SortOrder] =7)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 7,'ColWkSorting'[SortOrder] =8)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 8,'ColWkSorting'[SortOrder] =9)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 9,'ColWkSorting'[SortOrder] =10)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 10,'ColWkSorting'[SortOrder] =11)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 11,'ColWkSorting'[SortOrder] =12)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 12,'ColWkSorting'[SortOrder] =13)+",
              "                    CALCULATE([Forecast Value],'RowWkSorting'[SortOrder] = 13,'ColWkSorting'[SortOrder] =14)",
              "",
              "RETURN",
              "",
              "if (ISINSCOPE(ColWkSorting[Weeks]),",
              "",
              "Preweekvalue,TotalFcst)",
              "",
              "*/"
            ],
            "lineageTag": "ec3598be-263e-476c-a1ea-cbf8aabede12"
          },
          {
            "name": "ROF Forecast",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR Displayvalue =",
              "CALCULATE([ROF Detailed_ROF Forecast],'ROF Forecast'[Clari/ROF]=\"ROF\")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "e1529111-d9b9-467b-9e0b-2de17d81175a"
          },
          {
            "name": "CF for font(SCMonthPlans)",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "IF([SC_Month Plans]<=0,\"#C00000\")"
            ],
            "lineageTag": "d292c95d-077a-4a44-9199-838abc02edd4"
          },
          {
            "name": "CF for font(SCCumMonthPlans)",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "IF([SC_Cumu Month Plans]<=0,\"#C00000\")"
            ],
            "lineageTag": "d2813592-fb1f-44bf-b727-362852e56dcc"
          },
          {
            "name": "For Linearity metric_Den_M1_M2_M3 MIX",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR M1 = ",
              "    CALCULATE(",
              "        [M1 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W2\",\"W3\",\"W4\",\"W5\"}",
              "    )",
              "VAR M2 = ",
              "    CALCULATE(",
              "        [M2 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W6\",\"W7\",\"W8\",\"W9\"})",
              "",
              "VAR M3 = ",
              "    CALCULATE(",
              "        [M3 Order Plan+Task],",
              "        'ROF OrderPlan'[WeekNo] IN {\"W10\",\"W11\",\"W12\",\"W13\"}",
              "    )",
              "",
              "VAR DisplayValue = IF(M3<>0,M3,",
              "                    IF(M3=0 && M2<>0,M2,",
              "                    IF(M3=0 && M2=0,M1)))",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",CONVERT(FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\"),INTEGER)))",
              "RETURN",
              "Result"
            ],
            "lineageTag": "c2715c34-b429-4e1f-8dc4-edab14e84d8a"
          },
          {
            "name": "For Linearity_Den_Cum M1_M2_M3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [For Linearity metric_Den_M1_M2_M3 MIX],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")"
            ],
            "lineageTag": "95ee5088-245c-4b5f-8ed7-059e71802f7d"
          },
          {
            "name": "Non Exec Cum (Linearity)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR DisplayValue =calculate([Non Exec Total],ColWkSorting[Open/Close]=\"Close\")",
              "Var Result = if([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result"
            ],
            "lineageTag": "d748c9de-306f-4611-9c2a-7bd84f766df2"
          },
          {
            "name": "Order Budget_Services",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DisplayValue = CALCULATE(DIVIDE(SUM('rpt flashbudget_OR'[Amount]),10^6),'rpt flashbudget_OR'[Target]=\"Budget\",'rpt flashbudget_OR'[Source]=\"Anaplan\")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result",
              ""
            ],
            "lineageTag": "c3842148-e4bc-46e4-947d-2e4ac3c26aff"
          },
          {
            "name": "Order Flash_Services",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DisplayValue = CALCULATE(DIVIDE(SUM('rpt flashbudget_OR'[Amount]),10^6),'rpt flashbudget_OR'[Target]=\"Flash\",'rpt flashbudget_OR'[Source]=\"Anaplan\")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result",
              ""
            ],
            "lineageTag": "7ed5daab-987a-4b94-ac80-11d7316a62af"
          },
          {
            "name": "Orders_Services",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CALCULATE(DIVIDE(SUM('Load Bookings'[bookings]),10^6),'Date'[is_current_week]=1)",
              "",
              ""
            ],
            "lineageTag": "babf14dd-8a20-45fa-aa83-92f08a942a31"
          },
          {
            "name": "Deal Based Forecast_Services",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DisplayValue =",
              "[Commit_Services]-",
              "CALCULATE(",
              "    [Total Revenue_Services],",
              "    FILTER('ColWkSorting',ColWkSorting[Open/Close]=\"Open\"),",
              "   FILTER('RowWkSorting',RowWkSorting[Open/Close]=\"Open\"),",
              "    ",
              "   'Pipeline_Services'[ForecastCategory] =\"Commit\",",
              "    'Pipeline_Services'[DealBased_In/Out] =\"Out\")",
              "+",
              "CALCULATE(",
              "    [Total Revenue_Services],",
              "    'Pipeline_Services'[ForecastCategory] in {\"Upside\",\"Pipeline ES\",\"Pipeline LS\"},",
              "   'Pipeline_Services'[DealBased_In/Out] in {\"In\",\"In At Risk\",\"In At Risk - To Defer to NQ\"})",
              "",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "",
              "Return",
              "Result"
            ],
            "lineageTag": "7bf6d55c-3c68-490d-82c2-867f1cc6c8d8"
          },
          {
            "name": "(Orders + DBF)/Budget_Services",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              " VAR DisplayValue =DIVIDE(([Orders_Services]+[Deal Based Forecast_Services]),[Order Budget_Services])",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "",
              "Return",
              "Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f371238b-b218-4528-8022-fc8f3b70c997"
          },
          {
            "name": "Commit At Risk_Services",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DisplayValue =",
              "CALCULATE(",
              "    [Total Revenue_Services],Pipeline_Services[ForecastCategory] IN {\"Commit\",\"Upside\",\"Pipeline LS\",\"Pipeline ES\"},",
              "    ",
              "    'Pipeline_Services'[DealBased_In/Out] in {\"In At Risk\",\"In At Risk - To Defer to NQ\"},",
              "    FILTER('ColWkSorting',ColWkSorting[Open/Close]=\"Open\"),",
              "    FILTER('RowWkSorting',RowWkSorting[Open/Close]=\"Open\"))",
              "    ",
              "",
              "",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "",
              "Return",
              "Result"
            ],
            "lineageTag": "bd0f8e62-17a8-4a35-bb2d-e8f62e4d4c0c"
          },
          {
            "name": "Commit_Services",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DisplayValue =",
              "CALCULATE(",
              "   [Total Revenue_Services],'Pipeline_Services'[ForecastCategory]=\"Commit\",",
              "    FILTER('ColWkSorting',ColWkSorting[Open/Close]=\"Open\"),",
              "   FILTER('RowWkSorting',RowWkSorting[Open/Close]=\"Open\"))",
              "    ",
              "",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "",
              "Return",
              "Result"
            ],
            "lineageTag": "f76ee3a5-9a50-4577-9020-8d2bc2ef97f0"
          },
          {
            "name": "Strong Upside_Services",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DisplayValue =",
              "CALCULATE(",
              "    [Total Revenue_Services],Pipeline_Services[ForecastCategory] IN {\"Commit\",\"Upside\",\"Pipeline LS\",\"Pipeline ES\"},",
              "    ",
              "    'Pipeline_Services'[DealBased_In/Out] =\"Strong Upside\",",
              "    FILTER('ColWkSorting',ColWkSorting[Open/Close]=\"Open\"),",
              "    FILTER('RowWkSorting',RowWkSorting[Open/Close]=\"Open\"))",
              "    ",
              "",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "",
              "Return",
              "Result"
            ],
            "lineageTag": "bed91190-067b-47b6-a31b-c9a1fbc2804a"
          },
          {
            "name": "Pipeline_Services",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DisplayValue =",
              "CALCULATE(",
              "   [Total Revenue_Services],'Pipeline_Services'[ForecastCategory] in {\"Pipeline ES\",\"Pipeline LS\"},",
              "     FILTER('ColWkSorting',ColWkSorting[Open/Close]=\"Open\"),",
              "   FILTER('RowWkSorting',RowWkSorting[Open/Close]=\"Open\"))",
              "    ",
              "",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "",
              "Return",
              "Result",
              ""
            ],
            "lineageTag": "e98b0f7c-d95b-4aa9-946a-c8c4b5cd486f"
          },
          {
            "name": "Total Revenue_Services",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE(SUM('Pipeline_Services'[Revenue]),10^6)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "35812943-1431-4bec-81a0-606435a64901"
          },
          {
            "name": "Upside_Services",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR DisplayValue =",
              "CALCULATE(",
              "   [Total Revenue_Services],'Pipeline_Services'[ForecastCategory]=\"Upside\",",
              "      FILTER('ColWkSorting',ColWkSorting[Open/Close]=\"Open\"),",
              "   FILTER('RowWkSorting',RowWkSorting[Open/Close]=\"Open\"))",
              "    ",
              "",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "",
              "Return",
              "Result"
            ],
            "lineageTag": "bed4abf3-5dcb-4fd8-949b-7500894b424e"
          },
          {
            "name": "Fcst vs M1 plan",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Current Wk Forecast],[Plan + Task_M1],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "fb24b692-e202-483b-b221-b717a827fde1"
          },
          {
            "name": "Fcst vs M2 plan",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Current Wk Forecast],[Plan + Task_M2],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "d171e936-4ff8-40a7-80a5-4e3034d24164"
          },
          {
            "name": "M1 NEO Value",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR CurrentMonth = \"M1\"",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        SUM(ROF_NEO[NEOPValue]),FILTER('ROF_NEO',ROF_NEO[MonthPlan]=CurrentMonth)",
              "       ",
              "    )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))   ",
              "    RETURN",
              "    ",
              "    ",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "             CurrentMonth, IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\"},BLANK(),",
              "          --   CurrentMonth, IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\",\"W2\"},BLANK(),",
              "            Result)",
              "        ),",
              "      Result",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "732468bc-294c-4b90-a7f3-6045997b91d8"
          },
          {
            "name": "M2 NEO Value",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR CurrentMonth = \"M2\"",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        SUM(ROF_NEO[NEOPValue]),FILTER('ROF_NEO',ROF_NEO[MonthPlan]=CurrentMonth)",
              "       ",
              "    )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))   ",
              "    RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "             CurrentMonth, IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\"},BLANK(),",
              "             --CurrentMonth, IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\",\"W2\"},BLANK(),",
              "            Result)",
              "        ),",
              "      Result",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "cb7b1904-329c-406b-bd3f-8a7b96a363bb"
          },
          {
            "name": "M3 NEO Value",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR CurrentMonth = \"M3\"",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        SUM(ROF_NEO[NEOPValue]),FILTER('ROF_NEO',ROF_NEO[MonthPlan]=CurrentMonth)",
              "       ",
              "    )",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))   ",
              "    RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]),",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(),",
              "             CurrentMonth, IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\"},BLANK(),",
              "            -- CurrentMonth, IF(SELECTEDVALUE(ColWkSorting[Weeks]) in{\"W1\",\"W2\"},BLANK(),",
              "            Result)",
              "        ),",
              "      Result",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "16012ca8-b409-4b0a-a7dc-5c13b2c0d1c1"
          },
          {
            "name": "NEO Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "IF([M3 NEO Value]<>0,[M3 NEO Value],",
              "IF([M3 NEO Value]=0 && [M2 NEO Value]<>0,[M2 NEO Value],",
              "IF([M3 NEO Value]=0 && [M2 NEO Value]=0,[M1 NEO Value],[M1 NEO Value])))",
              "",
              ""
            ],
            "lineageTag": "d488c565-a582-40e8-ab8f-18d6bf6211ee"
          },
          {
            "name": "Exec Orders incl EBBL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "[EBBL]+[Order Budget Plan]-[NEO Value]",
            "lineageTag": "be0950c5-0541-4539-b289-4ed6e5e42e56"
          },
          {
            "name": "Total ROF Pipeline Detailed1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SUM('ROF Pipeline'[Value])",
            "lineageTag": "4c03005e-63ca-403c-b90a-7814d0507ee4"
          },
          {
            "name": "Cum Orders + Forecast (ROF)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Actuals & Forecast Measures",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Forecast Value],",
              "        FILTER(",
              "            ALL(ColWkSorting),",
              "            ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "        )",
              "        ,",
              "        KEEPFILTERS(RowWkSorting[Week] = \"W13 + 1\"))"
            ],
            "lineageTag": "3212abff-0afe-4f6b-ba5b-99294b7dcb08"
          },
          {
            "name": "Measure title",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SELECTEDVALUE('Month Selection'[Month]) & \" Order Plan\"",
            "lineageTag": "b2d6391e-08d7-4728-8516-f6aec3b20e1c"
          },
          {
            "name": "Measure title 2",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "\"Gap by Week vs \"&[Measure title]",
            "lineageTag": "ba3d46fa-9b23-40d8-b2cb-bd75d807baf1"
          },
          {
            "name": "Measure title 3",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "\"Cumulative Gap vs \"&[Measure title]",
            "lineageTag": "0da41d08-4301-4446-86b6-61d85415f402"
          },
          {
            "name": "Flex Solutions Services",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(SUM('ROF Pipeline'[Value]),FILTER('Prod Master','Prod Master'[BU 1]=\"Flex Solutions Services\"))",
            "formatString": "#,0",
            "lineageTag": "76a3cb53-72d4-4160-9dbe-b9ab49be31f9"
          },
          {
            "name": "Compute HW Core",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(SUM('ROF Pipeline'[Value]),FILTER('Prod Master','Prod Master'[BU 3]=\"Compute HW Core\"))",
            "formatString": "#,0",
            "lineageTag": "2f2c9cd9-a86f-4331-98f8-2a2b1bde9147"
          },
          {
            "name": "Storage HW Core",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(SUM('ROF Pipeline'[Value]),FILTER('Prod Master','Prod Master'[BU 4]=\"Storage HW Core\"))",
            "formatString": "#,0",
            "lineageTag": "c5e1838c-4ec2-47d1-af8d-e25a6f2030d7"
          },
          {
            "name": "HPC & AI HW Core",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(SUM('ROF Pipeline'[Value]),FILTER('Prod Master','Prod Master'[BU 3]=\"HPC & AI HW\"))",
            "formatString": "#,0",
            "lineageTag": "cb67a9ac-f52c-48e1-b794-3acd2f319f32"
          },
          {
            "name": "GL Flex Compute HW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(SUM('ROF Pipeline'[Value]),FILTER('Prod Master','Prod Master'[BU 4]=\"Flex Solutions Compute HW\"))",
            "formatString": "#,0",
            "lineageTag": "740658a1-1310-4b48-b6e4-09d7fcf64c81"
          },
          {
            "name": "GL Flex Storage HW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(SUM('ROF Pipeline'[Value]),FILTER('Prod Master','Prod Master'[BU 4]=\"Flex Solutions Storage HW\"))",
            "formatString": "#,0",
            "lineageTag": "ac35ec5c-2d9a-474f-a4d1-00a62c25a903"
          },
          {
            "name": "HPC & AI GL (HW & Svs)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(SUM('ROF Pipeline'[Value]),FILTER('Prod Master','Prod Master'[BU 3]=\"HPC & AI GreenLake (HW & Services)\"))",
            "formatString": "#,0",
            "lineageTag": "bc3d7d7b-348b-49a3-9f30-c4e205b817ff"
          },
          {
            "name": "Private Cloud HW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE(SUM('ROF Pipeline'[Value]),FILTER('Prod Master','Prod Master'[BU 4]=\"Private Cloud HW\"))",
            "formatString": "#,0",
            "lineageTag": "d5d08bb6-23de-4c7f-9651-a20de76e9aa7"
          },
          {
            "name": "Fcst vs M3 plan",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Current Wk Forecast],[Plan + Task_M3],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "39496643-8d13-4a23-afff-067fe2ca6e2a"
          },
          {
            "name": "Linearity_BOE",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "VAR Num =[Cum Orders_BOE]",
              "",
              "VAR Den = IF([M3 Order Plan+Task]<>0,[M3 Order Plan+Task],",
              "IF([M3 Order Plan+Task]=0 && [M2 Order Plan+Task]<>0,[M2 Order Plan+Task],",
              "IF([M3 Order Plan+Task]=0 && [M2 Order Plan+Task]=0,[M1 Order Plan+Task],[M1 Order Plan+Task])))",
              "VAR Output = ",
              "IFERROR(CALCULATE(DIVIDE( Num,Den),ALL('ROF Forecast'[Clari/ROF]),ALL('ROF Forecast'[Forecast Level])),",
              "    BLANK()",
              ")",
              "Return",
              "",
              "Output"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5d0bac4f-ca63-49ab-97ad-380ef84c86bd"
          },
          {
            "name": "Cum Orders_BOE",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR Weekdisplayed = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(RowWkSorting[Week]),",
              "        RowWkSorting[IsCurrentWeek] = \"TRUE\"",
              "    )",
              "VAR ValueDisplayed = ",
              "    IF(",
              "        [Orders_BOE]<> BLANK(),",
              "        CALCULATE(DIVIDE(SUM('OrdersDetailed'[NetUSD]),10^6),",
              "           // [Forecast Value],",
              "            KEEPFILTERS(RowWkSorting[IsCurrentWeek] = \"TRUE\"), ",
              "            KEEPFILTERS(ColWkSorting[Open/Close] = \"Close\" ||ColWkSorting[IsCurrentWeek]=\"True\" && VALUES('rpt dim_current_date_rof'[Actualsavaialble])=\"Y\"),",
              "            KEEPFILTERS('ROF Forecast'[Clari/ROF] = \"ROF\"),",
              "            FILTER(",
              "                ALL(ColWkSorting),",
              "                ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "            )",
              "        )",
              "    )",
              "RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]), ",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(), ",
              "            Weekdisplayed, ",
              "            ValueDisplayed",
              "        ),",
              "        ValueDisplayed",
              "    )"
            ],
            "lineageTag": "cc3c7bad-171e-4d01-bb1e-45d3799159b5"
          },
          {
            "name": "Orders_BOE",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "BOE Order Details",
            "expression": [
              "VAR Weekdisplayed = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(RowWkSorting[Week]),",
              "        RowWkSorting[IsCurrentWeek] = \"TRUE\"",
              "    )",
              "",
              "VAR DisplayValue = ",
              "    CALCULATE(DIVIDE(SUM('OrdersDetailed'[NetUSD]),10^6)",
              "   ",
              "    )",
              "  VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "RETURN ",
              "IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]), ",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(), ",
              "            Weekdisplayed, ",
              "            Result",
              "        ),",
              "        Result",
              "    )",
              " ",
              "  ",
              "    "
            ],
            "formatString": "#,0.0",
            "lineageTag": "f15dcf92-4bb0-48b9-9336-2d362b38ba6a"
          },
          {
            "name": "V/S Order Plan_BOE",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "IFERROR(",
              "    DIVIDE(",
              "        [Orders_BOE],",
              "        [M1_M2_M3 MIX]",
              "    ),",
              "    BLANK()",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "5002677a-d5e4-4d54-8ed9-694b0df47817"
          },
          {
            "name": "V/S Cum Order Plan_BOE",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "IFERROR(",
              "    DIVIDE(",
              "        [Cum Orders_BOE],",
              "        [Cum M1_M2_M3]",
              "    ),",
              "    BLANK()",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4804f9e0-0d3d-4cab-94de-da6378c6cc01"
          },
          {
            "name": "QTD v/s Plan_BOE",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR DisplayValue =",
              "[Orders_BOE] - [M1_M2_M3 MIX]",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "    Return",
              "    Result"
            ],
            "formatString": "#,0.0",
            "lineageTag": "103b534f-e452-41eb-8872-9c6faf9dd0fc"
          },
          {
            "name": "CF for QTD v/s Plan_BOE",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(CONVERT([QTD v/s Plan_BOE],DOUBLE)<0,1,0)",
            "formatString": "0",
            "lineageTag": "a96d4750-e273-4b4f-b039-f3d99092673f"
          },
          {
            "name": "Orders_Compute HW Core",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "BOE Order Details",
            "expression": "CALCULATE([Orders_BOE1],FILTER('Prod Master','Prod Master'[BU 3]=\"Compute HW Core\"))",
            "formatString": "#,0",
            "lineageTag": "65e37e3a-e88e-4273-9945-7ce78dff3a7c"
          },
          {
            "name": "Orders_Edge",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "BOE Order Details",
            "expression": "CALCULATE([Orders_BOE1],FILTER('Prod Master','Prod Master'[BU 2]=\"Edge\"))",
            "formatString": "#,0",
            "lineageTag": "b08b78af-74fa-454a-a44d-57cd2e08be3b"
          },
          {
            "name": "Orders_Flex Solutions Services",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "BOE Order Details",
            "expression": "CALCULATE([Orders_BOE1],FILTER('Prod Master','Prod Master'[BU 1]=\"Flex Solutions Services\"))",
            "formatString": "#,0",
            "lineageTag": "7aeb7eff-ad85-499b-8406-01c25cdfd89a"
          },
          {
            "name": "Orders_GL Flex Compute HW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "BOE Order Details",
            "expression": "CALCULATE([Orders_BOE1],FILTER('Prod Master','Prod Master'[BU 4]=\"Flex Solutions Compute HW\"))",
            "formatString": "#,0",
            "lineageTag": "ffb76c3f-55d5-4f83-9c58-451e58e76256"
          },
          {
            "name": "Orders_GL Flex Storage HW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "BOE Order Details",
            "expression": "CALCULATE([Orders_BOE1],FILTER('Prod Master','Prod Master'[BU 4]=\"Flex Solutions Storage HW\"))",
            "formatString": "#,0",
            "lineageTag": "bfdc952f-0000-4983-b576-7329b485c37a"
          },
          {
            "name": "Orders_HPC & AI GL (HW & Svs)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "BOE Order Details",
            "expression": "CALCULATE([Orders_BOE1],FILTER('Prod Master','Prod Master'[BU 3]=\"HPC & AI GreenLake (HW & Services)\"))",
            "formatString": "#,0",
            "lineageTag": "353efe42-f0b8-4a3c-a490-3db5b8a055c7"
          },
          {
            "name": "Orders_Private Cloud HW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "BOE Order Details",
            "expression": "CALCULATE([Orders_BOE1],FILTER('Prod Master','Prod Master'[BU 4]=\"Private Cloud HW\"))",
            "formatString": "#,0",
            "lineageTag": "bd678e82-c07a-4a54-9d03-5e84b4acbb59"
          },
          {
            "name": "Orders_Storage HW Core",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "BOE Order Details",
            "expression": "CALCULATE([Orders_BOE1],FILTER('Prod Master','Prod Master'[BU 4]=\"Storage HW Core\"))",
            "formatString": "#,0",
            "lineageTag": "5f059937-6102-45c5-b18c-db5c8e40cb1b"
          },
          {
            "name": "Orders_BOE1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "BOE Order Details",
            "expression": [
              "VAR Weekdisplayed = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(RowWkSorting[Week]),",
              "        RowWkSorting[IsCurrentWeek] = \"TRUE\"",
              "    )",
              "",
              "VAR DisplayValue = ",
              "    SUM('OrdersDetailed'[NetUSD])",
              "   ",
              "    ",
              "  VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "RETURN ",
              "IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]), ",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(), ",
              "            Weekdisplayed, ",
              "            Result",
              "        ),",
              "        Result",
              "    )",
              " ",
              "  ",
              "    "
            ],
            "formatString": "#,0",
            "lineageTag": "cc1ba203-8903-4152-9eec-2546fa51f1ab"
          },
          {
            "name": "Orders_HPC & AI HW Core",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "BOE Order Details",
            "expression": "CALCULATE([Orders_BOE],FILTER('Prod Master','Prod Master'[BU 3]=\"HPC & AI HW\"))",
            "formatString": "#,0",
            "lineageTag": "deb07199-a0f1-40a3-ab13-a5b1843c1478"
          },
          {
            "name": "Fontcolor1",
            "displayFolder": "\"vs\" Measures",
            "expression": "IF(IF(MAX(TableNew[Column1])=\"Performance\",[performance])=\"Overachieving\",0,IF(IF(MAX(TableNew[Column1])=\"Performance\",[performance])=\"Underperforming\",1))",
            "formatString": "0",
            "lineageTag": "6feafab5-62fe-4452-8bab-fba3a37fc081"
          },
          {
            "name": "M1M2M3",
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "",
              "",
              "VAR Week = SELECTEDVALUE(ColWkSorting[Weeks])",
              "",
              "RETURN",
              "IF(Week IN{\"W1\",\"W2\",\"W3\",\"W4\",\"W5\"},[M1 Order Plan+Task],",
              "IF(Week IN{\"W6\",\"W7\",\"W8\",\"W9\",\"W10\"},[M2 Order Plan+Task],[M3 Order Plan+Task]))",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "6172d0f9-eab0-4a0c-8c06-6aabd64b4ffc"
          },
          {
            "name": "vs QTD M2 Plan",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": "[Cum Orders]-[Cum M1_M2_M3]",
            "lineageTag": "562b0ef5-2fbb-48bd-bc7e-884b757b568a"
          },
          {
            "name": "performance",
            "displayFolder": "\"vs\" Measures",
            "expression": "IF([vs QTD M2 Plan]>=0,\"Overachieving\",\"Underperforming\")",
            "lineageTag": "93b8a675-1cc9-4788-a38b-a70e8ec09468"
          },
          {
            "name": "Cum Order budget Plan",
            "displayFolder": "Actuals & Forecast Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    [Order Budget Plan],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "754f2f64-2090-4207-961c-bb84a38c8231"
          },
          {
            "name": "Actuals & Forecast Values",
            "displayFolder": "Actuals & Forecast Measures",
            "expression": "IF([Orders]=BLANK(),[Current Wk Forecast],[Orders])",
            "formatString": "0.0",
            "lineageTag": "848875ef-e71b-4219-86a7-5385ebf7f7dd"
          },
          {
            "name": "Check Cal_test",
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "",
              "MAX(TableNew[Column1])=\"Net Orders\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[Orders],",
              "MAX(TableNew[Column1])=\"Net Orders\" && MAX(ColWkSorting[WKDyn]) <>\"CurrWeek-1\",BLANK(),",
              "MAX(TableNew[Column1])=\"Monthly Plan\" &&MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[M1M2M3],",
              "MAX(TableNew[Column1])=\"Monthly Plan\" &&MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\",BLANK(),",
              "MAX(TableNew[Column1])=\"vs Monthly Plan\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[vs QTD M2 Plan],",
              "MAX(TableNew[Column1])=\"vs Monthly Plan\" && MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\",BLANK(),",
              "MAX(TableNew[Column1])=\"vs Budget Plan\"&&  MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[Order Budget Plan],",
              "MAX(TableNew[Column1])=\"vs Budget Plan\"&&  MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\",BLANK(),",
              "MAX(TableNew[Column1])=\"Performance\"&&   MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[performance],",
              "MAX(TableNew[Column1])=\"Performance\"&&  MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\",",
              "BLANK())",
              "",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "acf6d301-5a5d-4b69-9a6b-8443b291b8e8"
          },
          {
            "name": "orders_test for current",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF([Orders]= BLANK(),CALCULATE([Orders],ColWkSorting[WKDyn]=\"CurrWeek-1\"),[Orders])",
            "lineageTag": "87e24985-5771-49b2-92ef-afdb85399525"
          },
          {
            "name": "Actuals_CK&PW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": "IF(VALUES('rpt dim_current_date_rof'[Actualsavaialble])=\"Y\",[Orders],CALCULATE([Orders], ColWkSorting[WKDyn]=\"CurrWeek-1\"))",
            "lineageTag": "885808d4-b9a2-4b82-8ae9-6d3ff990f674"
          },
          {
            "name": "Monthly Plan",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([M1M2M3],ColWkSorting[Weeksdyn]=\"CurrWeek\")",
            "lineageTag": "c351d62d-9465-4910-b42d-b3b14add21ef"
          },
          {
            "name": "Order_Budget_Plan",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Target Measures",
            "expression": "CALCULATE([Order Budget Plan],ColWkSorting[Weeksdyn]=\"CurrWeek\")",
            "lineageTag": "e8d6fce3-a8aa-4251-833b-a444a1ae6893"
          },
          {
            "name": "QTD M2 Plan_Test",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "\"vs\" Measures",
            "expression": "[Actuals_CK&PW]-[Monthly Plan]",
            "lineageTag": "cbebe5e6-1608-4a0b-adf1-ed38d43dc605"
          },
          {
            "name": "vs Budget Plan",
            "displayFolder": "Target Measures",
            "expression": "CALCULATE([Order Budget Plan],ColWkSorting[Weeksdyn]=\"CurrWeek\")",
            "formatString": "0.0",
            "lineageTag": "f223f369-d64b-4670-a776-7f2023a1e801"
          },
          {
            "name": "check call_OL",
            "expression": [
              "SWITCH(TRUE(),",
              "MAX(Table_OL[Column1])=\"Actuals\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[Cum Orders],",
              "MAX(Table_OL[Column1])=\"Actuals\" && MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\",BLANK(),",
              "MAX(Table_OL[Column1])=\"M1 Plan\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M1\",[SC_CUM_Month_OL],",
              "MAX(Table_OL[Column1])=\"M1 Plan\" &&MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M1\",BLANK(),",
              "MAX(Table_OL[Column1])=\"M2 Plan\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M2\",[SC_CUM_Month_OL],",
              "MAX(Table_OL[Column1])=\"M2 Plan\" &&MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M2\",BLANK(),",
              "MAX(Table_OL[Column1])=\"M3 Plan\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M3\",[SC_CUM_Month_OL],",
              "MAX(Table_OL[Column1])=\"M3 Plan\" &&MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M3\",BLANK())"
            ],
            "formatString": "0.0",
            "lineageTag": "00276454-44ee-43ea-980b-048cc5264eee"
          },
          {
            "name": "Check Cal_Geo",
            "expression": [
              "",
              "",
              "SWITCH(TRUE(),",
              "",
              "MAX(TableNew[Column1])=\"Net Orders\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[Cum Orders],",
              "MAX(TableNew[Column1])=\"Net Orders\" && MAX(ColWkSorting[WKDyn]) <>\"CurrWeek-1\",BLANK(),",
              "MAX(TableNew[Column1])=\"M1 Plan\" &&MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M1\"  ,[SC_CUM_Month_OL],",
              "MAX(TableNew[Column1])=\"M1 Plan\" &&MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M1\",BLANK(),",
              "MAX(TableNew[Column1])=\"M2 Plan\" &&MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M2\"  ,[SC_CUM_Month_OL],",
              "MAX(TableNew[Column1])=\"M2 Plan\" &&MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M2\",BLANK(),",
              "MAX(TableNew[Column1])=\"M3 Plan\" &&MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M3\"  ,[SC_CUM_Month_OL],",
              "MAX(TableNew[Column1])=\"M3 Plan\" &&MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M3\",BLANK(),",
              "MAX(TableNew[Column1])=\"vs M1 Plan\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M1\",[vs QTD M2 Plan],",
              "MAX(TableNew[Column1])=\"vs M1 Plan\" && MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M1\",BLANK(),",
              "MAX(TableNew[Column1])=\"vs M2 Plan\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M2\",[vs QTD M2 Plan],",
              "MAX(TableNew[Column1])=\"vs M2 Plan\" && MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M2\",BLANK(),",
              "MAX(TableNew[Column1])=\"vs M3 Plan\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M3\",[vs QTD M2 Plan],",
              "MAX(TableNew[Column1])=\"vs M3 Plan\" && MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\" && SELECTEDVALUE('Month Selection'[Month])=\"M3\",BLANK(),",
              "MAX(TableNew[Column1])=\"vs Budget Plan\"&&  MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[Cum Order budget Plan],",
              "MAX(TableNew[Column1])=\"vs Budget Plan\"&&  MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\",BLANK(),",
              "MAX(TableNew[Column1])=\"Performance\"&&   MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[performance],",
              "MAX(TableNew[Column1])=\"Performance\"&&  MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\",",
              "BLANK())",
              "",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "3e441bc1-53f6-4a21-8017-4fbb5041c287"
          },
          {
            "name": "Column_colors",
            "displayFolder": "\"vs\" Measures",
            "expression": [
              "IF(MAX(Table_OL[Column1])=\"Actuals\",1,2)",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "92f44fd4-466e-4953-924c-2ba3693869ff"
          },
          {
            "name": "checkcall_OL_Budget",
            "expression": [
              "SWITCH(TRUE(),",
              "MAX(Table_OL[Column1])=\"Actuals\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[Cum Orders],",
              "MAX(Table_OL[Column1])=\"Actuals\" && MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\",BLANK(),",
              "MAX(Table_OL[Column1])=\"Budget Plan\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[Cum Order budget Plan],",
              "MAX(Table_OL[Column1])=\"Budget Plan\" && MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\",BLANK())"
            ],
            "formatString": "0.0",
            "lineageTag": "d154e920-720c-41fc-9f3b-42ca1845fe14"
          },
          {
            "name": "Actuals_OL",
            "displayFolder": "Actuals & Forecast Measures",
            "expression": "IF([Orders]= [Blank],[Blank],[Orders])",
            "formatString": "0.0",
            "lineageTag": "7fa69f25-5d19-498b-9d0d-6e5aec82b741"
          },
          {
            "name": "Current Wk Forecast_OL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [Forecast Value],",
              "       KEEPFILTERS(RowWkSorting[IsCurrentWeek] = \"TRUE\"),",
              "    KEEPFILTERS(MAX(RowWkSorting[SortOrder])>(RowWkSorting[SortOrder])",
              ")",
              "",
              ")"
            ],
            "lineageTag": "26f583ea-2ca1-4332-9961-b3712a4b6099"
          },
          {
            "name": "CurrentWk_Forecast_OL",
            "expression": "IF([Orders]=BLANK(),[Current Wk Forecast],BLANK())",
            "formatString": "0.0",
            "lineageTag": "87686e86-b54a-45ad-b007-10ffd1c5a42f"
          },
          {
            "name": "CurrentWk_Forecast_OL_Test",
            "displayFolder": "Actuals & Forecast Measures",
            "expression": "IF([Orders]=[Current Wk Forecast],BLANK(),[Current Wk Forecast])",
            "formatString": "0.0",
            "lineageTag": "6f14f2e1-534e-45db-9054-a6f172f818f4"
          },
          {
            "name": "Dynamic Title",
            "expression": "\"vs Plan \" & SELECTEDVALUE('Month Selection'[Month])",
            "lineageTag": "ba551fbd-96d9-4a98-9f66-8b9859638fb4"
          },
          {
            "name": "Dynamic Title1",
            "expression": "\"vs Plan \" & SELECTEDVALUE('Month Selection'[Month]) & \" Cum\"",
            "lineageTag": "52c1ab10-7eaa-44ee-bab8-320c0c360334"
          },
          {
            "name": "SC_Month_OL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR MonSel = SELECTEDVALUE('Month Selection'[Month])",
              "VAR Result = ",
              "            SWITCH(TRUE(),",
              "            MonSel=\"M1\",[Plan + Task_M1],",
              "            MonSel=\"M2\",[Plan + Task_M2],",
              "            MonSel=\"M3\",[Plan + Task_M3])",
              "",
              "Return",
              "Result",
              ""
            ],
            "lineageTag": "1edc78eb-ded4-4935-adcc-64beb2191a19"
          },
          {
            "name": "SC_CUM_Month_OL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [SC_Month_OL],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    ",
              ")",
              ")"
            ],
            "lineageTag": "eba7e372-bef9-4b3a-8409-f8ad81855585"
          },
          {
            "name": "Dynamic Title_OL",
            "expression": "SELECTEDVALUE('Month Selection'[Month]) & \" Plan \" ",
            "lineageTag": "e1e6e8e3-989b-4514-afef-db97bdc9f2b9"
          },
          {
            "name": "GEO_title",
            "expression": "\"QTD PERFORMANCE VS \" & SELECTEDVALUE('Month Selection'[Month]) &\" PLAN\" ",
            "lineageTag": "867d63dc-d97f-4b76-8941-ac7518528fae"
          },
          {
            "name": "check_test1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "",
              "MAX('Metric Table'[Column1])=\"PQ Orders\",[Cum orders_pq],",
              "",
              "MAX('Metric Table'[Column1])=\"M1 Plan\" && SELECTEDVALUE('Month Selection'[Month])=\"M1\"  ,[SC_CUM_Month_OL],",
              "MAX('Metric Table'[Column1])=\"M2 Plan\" && SELECTEDVALUE('Month Selection'[Month])=\"M2\"  ,[SC_CUM_Month_OL],",
              "MAX('Metric Table'[Column1])=\"M3 Plan\" && SELECTEDVALUE('Month Selection'[Month])=\"M3\"  ,[SC_CUM_Month_OL],",
              "MAX('Metric Table'[Column1])=\"QTD Orders\"  ,[Cum Orders],",
              "MAX('Metric Table'[Column1])=\"Budget Plan\"  ,[Cum Order budget Plan],",
              "",
              "BLANK())"
            ],
            "lineageTag": "7af1f00a-c938-4044-9a7e-a71248088bbd"
          }
        ],
        "partitions": [
          {
            "name": "Calcs-a41ea9d6-0c34-49a0-890b-54a2b10428ed",
            "mode": "import",
            "queryGroup": "ROF Group",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Month Selection",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0c6a239cc11f451b99048bcbd5480d2a"
          }
        ],
        "columns": [
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "25d2cf29-0548-40cd-847b-0bda941777e0",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "da249cf1-8b29-4617-93d3-45b97accb5bf",
        "partitions": [
          {
            "name": "Month Selection-4a03b668-657c-467f-b232-a57e80ffa25a",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DATATABLE(",
                "    \"Month\",STRING,",
                "    {",
                "        {\"M1\"},",
                "        {\"M2\"},",
                "        {\"M3\"}",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Task Option",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f5431c340a8f4911b3d8e0ae382b951c"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "da64914d-81ba-4027-8741-16cd1f09b6ce",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "906524be-3a0f-4959-8231-65fcdb752d12",
        "partitions": [
          {
            "name": "Task Option-d302c5c9-969a-4d64-96dd-8b50fdccbb47",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "{\"W Task\", \"W/O Task\"}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DataRefreshConfig",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DataSet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bf61d79-1193-470b-9ed9-1665c79a5e84",
            "sourceColumn": "DataSet",
            "summarizeBy": "none"
          },
          {
            "name": "Source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "914340a9-e3c4-4465-a7eb-f789e082bc01",
            "sourceColumn": "Source",
            "summarizeBy": "none"
          },
          {
            "name": "Geo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72b9480a-0d92-424b-908d-6b4e7976f230",
            "sourceColumn": "Geo",
            "summarizeBy": "none"
          },
          {
            "name": "RefreshDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy h:nn:ss AM/PM",
            "lineageTag": "e1217d04-a6dd-49ac-b82e-f0149533b949",
            "sourceColumn": "RefreshDate",
            "summarizeBy": "none"
          },
          {
            "name": "RefreshTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e79db66-cc6c-4a38-933a-7690b005cedf",
            "sourceColumn": "RefreshTime",
            "summarizeBy": "none"
          },
          {
            "name": "Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6228c11-9307-41c0-bf40-e78e6ae493c4",
            "sourceColumn": "Comments",
            "summarizeBy": "none"
          },
          {
            "name": "DisplayText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "DataRefreshConfig[Source] & \" \" & DataRefreshConfig[DataSet] & \" \" & DataRefreshConfig[Geo] & \" last refreshed on \" & FORMAT( DataRefreshConfig[RefreshDate], \"dd mmm, YYYY\")",
            "isDataTypeInferred": true,
            "lineageTag": "a07deecf-2e3d-4255-acc5-e89b7215cdcf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DataSetGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fdad988-fa60-44c7-b327-fea98c02d6b8",
            "sourceColumn": "DataSetGroup",
            "summarizeBy": "none"
          },
          {
            "name": "Frequency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c9bb1e1-7905-4f1d-9049-f227b8b54b98",
            "sourceColumn": "Frequency",
            "summarizeBy": "none"
          },
          {
            "name": "BU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6e5051f-4c16-4e64-ac2a-b289999f6513",
            "sourceColumn": "BU",
            "summarizeBy": "none"
          },
          {
            "name": "RefreshFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ba12610-e392-48c4-9280-17a73edcd14c",
            "sourceColumn": "RefreshFlag",
            "summarizeBy": "none"
          },
          {
            "name": "Today",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"Datasets refreshed on \"& TODAY()",
            "isDataTypeInferred": true,
            "lineageTag": "d3a7084f-6701-4a0c-9e4d-6dc9e2e64e85",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Refresh Date Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": "DataRefreshConfig[RefreshDate]",
            "formatString": "m/d/yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "43ea33bb-db7c-4cc2-829a-c1199dd7b9cb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "ebda3dc9-b571-422a-a5d3-0e4de8e0c272",
        "partitions": [
          {
            "name": "DataRefreshConfig-6be3808b-3104-4930-894d-bc78f1ae3b4e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"ROF_Geography_Sheet\" = Source{[Schema=\"ref\",Item=\"DataRefreshConfig\"]}[Data]",
                "in",
                "    ROF_Geography_Sheet"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ROF Pipeline",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "HPE Opportunity Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6fe6cf10-facd-4286-872e-f30290e01a78",
            "sourceColumn": "HPE Opportunity Id",
            "summarizeBy": "none"
          },
          {
            "name": "Opportunity Close Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "5861b95b-f536-4a4d-9981-f76b7b3dab3c",
            "sourceColumn": "Opportunity Close Date",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ef4c6cf-f54f-47fa-aa4d-4ef223e40d28",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Account ST ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b09370a6-ecaf-49ca-b996-1d6899b23690",
            "sourceColumn": "Account ST ID",
            "summarizeBy": "count"
          },
          {
            "name": "Opportunity Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0d4a730-c5d8-4ca6-a735-62d405c1081b",
            "sourceColumn": "Opportunity Name",
            "summarizeBy": "none"
          },
          {
            "name": "Forecast Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19955131-1103-4550-b0fc-0e66ceab2617",
            "sourceColumn": "Forecast Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Stage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "819c3a77-9e2a-4a13-8f1e-69346d501aef",
            "sourceColumn": "Sales Stage",
            "summarizeBy": "none"
          },
          {
            "name": "Opportunity Owner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "057a8cf0-8c74-4714-bc52-3109c146ecf2",
            "sourceColumn": "Opportunity Owner",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNo1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c95b9050-6dcf-46a5-8c3f-eea7adce18d0",
            "sourceColumn": "WeekNo1",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ca2b02a6-e9ed-48ce-ae38-c287c4a6a5cb",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Country Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6c21d2c-320b-4211-9735-ed699111280b",
            "sourceColumn": "Country Name",
            "summarizeBy": "none"
          },
          {
            "name": "ROFGeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61521f92-f312-4ca7-b9f3-a78ea3744feb",
            "sourceColumn": "ROFGeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ROFProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebb629ee-1b03-48a0-a0f5-6bf3b288e2bf",
            "sourceColumn": "ROFProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "Lightning URL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "WebUrl",
            "dataType": "string",
            "lineageTag": "08cca455-bed1-4da3-9f00-a73dd5b7f430",
            "sourceColumn": "Lightning URL",
            "summarizeBy": "none"
          },
          {
            "name": "SFDC URL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "WebUrl",
            "dataType": "string",
            "lineageTag": "14f996b0-205a-4f9c-a6f2-851c714296a6",
            "sourceColumn": "SFDC URL",
            "summarizeBy": "none"
          },
          {
            "name": "DealBased_In/Out",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4a7f354-4e5b-41c7-a0bc-2048e1dc1b92",
            "sourceColumn": "DealBased_In/Out",
            "summarizeBy": "none"
          },
          {
            "name": "OpportunityUpdateText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "502a1684-a80a-4f11-bb48-4a4422f402cb",
            "sourceColumn": "OpportunityUpdateText",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "534771b3-7d2f-41df-b6fa-7f4697ea5fd3",
            "sourceColumn": "WeekNo",
            "summarizeBy": "none"
          },
          {
            "name": "HasGreenLake",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90ac9d15-8501-4fd9-9994-e143966f81d8",
            "sourceColumn": "HasGreenLake",
            "summarizeBy": "none"
          },
          {
            "name": "Strategic Deal Exec Sponsor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5513b178-2716-4aad-a38c-1d7420617b96",
            "sourceColumn": "Strategic Deal Exec Sponsor",
            "summarizeBy": "none"
          },
          {
            "name": "Strategic Deal Review",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30575b46-7946-4461-ad08-035fb98dea88",
            "sourceColumn": "Strategic Deal Review",
            "summarizeBy": "none"
          },
          {
            "name": "Strategic Deal Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF (ISBLANK('ROF Pipeline'[Strategic Deal Review]),\"No\",\"Yes\")",
            "isDataTypeInferred": true,
            "lineageTag": "9359a961-a3f3-48fd-a8bc-2e8bd3bef347",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "188cf656-0507-4ed1-9f6a-cbf781acff85",
        "partitions": [
          {
            "name": "ROF Pipeline-a9508ab6-8d2d-428e-be58-fb38d6ddd468",
            "mode": "import",
            "queryGroup": "ROF Group\\Dims",
            "source": {
              "expression": [
                "let",
                "     Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"fact ROF_Pipeline\" = Source{[Schema=\"fact\",Item=\"ROF_Pipeline_detailed\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"fact ROF_Pipeline\",{{\"HPE Opportunity Id\", type text}, {\"Opportunity Close Date\", type datetime}, {\"Account Name\", type text}, {\"Account ST ID\", Int64.Type}, {\"Opportunity Name\", type text}, {\"Forecast Category\", type text}, {\"Sales Stage\", type text}, {\"Opportunity Owner\", type text}, {\"Primary Reseller\", type text}, {\"WeekNo\", type text}, {\"Opportunity Source ID\", type text}, {\"BusinessAreaCode\", type text}, {\"Value\", type number}, {\"Country Name\", type text}, {\"ROFGeoKey\", type text}, {\"ROFProductKey\", type text}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"Opportunity Close Date\", type date}}),",
                "    #\"Added LightningURL\" = Table.AddColumn(#\"Changed Type1\", \"Lightning URL\", each \"https://hp.lightning.force.com/\" & [Opportunity Source ID], type text),",
                "    #\"Added sfdcURL\" = Table.AddColumn(#\"Added LightningURL\", \"SFDC URL\", each \"https://hp.my.salesforce.com/\" & [Opportunity Source ID], type text),",
                "    #\"Grouped Rows\" = Table.Group(#\"Added sfdcURL\", {\"HPE Opportunity Id\", \"Opportunity Close Date\", \"Account Name\", \"Account ST ID\", \"Opportunity Name\", \"Forecast Category\", \"Sales Stage\", \"Opportunity Owner\", \"Primary Reseller\", \"WeekNo\", \"Opportunity Source ID\", \"Country Name\", \"ROFGeoKey\", \"ROFProductKey\", \"Lightning URL\", \"SFDC URL\", \"DealBased_In/Out\", \"OpportunityUpdateText\", \"HasGreenLake\",\"Strategic Deal Exec Sponsor\",\"Strategic Deal Review\"}, {{\"Value\", each List.Sum([Value]), type nullable number}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Grouped Rows\",{{\"WeekNo\", \"WeekNo1\"}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Renamed Columns\", \"WeekNo\", each if [WeekNo1] = \"W1\" then \"W2\" else if [WeekNo1] = \"W13-1\" then \"W13\" else [WeekNo1]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"Primary Reseller\", \"Opportunity Source ID\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Top Deal Count",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3ff96cbf8d6e4c6799444ed01dcd83c2"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a0e81968-bd86-41bf-9beb-29921f7ffa3d",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "a75d6bd4-7902-4f51-aed3-18eab9fe5c34",
        "measures": [
          {
            "name": "N Opps",
            "expression": "DISTINCTCOUNT('ROF Pipeline'[HPE Opportunity Id])",
            "formatString": "0",
            "lineageTag": "eac2f013-ecbf-4d6a-8a7d-ceb06b98e004"
          }
        ],
        "partitions": [
          {
            "name": "Top Deal Count-15eab59c-893d-4e45-953d-e527a77301eb",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "GENERATESERIES(1,100,1)"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dummy Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "94407b63145341ceaf2f1a58ed0df864"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0ec98778-45f4-421b-9479-d6fb5bacf7b2",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "fb584145-54b2-4cb8-a43f-63f7c9ae0b20",
        "partitions": [
          {
            "name": "Dummy Table-77ac7a45-6bfc-4d0e-b554-b27b3384dac0",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "{1}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Date Last Refreshed",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date Last Refreshed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c65d25b0-f2c8-4a8c-a9c7-63882bda2232",
            "sourceColumn": "Date Last Refreshed",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7637700d-ca39-45e0-a10a-5e39d5215739",
        "partitions": [
          {
            "name": "Date Last Refreshed-ad2f4b8b-c45a-4574-a91c-8ff3da537c27",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #table(type table[Date Last Refreshed=datetime], {{DateTime.LocalNow()}})",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "UAM Attributes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RequestID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "89f78c1c-81f1-4b5f-b3a4-472cb8fae3bc",
            "sourceColumn": "RequestID",
            "summarizeBy": "count"
          },
          {
            "name": "RequestedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6e73bb66-aca0-4306-a57e-47c59b6e8b67",
            "sourceColumn": "RequestedDate",
            "summarizeBy": "none"
          },
          {
            "name": "NTNAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14be4301-46fb-4e6b-93aa-cbf9e6b50898",
            "sourceColumn": "NTNAME",
            "summarizeBy": "none"
          },
          {
            "name": "EmployeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0c8cfec-f539-40e7-b891-736a11ec1bab",
            "sourceColumn": "EmployeeID",
            "summarizeBy": "none"
          },
          {
            "name": "ResourceName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adb67739-e402-45d3-8522-24439c5c6d37",
            "sourceColumn": "ResourceName",
            "summarizeBy": "none"
          },
          {
            "name": "ATTRIBUTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e6c55fa-120c-4a6f-8f54-63abca1efc5b",
            "sourceColumn": "ATTRIBUTE",
            "summarizeBy": "none"
          },
          {
            "name": "DATAFIELD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1365281b-91d7-44b3-a08a-c622b36424e7",
            "sourceColumn": "DATAFIELD",
            "summarizeBy": "none"
          },
          {
            "name": "DATAVALUE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8260da01-4a2a-4047-b6be-032c285162ff",
            "sourceColumn": "DATAVALUE",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76f45eb3-469d-4c67-a006-dfb82e1ec3bd",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fd526466-5007-4229-bf38-daea56da10b2",
        "partitions": [
          {
            "name": "UAM Attributes-c2eeed26-0b66-429c-8759-47ed91271cdf",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerBI.Dataflows(null),",
                "    #\"bcdf7dcb-64ea-4e11-aa55-ece3a23a2c01\" = Source{[workspaceId=\"bcdf7dcb-64ea-4e11-aa55-ece3a23a2c01\"]}[Data],",
                "    #\"fe397d83-41c4-4182-bdff-064c2b4ebccb\" = #\"bcdf7dcb-64ea-4e11-aa55-ece3a23a2c01\"{[dataflowId=\"fe397d83-41c4-4182-bdff-064c2b4ebccb\"]}[Data],",
                "    #\"UAM Attributes1\" = #\"fe397d83-41c4-4182-bdff-064c2b4ebccb\"{[entity=\"UAM Attributes\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"UAM Attributes1\", each ([TypeName] = \"POWER BI - PBI Sales Cockpit\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"ACCESS\", \"ALIAS\", \"TypeName\", \"OMIT\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "rpt dim_current_date_rof",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "datekey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "749a90cf-a4a1-4635-8555-0254f3cf3ebd",
            "sourceColumn": "datekey",
            "summarizeBy": "none"
          },
          {
            "name": "fiscal_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "df5913ef-1338-4a1c-9322-b10fd1c76665",
            "sourceColumn": "fiscal_year",
            "summarizeBy": "sum"
          },
          {
            "name": "fiscal_quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "41c55981-9e19-4326-ab61-a751af68343d",
            "sourceColumn": "fiscal_quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "fiscal_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb2b5730-76f2-4e46-a639-1eb054589f30",
            "sourceColumn": "fiscal_month",
            "summarizeBy": "sum"
          },
          {
            "name": "fiscal_week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8038e06c-9174-48cf-8fc6-d8b852fc0930",
            "sourceColumn": "fiscal_week",
            "summarizeBy": "sum"
          },
          {
            "name": "FiscalQuarterStartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0a01fa3a-40cd-4dd4-9d71-82c862882d85",
            "sourceColumn": "FiscalQuarterStartDate",
            "summarizeBy": "none"
          },
          {
            "name": "Latest FYQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE('rpt dim_current_date_rof'[fiscal_year] & \"-Q\",CONCATENATE('rpt dim_current_date_rof'[fiscal_quarter] & \"-Week\",IF('rpt dim_current_date_rof'[fiscal_week]=14,\"13-1\",'rpt dim_current_date_rof'[fiscal_week])))",
            "isDataTypeInferred": true,
            "lineageTag": "82d83732-3e1c-4d32-9e98-10c8928114a0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKDAY('rpt dim_current_date_rof'[datekey])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f51f26cb-506a-4ce2-bc90-6bcbf81cb87f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Actualsavaialble",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0ea034f-797b-492a-b359-043d81fb8725",
            "sourceColumn": "Actualsavaialble",
            "summarizeBy": "none"
          },
          {
            "name": "Current_Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "\"- Wk\" & 'rpt dim_current_date_rof'[fiscal_week]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f60cec93-3d5f-47de-82fc-4259471c0f26",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Qtd_orders_title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "\"Wk\" & 'rpt dim_current_date_rof'[fiscal_week] & \" QTD Net Orders\" ",
            "isDataTypeInferred": true,
            "lineageTag": "897cf93d-a66f-43db-bda9-36a233902c88",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "c3eee537-9573-47c2-8919-7a15ca84f64d",
        "partitions": [
          {
            "name": "rpt dim_current_date_rof-62906c01-7036-4f8d-a527-32613a7bd8e1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    rpt_dim_current_date = Source{[Schema=\"rpt\",Item=\"dim_current_date_rof\"]}[Data]",
                "in",
                "    rpt_dim_current_date"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Geo Bridge",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3eb33917-cf83-4e66-943f-5bf3e005c590",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "SubRegion1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7707f160-2f8e-4294-b91a-e4b38d8d5f30",
            "sourceColumn": "SubRegion1",
            "summarizeBy": "none"
          },
          {
            "name": "SubRegion2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d97af526-6f0e-4c1f-b001-e410a9a3c8fd",
            "sourceColumn": "SubRegion2",
            "summarizeBy": "none"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a421daf2-ab3a-452d-8bba-0f3570b3fd71",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "Reporting",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e9aab9f-d038-435a-896c-34b69512be46",
            "sourceColumn": "Reporting",
            "summarizeBy": "none"
          },
          {
            "name": "ROFGeoKEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bbd08c1-be57-4bfd-b134-b5d1be53fb0a",
            "sourceColumn": "ROFGeoKEY",
            "summarizeBy": "none"
          },
          {
            "name": "ReportingNew",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9358cdf-927d-4d0d-85ae-0e9b95a4dd16",
            "sourceColumn": "ReportingNew",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2ed4a2c4-5090-49e2-8720-ded7bd7671de",
        "partitions": [
          {
            "name": "Geo Bridge-b3c57a3b-d415-4e42-b7e3-3d323aaf7c6c",
            "mode": "import",
            "queryGroup": "ROF Group\\Dims",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"ROF_Geography_Sheet\" = Source{[Schema=\"dim\",Item=\"Geography\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(ROF_Geography_Sheet, \"ReportingNew\", each if [SubRegion2]=\"China\" then \"Y\"",
                "else [Reporting]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\",{\"AdjPipelineSubregion\", \"Country\", \"CountryCode\", \"PETGeo\", \"RegionSecurity\", \"SubRegion3\", \"SubRegion4\", \"SubRegion5\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Prod Bridge",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e4fd977-a261-453f-a2df-d623a1c7cc14",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "Level_6_Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c4a4654-7b5b-4657-b12c-03caa9c89aae",
            "sourceColumn": "Level_6_Description",
            "summarizeBy": "none"
          },
          {
            "name": "Level_5_Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c1961b0-ac63-4718-8242-cf5e8f320b33",
            "sourceColumn": "Level_5_Description",
            "summarizeBy": "none"
          },
          {
            "name": "Level_4_Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "879c3f5a-5db0-40a5-a11d-ff29535b3b7c",
            "sourceColumn": "Level_4_Description",
            "summarizeBy": "none"
          },
          {
            "name": "Level_3_Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e3ad9ea-7998-419c-8ed2-2522296c7e71",
            "sourceColumn": "Level_3_Description",
            "summarizeBy": "none"
          },
          {
            "name": "Level_2_Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3264fbd8-ef4a-4d1e-9e32-7dfe9e9f062f",
            "sourceColumn": "Level_2_Description",
            "summarizeBy": "none"
          },
          {
            "name": "Level_1_Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69f6d8e5-52c1-4303-8d24-0f6343953ceb",
            "sourceColumn": "Level_1_Description",
            "summarizeBy": "none"
          },
          {
            "name": "PL_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bc6ff2a-d494-4e22-9c26-eccbd55cc200",
            "sourceColumn": "PL_Name",
            "summarizeBy": "none"
          },
          {
            "name": "GBUGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dfda4a8-7056-400d-adef-7529a573e183",
            "sourceColumn": "GBUGroup",
            "summarizeBy": "none"
          },
          {
            "name": "GBUSubGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c924d88-37fc-4ed6-a73c-c1e2358a2d20",
            "sourceColumn": "GBUSubGroup",
            "summarizeBy": "none"
          },
          {
            "name": "Reporting",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e84c0f15-2714-4535-8297-b256e2a82056",
            "sourceColumn": "Reporting",
            "summarizeBy": "none"
          },
          {
            "name": "ROFProductKEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6034dbad-98d8-4a58-ac3b-5784b7a577a5",
            "sourceColumn": "ROFProductKEY",
            "summarizeBy": "none"
          },
          {
            "name": "PET_Level_4_5_Mix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd8869c5-7b9c-49b8-a9bb-804ae8cd32d0",
            "sourceColumn": "PET_Level_4_5_Mix",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9bcaeb38-fb7c-4619-a266-17249636e14c",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          },
          {
            "name": "GBUGroup2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6dbf21e1-2454-415b-9470-620d7582dce0",
            "sourceColumn": "GBUGroup2",
            "summarizeBy": "none"
          },
          {
            "name": "GLProductkey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a32434d-9b16-4df7-b4f3-fa77720d8031",
            "sourceColumn": "GLProductkey",
            "summarizeBy": "none"
          },
          {
            "name": "Level_1_Descrition_Svc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c748613a-dea4-4b45-be60-e81bf0fba9ce",
            "sourceColumn": "Level_1_Descrition_Svc",
            "summarizeBy": "none"
          },
          {
            "name": "GBUGroup3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a31ef2e-acce-46c0-adca-9bf3e22234f1",
            "sourceColumn": "GBUGroup3",
            "summarizeBy": "none"
          },
          {
            "name": "GBUGroup4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f892e56d-cebf-47a9-ad80-34f22c8dbe4d",
            "sourceColumn": "GBUGroup4",
            "summarizeBy": "none"
          },
          {
            "name": "BUFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "if('Prod Bridge'[GBUGroup] in {\"Edge\",\"HPE Products\"} ,if('Prod Bridge'[GBUGroup2]<>\"GreenLake\",\"HW\",\"GL HW\"),'Prod Bridge'[GBUGroup2])",
            "isDataTypeInferred": true,
            "lineageTag": "b2b3fb30-90a0-4419-b8ce-c89041664826",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "GBUGroup6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF('Prod Bridge'[Level_2_Description] IN {\"A&PS\",\"Software\"},'Prod Bridge'[GBUSubGroup],'Prod Bridge'[GBUGroup4])",
            "isDataTypeInferred": true,
            "lineageTag": "a814f11a-0645-4363-ac2e-acb1638f9641",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "OriginalProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b49e4d6-044a-453f-8bf4-9072a986547e",
            "sourceColumn": "OriginalProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "HierarchyFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50bd17c3-462a-401a-a1c2-a598441d3544",
            "sourceColumn": "HierarchyFlag",
            "summarizeBy": "none"
          },
          {
            "name": "Level_4_Description (original)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee14cc65-426c-48a3-b044-426e2baf253f",
            "sourceColumn": "Level_4_Description (original)",
            "summarizeBy": "none"
          },
          {
            "name": "Level_3_Description (original)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8a32f10-3fb0-4cfa-9698-67611db1a4e0",
            "sourceColumn": "Level_3_Description (original)",
            "summarizeBy": "none"
          },
          {
            "name": "GBUSubGroup2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41db8b31-d41e-4c74-80aa-7ec160464aad",
            "sourceColumn": "GBUSubGroup2",
            "summarizeBy": "none"
          },
          {
            "name": "GBUGroup5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa36ab6a-ed53-4955-8245-cd0e6cc6835c",
            "sourceColumn": "GBUGroup5",
            "summarizeBy": "none"
          },
          {
            "name": "internalGLNLrep",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a5ba570-9e5f-44bb-9914-f7bd7ba53f3f",
            "sourceColumn": "internalGLNLrep",
            "summarizeBy": "none"
          },
          {
            "name": "HW/Services",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d658f988-c0be-40e9-a0a8-397dd07e1ffe",
            "sourceColumn": "HW/Services",
            "summarizeBy": "none"
          },
          {
            "name": "GBUSubGroup3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF('Prod Bridge'[GBUSubGroup]in{\"OS\",\"GL OS\",\"Compute Subscription Services\",\"GL Compute Subscription Services\"},\"OS\",",
              "                    IF('Prod Bridge'[GBUSubGroup]in{\"GL A&PS\",\"A&PS\"},\"A&PS\",",
              "                        IF('Prod Bridge'[GBUGroup]=\"Hybrid Cloud Software\",'Prod Bridge'[GBUGroup],",
              "                                IF('Prod Bridge'[GBUGroup]in {\"Edge Services\",\"Telco Solutions\",\"Edge SASE\"},\"Edge\",",
              "                                    IF('Prod Bridge'[GBUSubGroup]in {\"Private Cloud\",\"GL Private Cloud\"},\"Private Cloud\",",
              "                               ",
              "                                \"\")))))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e880f7f8-1ed6-4116-8cce-320b69505082",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "GBUSubGroup4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF('Prod Bridge'[GBUSubGroup3]=\"Hybrid Cloud Software\",'Prod Bridge'[Level_3_Description],'Prod Bridge'[GBUSubGroup])",
              "",
              "//IF('Prod Bridge'[Level_2_Description] IN {\"A&PS\",\"Software\"},'Prod Bridge'[GBUSubGroup],'Prod Bridge'[GBUGroup4])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "f71b199f-a69b-4a29-b694-054d54cf5ee4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "0a27f205-ec7e-4088-b08c-bf7b726d7325",
        "partitions": [
          {
            "name": "Prod Bridge-ed3d69ff-64f6-46cf-9767-340d817786d8",
            "mode": "import",
            "queryGroup": "ROF Group\\Dims",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"ROF_Geography_Sheet\" = Source{[Schema=\"rpt\",Item=\"Product_All\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(ROF_Geography_Sheet,{\"Alternate BU\", \"BusinessAreaCode\", \"CloudService\", \"FocusProducts\", \"GBUGroupSecurity\", \"Trad_vs_aaS\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Load Bookings",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "fiscalweekkey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"FY\"&left(REPLACE('Load Bookings'[fiscalquarter],1,2,\"\"),2)&right('Load Bookings'[fiscalquarter],2)&'Load Bookings'[weekno]",
            "isDataTypeInferred": true,
            "lineageTag": "52faf59c-e1df-4020-ae44-5df161517972",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "GP_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Load Bookings'[geokey]&\"_\"&'Load Bookings'[ProductKey]&\"_\"&'Load Bookings'[SalesMotion]",
            "isDataTypeInferred": true,
            "lineageTag": "67ff8a74-1626-407d-ae14-6193fe49df56",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "fiscalquarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce2fab13-61df-416c-9a08-5d027b3de0b7",
            "sourceColumn": "fiscalquarter",
            "summarizeBy": "none"
          },
          {
            "name": "weekno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2b77023-bf3d-4eff-a826-a655ff3a96a7",
            "sourceColumn": "weekno",
            "summarizeBy": "none"
          },
          {
            "name": "geokey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16f53e2c-c078-4225-beca-1f07693ed407",
            "sourceColumn": "geokey",
            "summarizeBy": "none"
          },
          {
            "name": "productkey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8730033-b20b-46ec-b3ff-ba9bd5c926c1",
            "sourceColumn": "productkey",
            "summarizeBy": "none"
          },
          {
            "name": "salesmotion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2639236-214d-4c63-a1cb-c7315627afce",
            "sourceColumn": "salesmotion",
            "summarizeBy": "none"
          },
          {
            "name": "bookings",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f3ec4aac-9b55-469c-b2d0-a3618821d74d",
            "sourceColumn": "bookings",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "83954289-ec5b-4de2-af15-3d798db77c23",
        "partitions": [
          {
            "name": "Load Bookings-580eb80e-4b05-49e4-a0f6-1d9816b13e3b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\", [Query=\"select * from rpt.loadbookings_BOE where FiscalQuarter=(select cast(fiscal_year as varchar(10))+'-Q'+cast(fiscal_quarter as varchar(5)) from rpt.dim_current_date)\"]),",
                "    //#\"Appended Query\" = Table.Combine({Source, LoadBookings_ROF}),",
                "    //#\"Changed Type\" = Table.TransformColumnTypes(#\"Source\",{{\"fiscalquarter\", type text}, {\"weekno\", type text}, {\"geokey\", type text},{\"productkey\", type text}, {\"RTM\", type text},{\"Bookings\", type number},    {\"salesmotion\", type text}}),",
                "    #\"Added W13-1\" = Table.TransformColumns (#\"Source\", {{\"weekno\", each Text.Replace(\"W\" & _,\"W14\",\"W13-1\")}} ),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Added W13-1\",{\"fiscalquarter\", \"weekno\", \"geokey\", \"productkey\", \"bookings\",  \"salesmotion\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each ([bookings] <> null)),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",null,\"blank\",Replacer.ReplaceValue,{\"salesmotion\"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Days Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "73837f81384b4d1e83966ecbc8e5bace"
          }
        ],
        "columns": [
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d96085c8-e2ea-4ff1-a22b-f5a35c5aa167",
            "sourceColumn": "[Day]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a1cdaaa2-2f28-418e-ac4f-75dd4367800c",
            "sourceColumn": "[Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "To Go",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d0a044ff-42e9-4cbb-b8cc-8eed749acfd0",
            "sourceColumn": "[To Go]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "ad58da91-8f1f-4be9-a3de-eaa9269ad3df",
        "partitions": [
          {
            "name": "Days Table-25cfcdd1-c6f6-4752-a0a0-7b79ab377964",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DATATABLE(",
                "    \"Day\",STRING,",
                "    \"Number\",INTEGER,",
                "    \"To Go\",INTEGER,",
                "    {",
                "        {\"Thu\", 4, 1},",
                "        {\"Fri\", 1, 4},",
                "        {\"Mon\", 2, 3},",
                "        {\"Tue\", 3, 2},",
                "        {\"Wed\", 5, 0}",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Month new",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Plan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6c2d944-940e-483f-8f97-f3c0805c6d11",
            "sourceColumn": "Plan",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1d797ea-dd46-427b-a322-95c8afbac588",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bb5a67f5-923c-4b98-af17-48533d15c405",
        "partitions": [
          {
            "name": "Month new-ee8369b2-e4b6-4ada-a97f-2426518fb563",
            "mode": "import",
            "queryGroup": "ROF Group\\Facts",
            "source": {
              "expression": [
                "let",
                "    Source = #\"ROF OrderPlan\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Plan\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Inserted Text Before Delimiter\" = Table.AddColumn(#\"Removed Duplicates\", \"Text Before Delimiter\", each Text.BeforeDelimiter([Plan], \"-\"), type text),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Text Before Delimiter\",{{\"Text Before Delimiter\", \"Month\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim ROF_WeekNO",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CloseDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "40d31960-a7f4-4961-a438-e9d1636acb2f",
            "sourceColumn": "CloseDate",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b2bfbe3c-9c0e-46a3-af0c-1b2fc730a2a9",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNo1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4927cdd5-8c31-4a9c-931b-aad3fcb24e62",
            "sourceColumn": "WeekNo1",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekNo2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d7c7f25-17c3-4c51-a960-b32e881f396f",
            "sourceColumn": "WeekNo2",
            "summarizeBy": "none"
          },
          {
            "name": "Cal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "Year('dim ROF_WeekNO'[Day])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d195b10f-4288-4c3d-8e00-8ba7692f676c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "SWITCH('dim ROF_WeekNO'[Cal Month],11,\"Nov\",12,\"Dec\",1,\"Jan\",2,\"Feb\",3,\"Mar\",4,\"Apr\",5,\"May\",6,\"Jun\",7,\"Jul\",8,\"Aug\",9,\"Sep\",10,\"Oct\")",
            "isDataTypeInferred": true,
            "lineageTag": "2a9601a2-8030-4f21-87a1-2a913eb9c764",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Fiscal Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "if('dim ROF_WeekNO'[Fiscal Month] = \"Nov\" || 'dim ROF_WeekNO'[Fiscal Month] = \"Dec\" ||'dim ROF_WeekNO'[Fiscal Month] = \"Jan\", \"Q1\", if('dim ROF_WeekNO'[Fiscal Month] = \"Feb\" ||'dim ROF_WeekNO'[Fiscal Month] = \"Mar\" ||'dim ROF_WeekNO'[Fiscal Month] = \"Apr\",\"Q2\",if('dim ROF_WeekNO'[Fiscal Month] = \"May\" ||'dim ROF_WeekNO'[Fiscal Month] = \"Jun\" ||'dim ROF_WeekNO'[Fiscal Month] = \"Jul\" ,\"Q3\" ,if('dim ROF_WeekNO'[Fiscal Month] = \"Aug\" ||'dim ROF_WeekNO'[Fiscal Month] = \"Sep\" ||'dim ROF_WeekNO'[Fiscal Month] = \"Oct\" ,\"Q4\"))))",
            "isDataTypeInferred": true,
            "lineageTag": "3740cf2c-4e3a-477c-98a8-0a2aa90504c3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "if('dim ROF_WeekNO'[Cal Month] = 11 || 'dim ROF_WeekNO'[Cal Month] = 12, 'dim ROF_WeekNO'[Cal Year]+1,'dim ROF_WeekNO'[Cal Year])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "38a9b14b-d845-41ef-ba23-159c1e83b99d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Cal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH('dim ROF_WeekNO'[Day])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2bcb46fa-113d-4325-ae1b-58190070a625",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "ffda3e47-a1ea-42bf-b1de-1fd8b3140a17",
        "partitions": [
          {
            "name": "dim ROF_WeekNO-df89ec06-4dca-45ac-abd7-b663e755517a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    dim_ROF_WeekNO = Source{[Schema=\"dim\",Item=\"ROF_WeekNO\"]}[Data]",
                "in",
                "    dim_ROF_WeekNO"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Metric Definitions",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dashboard",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da18e85e-5674-4b76-a548-8eea1e94291c",
            "sourceColumn": "Dashboard",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41ee581f-3ccc-4397-96ee-6e392e9909d2",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Metric",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae9389ec-c740-449d-adb9-2fd87399e9b3",
            "sourceColumn": "Metric",
            "summarizeBy": "none"
          },
          {
            "name": "Definition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d9f4bd8-6cc3-486d-addb-1e09bda92bf5",
            "sourceColumn": "Definition",
            "summarizeBy": "none"
          },
          {
            "name": "Available in Page",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edc62580-658c-48d8-a9e5-0396ed77e675",
            "sourceColumn": "Available in Page",
            "summarizeBy": "none"
          },
          {
            "name": "Page",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d492809-7350-4f95-b23e-7f1c23f0a153",
            "sourceColumn": "Page",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d1cebd3-6246-49cd-ba05-21d94fcf387f",
            "sourceColumn": "Value",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e05520bd-04b7-42d9-97c9-b74c9bd16372",
        "partitions": [
          {
            "name": "Metric Definitions-676e8c1e-5103-47f2-afbb-e468cf1aa56d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://hpe.sharepoint.com/sites/msteams_ac908f/Shared%20Documents/Project%20Phases/Deploy/Training%20material/MetricDefinitions.xlsx\"), null, true),",
                "    Table_metrics_Table = Source{[Item=\"Table_metrics\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table_metrics_Table,{{\"Dashboard\", type text}, {\"Category\", type text}, {\"Metric\", type text}, {\"Definition\", type text}, {\"Available in Page\", type text}, {\"Pipeline Coverage HW\", type text}, {\"Pipeline Coverage Services\", type text}, {\"Waterfall HW\", type text}, {\"Waterfall Services\", type text}, {\"Accelerate the Quarter\", type text}, {\"Order Details\", type text}, {\"ROF Executive\", type text}, {\"ROF Detailed\", type text}, {\"ROF Mobile\", type text}}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type\", {\"Available in Page\", \"Dashboard\", \"Category\", \"Metric\", \"Definition\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"Page\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Custom notifications",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ReportName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1ff34e6-7477-41a1-858d-f2b0134d2115",
            "sourceColumn": "ReportName",
            "summarizeBy": "none"
          },
          {
            "name": "Message",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b15fe16a-fa78-4d74-b302-0d912009fe10",
            "sourceColumn": "Message",
            "summarizeBy": "none"
          },
          {
            "name": "CustomMessage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d5d69d8-3585-4590-ad5a-613c21526843",
            "sourceColumn": "CustomMessage",
            "summarizeBy": "none"
          },
          {
            "name": "Message to Show",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "CONCATENATE( 'Custom Notifications'[Message]& \"  \",",
              "CONCATENATE('Custom Notifications'[CustomMessage],\" \"))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "59e86df3-e095-4e86-b8ea-e451b8d46a86",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "RefreshTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c081acb6-40ef-4466-b67f-cbb009f960c6",
            "sourceColumn": "RefreshTime",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d12f616d-91ed-426a-8aa4-ad89f0446ab0",
        "measures": [
          {
            "name": "Measure Absolute",
            "expression": "SELECTEDVALUE('Custom notifications'[Message])",
            "lineageTag": "52576e88-7296-49b7-87cc-56f0291c1a36"
          }
        ],
        "partitions": [
          {
            "name": "Custom notifications-15f29a9e-4ee1-4c30-a097-3d0593724c54",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"ref.CustomNotifications\")),",
                "    ref_CustomNotifications = #\"Filtered Rows\"{[Schema=\"ref\",Item=\"CustomNotifications\"]}[Data],",
                "    #\"Filtered Rows1\" = Table.SelectRows(ref_CustomNotifications, each ([ReportName] = \"ROF\"))",
                "in",
                "    #\"Filtered Rows1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ROF_Clari_Final_Split",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7be92525-f388-4d52-8b4b-c83418d5533a",
            "sourceColumn": "FiscalQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93ec7730-3f00-44b3-87ae-d230cde3d4e0",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "ForecastEntryType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eccdcba7-5ca7-4456-9d3e-3aa551007006",
            "sourceColumn": "ForecastEntryType",
            "summarizeBy": "none"
          },
          {
            "name": "DealBasedType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd6ce572-6470-4d2e-ae40-8c6b85a41e3a",
            "sourceColumn": "DealBasedType",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1610a1f-3db2-4940-8443-d15f87d2608a",
            "sourceColumn": "WeekNo",
            "summarizeBy": "none"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "989ec244-7389-4c5b-ba75-bb3beb122e03",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afd691d0-1a63-4674-8fb7-60cff3508a36",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ColumnWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95f26ee6-06fd-4447-a216-68053d5459f5",
            "sourceColumn": "ColumnWeek",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0f0fbb24-50d8-49e3-a0c3-bbf6853a7051",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Forecast Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('Geo Master'[Clari Forecast Toggle])",
            "isDataTypeInferred": true,
            "lineageTag": "afdf4658-5fa4-4325-9843-cc407bc918ca",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "a3110933-8562-4d87-9a59-574d98d2e048",
        "partitions": [
          {
            "name": "ROF_Clari_Final_Split-c1faf5ee-e23f-4658-9ced-07901411f4ef",
            "mode": "import",
            "queryGroup": "ROF Group\\Facts",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    fact_ROF_Clari_Final_Split = Source{[Schema=\"fact\",Item=\"ROF_Clari_Final_Split\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(fact_ROF_Clari_Final_Split,{\"CountryCode\", \"BusinessAreaCode\", \"Total\"}),",
                "    #\"Unpivoted Columns\" = Table.UnpivotOtherColumns(#\"Removed Columns\", {\"FiscalQuarter\", \"Region\", \"Country\", \"BU\", \"DataType\", \"ForecastEntryType\", \"DealBasedType\", \"WeekNo\", \"GeoKey\", \"ProductKey\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Columns\",{{\"Attribute\", \"ColumnWeek\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Value\", type number}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type\",{\"BU\", \"Country\", \"DataType\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Metrics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Forecast vs Flash",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f53af2f-c82a-4379-a4f6-d0dad416bdcf",
            "sortByColumn": "Index",
            "sourceColumn": "Forecast vs Flash",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fd2ecbe-b96a-4bf7-9439-c5b710c92397",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7cf9aba4-ddef-46c0-bf41-277ad45129bc",
        "partitions": [
          {
            "name": "Metrics-4e1735f1-2243-4854-8b78-244002c7fa69",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WckwuKU3MKVYoK1YICFfSUTJUitVBE1XQcC7N1QTKGYHlXFJzShIVSvIV3HISizOAwsZgYVWF/DS4kIlSbCwA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Forecast vs Flash\" = _t, Index = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Forecast vs Flash\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TOPN",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "79ac3d09-c2b1-49a7-a881-593fb07f6413",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ecd4c5a9-6a81-4d61-be0e-178a60cafb82",
        "measures": [
          {
            "name": "Selected Value",
            "expression": "SELECTEDVALUE('TOPN'[Value])",
            "formatString": "0",
            "lineageTag": "3d68dc86-68b5-435f-8bd7-00fd0e7ef044"
          },
          {
            "name": "Opp ID Rank",
            "expression": [
              "RANKX(ALLSELECTED('ROF Pipeline'[HPE Opportunity Id],'ROF Pipeline'[Account Name],'ROF Pipeline'[Account ST ID],'ROF Pipeline'[Opportunity Name],'ROF Pipeline'[Opportunity Owner],'ROF Pipeline'[Country Name],'ROF Pipeline'[Forecast Category],'ROF Pipeline'[Sales Stage],'ROF Pipeline'[Opportunity Close Date],'ROF Pipeline'[DealBased_In/Out],'ROF Pipeline'[WeekNo1],'ROF Pipeline'[WeekNo],'ROF Pipeline'[Strategic Deal Exec Sponsor],'ROF Pipeline'[Strategic Deal Review],'ROF Pipeline'[OpportunityUpdateText],'ROF Pipeline'[HasGreenLake],'ROF Pipeline'[SFDC URL],'ROF Pipeline'[Lightning URL]),[Total ROF Pipeline Detailed1],,DESC)",
              "",
              "--RANKX(ALLSELECTED('ROF Pipeline'),[Total ROF Pipeline Detailed],,DESC)"
            ],
            "formatString": "0",
            "lineageTag": "1fa1a110-0698-44a6-a29c-4667297c50a1"
          },
          {
            "name": "selectedtopN",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(HASONEVALUE('TOPN'[Value]),MIN('TOPN'[Value]),'TOPN'[Opp ID Rank])",
            "lineageTag": "5dd672de-a392-4e65-bb2b-4c10988330c7"
          },
          {
            "name": "Opp id in selected",
            "expression": "IF('TOPN'[Opp ID Rank]<=[selectedtopN],1,0)",
            "formatString": "0",
            "lineageTag": "f9b8d931-2846-4209-996b-0b19f4cb2882"
          },
          {
            "name": "Top N ID Ranking",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "if(isfiltered('TOPN'[Value]),CALCULATE([Total ROF Pipeline Detailed1],TOPN(SELECTEDVALUE('TOPN'[Value]),VALUES('ROF Pipeline'[HPE Opportunity Id]),[Total ROF Pipeline Detailed1],DESC)),[Total ROF Pipeline Detailed1])",
            "formatString": "#,0",
            "lineageTag": "e549ebbf-d47c-4167-8974-98147322123e"
          }
        ],
        "partitions": [
          {
            "name": "TOPN-fe023a92-e4ee-4d28-9e96-7f16f78c7639",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMjRQitWJVjKCUMYQygRCmUIoQwOYGpgimDRcHsiIBQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Value = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Value\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "w / wo Decimal",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Decimal Pointer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed03f9ff-e102-47f3-8b17-c578ed78e041",
            "sortByColumn": "DecIndex",
            "sourceColumn": "Decimal Pointer",
            "summarizeBy": "none"
          },
          {
            "name": "DecIndex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ee4a3ce-aa7c-4852-9510-d3cb29f35fe3",
            "sourceColumn": "DecIndex",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f357af0d-8034-4d85-a479-aac1feee0de9",
        "measures": [
          {
            "name": "Sel Decimal",
            "expression": "SELECTEDVALUE('w / wo Decimal'[Decimal Pointer])",
            "lineageTag": "b77974f1-4a67-4152-855d-8f6d1de4d697"
          }
        ],
        "partitions": [
          {
            "name": "w / wo Decimal-c12c6917-6cf1-4d37-a292-4edfb3ebb67f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WKldISU3OzE3MUdJRMlSK1YlWystHEjJSio0FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Decimal Pointer\" = _t, DecIndex = _t])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "rpt flashbudget_OR",
        "columns": [
          {
            "name": "fiscalquarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecb4aaa2-5354-4855-921c-8b21796d47b6",
            "sourceColumn": "fiscalquarter",
            "summarizeBy": "none"
          },
          {
            "name": "geokey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88451153-4487-4340-b116-abe2cd98f93f",
            "sourceColumn": "geokey",
            "summarizeBy": "none"
          },
          {
            "name": "productkey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7723416e-5077-44b5-9adc-1e330c5f6f2c",
            "sourceColumn": "productkey",
            "summarizeBy": "none"
          },
          {
            "name": "salesmotion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1e64983-aef7-4531-8970-06f7533051c8",
            "sourceColumn": "salesmotion",
            "summarizeBy": "none"
          },
          {
            "name": "Target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "122e4f55-2b54-48f8-8310-1c1f00c81122",
            "sourceColumn": "Target",
            "summarizeBy": "none"
          },
          {
            "name": "TargetType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d400012-d919-44a0-9d6b-a2cfd0c70868",
            "sourceColumn": "TargetType",
            "summarizeBy": "none"
          },
          {
            "name": "GLHWFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "605ed8a7-8681-40f5-bb80-90e86975ff49",
            "sourceColumn": "GLHWFlag",
            "summarizeBy": "none"
          },
          {
            "name": "GMSFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56b31f77-e44a-4c21-a84f-fbe826d3a7c0",
            "sourceColumn": "GMSFlag",
            "summarizeBy": "none"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "dbd70c58-1cd8-4953-9b32-b796a8e6249e",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9de0851e-ae53-4454-abbb-bd5c8713207a",
            "sourceColumn": "Source",
            "summarizeBy": "none"
          },
          {
            "name": "GP_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'rpt flashbudget_OR'[geokey]&\"_\"&'rpt flashbudget_OR'[ProductKey]&\"_\"&'rpt flashbudget_OR'[salesmotion]",
            "isDataTypeInferred": true,
            "lineageTag": "e1940c6c-66dd-440f-8461-8ed822a598f7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "RTM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9126d171-e81c-491b-90cc-8be7414780b4",
            "sourceColumn": "RTM",
            "summarizeBy": "none"
          },
          {
            "name": "ServiceSolution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "100be2b1-fa28-4cd1-9a63-a2ebb371592b",
            "sourceColumn": "ServiceSolution",
            "summarizeBy": "none"
          },
          {
            "name": "GreenLakeFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "966c10f4-ec9e-46b6-bffb-c798f3b8a991",
            "sourceColumn": "GreenLakeFlag",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ee13625f-391d-43d9-b0d9-084dc9488d32",
        "partitions": [
          {
            "name": "rpt flashbudget_OR-e54488a3-75cd-4f0c-a462-45aadfbd5f5e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    rpt_flashbudget_OR = Source{[Schema=\"rpt\",Item=\"flashbudget_OR\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(rpt_flashbudget_OR,{\"CCflag\", \"ServiceType\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim GeoProduct",
        "columns": [
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3abdd728-ea80-4bfd-99db-fbd7f40d122d",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b51a1ca-63f9-4231-b772-f6f73f8ff0fb",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "Sales_Motion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0eb7ef8a-82b1-48f9-a5f0-868989c156c9",
            "sourceColumn": "Sales_Motion",
            "summarizeBy": "none"
          },
          {
            "name": "GP_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'dim GeoProduct'[geokey]&\"_\"&'dim GeoProduct'[ProductKey]&\"_\"&'dim GeoProduct'[Sales_Motion]",
            "isDataTypeInferred": true,
            "lineageTag": "ed6b3862-77d6-4f20-aab0-4a8284779f34",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Sales_Motion1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(RELATED('Prod Bridge'[Level_2_Description]) IN {\"A&PS\",\"Software\"},RELATED('Prod Bridge'[GBUGroup4]),",
              "IF(RELATED('Prod Bridge'[GBUGroup2])=\"GreenLake\",\"HPE GreenLake\",",
              "",
              "IF('dim GeoProduct'[Sales_Motion]=\"blank\",\"Other\",'dim GeoProduct'[sales_motion])))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "315758ae-64eb-47c5-8d6a-63f90f8a670a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "9cf691b8-8fe8-4855-b985-b5f94990192f",
        "partitions": [
          {
            "name": "dim GeoProduct-bf9e13ec-6532-4734-9197-83f14b9c82f9",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    dim_GeoProduct = Source{[Schema=\"dim\",Item=\"GeoProduct\"]}[Data]",
                "in",
                "    dim_GeoProduct"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "fiscal_weekkey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffffd427-1a36-4872-b335-df9320c711a7",
            "sourceColumn": "fiscal_weekkey",
            "summarizeBy": "none"
          },
          {
            "name": "fiscal_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7b307526-f3d1-4cb8-926b-f368d78a44bd",
            "sourceColumn": "fiscal_year",
            "summarizeBy": "sum"
          },
          {
            "name": "fiscal_quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fb9333e2-ed03-4d2c-ae9c-a3743e561e8b",
            "sourceColumn": "fiscal_quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "fiscal_week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "58b30486-150b-4bee-8e81-db464ec9dad0",
            "sourceColumn": "fiscal_week",
            "summarizeBy": "sum"
          },
          {
            "name": "relative_quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2809a2c4-7f94-4b0c-83b4-8a1ccadd3086",
            "sourceColumn": "relative_quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "is_current_week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0572b30f-85d2-4ecd-8b83-30162ca305a9",
            "sourceColumn": "is_current_week",
            "summarizeBy": "sum"
          },
          {
            "name": "current_fiscal_week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c409ec73-18b4-4f4f-befd-b27496ed5db4",
            "sourceColumn": "current_fiscal_week",
            "summarizeBy": "sum"
          },
          {
            "name": "Graph",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4302abf1-3d27-4da5-b363-e89d5bee7a91",
            "sourceColumn": "Graph",
            "summarizeBy": "sum"
          },
          {
            "name": "fiscalqtr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "left('Date'[fiscal_weekkey],6)",
            "isDataTypeInferred": true,
            "lineageTag": "a2d7b1e7-8667-4ee2-ae48-0840e5a02cbe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "fiscalyrQtr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Date'[fiscal_year]&\"-Q\"&'Date'[fiscal_quarter]",
            "isDataTypeInferred": true,
            "lineageTag": "c3c1e364-1a19-4fd9-9d2b-fedcb5369bc7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "85d3a815-cd4c-4ed0-b6b6-9f29cfd83ee6",
        "partitions": [
          {
            "name": "Date-1a31afa0-499c-4b16-b72e-3101b6c22093",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\", [Query=\"Select * from rpt.date\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Pipeline_Services",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FiscalWeekKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e217dde1-2619-4055-9f92-b8a9beb573dc",
            "sourceColumn": "FiscalWeekKey",
            "summarizeBy": "none"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80846fbb-2cc6-4a0a-862d-74eb68644b97",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f77634ad-2a40-4527-8264-667ac57d536b",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ForecastCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bb9a946-b9db-440e-9a30-89e68831c7b7",
            "sourceColumn": "ForecastCategory",
            "summarizeBy": "none"
          },
          {
            "name": "SalesStage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a71e5456-9241-4d71-9805-3f6e5f46f4b8",
            "sourceColumn": "SalesStage",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "757770bf-9224-4d74-8010-413ced9c6b30",
            "sourceColumn": "WeekNo",
            "summarizeBy": "none"
          },
          {
            "name": "DealBased_In/Out",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e623196-694e-495f-b136-0d22d11bd77e",
            "sourceColumn": "DealBased_In/Out",
            "summarizeBy": "none"
          },
          {
            "name": "SalesMotion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df5d9c35-bb4e-4cb0-b6fe-1b10c7238c90",
            "sourceColumn": "SalesMotion",
            "summarizeBy": "none"
          },
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "db8a8134-780a-44ca-b902-995a1a76ba90",
            "sourceColumn": "Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "GP_Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Pipeline_Services'[geokey]&\"_\"&'Pipeline_Services'[ProductKey]&\"_\"&'Pipeline_Services'[SalesMotion]",
            "isDataTypeInferred": true,
            "lineageTag": "f2b6358c-9a0b-4a81-8cf3-6c4afd3bcdfb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "01cbebd1-3fcd-4fba-8aa7-f41f152f1dd4",
        "partitions": [
          {
            "name": "Pipeline_Services-a35cc1d3-1b94-45ca-87d8-2ca856392351",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    fact_Pipeline_Services = Source{[Schema=\"fact\",Item=\"Pipeline_Services\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(fact_Pipeline_Services,\"W14\",\"W13-1\",Replacer.ReplaceText,{\"WeekNo\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value\",{\"Country\", \"Strategic Deal Exec Sponsor\", \"Strategic Deal Review\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ROF_NEO",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28001a13-48bb-4314-b981-a1d5668cea15",
            "sourceColumn": "FiscalQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35fa7c6e-3288-4fbc-9834-a5412ec4b220",
            "sourceColumn": "WeekNo",
            "summarizeBy": "none"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95b36c5d-c2ff-4fbb-94fe-006a725922dd",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ff27ba0-3206-46e1-96c6-7855ecd17762",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "NEOPValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d3397726-52f9-4d2f-b585-29e81cdd91c2",
            "sourceColumn": "NEOPValue",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthPlan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04e1c6d2-f94f-40a7-8029-0f36868eaabc",
            "sourceColumn": "MonthPlan",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8b782e9c-96f0-45ca-8eb9-f5bce6edb083",
        "partitions": [
          {
            "name": "ROF_NEO-f12e2112-f3c9-4b29-bbe3-91c876541d28",
            "mode": "import",
            "queryGroup": "ROF Group\\Facts",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    fact_ROF_NonExecutableOrdersPlan = Source{[Schema=\"fact\",Item=\"ROF_NonExecutableOrdersPlan\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(fact_ROF_NonExecutableOrdersPlan,{\"BU\", \"BusinessAreaCode\", \"Country\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sort Forecast Category",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Fcst Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7b2de05-c1a2-43d9-8d85-58a18faa8177",
            "sortByColumn": "Sort Order",
            "sourceColumn": "Fcst Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sort Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "17f26be4-0060-4afd-bd2c-c8184484664f",
            "sourceColumn": "Sort Order",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8e510414-fa20-404a-826b-6cfbe04ddfa2",
        "partitions": [
          {
            "name": "Sort Forecast Category-2ab85d3c-563a-4b3b-acf4-4c06195cdf4d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCs/PU9JRMlSK1YlWcs7Pzc0sAXKNwNzQguLMlFQg1xjMDcgsSM3JzEtVcA0GipmgivmAxEyVYmMB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Fcst Category\" = _t, #\"Sort Order\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Fcst Category\", type text}, {\"Sort Order\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Geo Master Sorting",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SubRegion1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebaaf585-6d5b-42f6-8abf-9493a0c873c6",
            "sortByColumn": "Sort",
            "sourceColumn": "SubRegion1",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3148567a-88e3-4f36-939f-cd53a50411c0",
            "sourceColumn": "Sort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ffa097ec-da20-4a5f-8487-d680b7ce8ae7",
        "partitions": [
          {
            "name": "Geo Master Sorting",
            "mode": "import",
            "queryGroup": "ROF Group\\Dims",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcgxwdFbSUbJUitWJVnJOzSspSsxRcC0tyi9IBQobQ4QzMvMSgTwzMM8zLyUTxLMA87wSCxLzgDxzMM/HMdg1CMgzAvP88otKMhQcc1OLMpNBOgwhouGuQLYJmB3q7enr6gjkmoK5HoEgVQZKsbEA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SubRegion1 = _t, Sort = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"SubRegion1\", type text}, {\"Sort\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Table_TempSecurity",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Prod Categ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bf05ba3-2c6c-4a6d-a07b-9ddcd1171fc4",
            "sourceColumn": "Prod Categ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5ade3637-0a37-4425-bda2-81c59d6e8fbc",
        "partitions": [
          {
            "name": "Table_TempSecurity",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"nZJPb4JAEMW/yoSTJh6MTbzTlRajpVQOmlAPWxiVSHfI/tH22xes1NIa2XDbnfzee5OZiWOH0XthNIK/BEYSnYHjhx6EklKTaFV+a+CntB7ETqRJ8u0NVQ00VA85fkBEudEZCQWXaMvUP/pLE93yI5SHLEFlmR7K7MDLIsvJpPZNM8k/wVtdFfghg1czHI7G4E5/dfbfYDWBnltQnhOMZrVmPOt3tw1IVBMsujssUGmgDTTh6/dgZdiEHiWimPM9Qq88s3O93lm/Y4SXVgfzUuLV62ziSvPGa+6ETVjwXbUB/Ttmg4UoFBcptbHPeocSomOmk10mtm34cu4GbUxEG33kp73c5p7u25AFlWNt6Wr9BQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Prod Categ\" = _t, Security1Temp = _t, Security2Temp = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Prod Categ\", type text}, {\"Security1Temp\", type text}, {\"Security2Temp\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Security1Temp\", \"Security2Temp\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Prod Master Sorting (Prod categ)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Prod Categ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb2ace4f-f826-4112-ac2d-6599f44bf1d7",
            "sourceColumn": "Prod Categ",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "61cd6f5e-cba2-4df3-8265-ffb72e82a5b6",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c5945b72-26ea-4f55-ac46-122c57ff4566",
        "partitions": [
          {
            "name": "Prod Master Sorting (Prod categ)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"bZFBU8IwEIX/yk5PMMOhtFr1WANaB6yVHmCmcog0QMea7aQp6L83yQrVGY777XubfZui8Bh+Np0WkCyBoRLeyBt761Hh5RoV3/3loeMPtfiCHOtOVyhb6O1GEVxS9IOM4uqiQqhDtRGtfZsez1R14GYqq7EryTn2XYcp/g3TFbHrHq0mMIgbrGuEYAZvne8HEUSzIQkjJ0xR2m0aYjeOLUSrAbeQZOzkip9OiW+d5H/rUQkh5/xDwMCc5pefEgyN6c6ZpqWN/GqPQotPWAqx6t65zRKcURIyC8IzyIRsuSzRUrrWi94LBfmx0pt9JXe2QcGX8zi1FaXLcauPnH6QsuXP97agFAs01ya32XD9Aw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Prod Categ\" = _t, Sort = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Prod Categ\", type text}, {\"Sort\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Prod Master Sorting (BU)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BU 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e46bfd1-6fc1-4a0a-a97b-a31701731e19",
            "sourceColumn": "BU 2",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f61eb8c-31c2-481f-a1df-66aeee2dd11d",
            "sourceColumn": "Sort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4707123d-49eb-4f41-be98-ac4aa7c6ec0c",
        "partitions": [
          {
            "name": "Prod Master Sorting (BU)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcs7PLSgtSVXwCFdwzi9KVdJRMlSK1YlWCi7JL0pMRxY3Aou75aRWKATn55SWZObnFQOFzcDCAUWZZYlAY5xz8ktTgJqAEiZgCY8AZ4WYUgMDIzMFR0+IhDEWCfei1NQ8n8TsVAUNoI1Q8eDUorLM5NRiTaAmU7Am15R0kFPMlWJjAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"BU 2\" = _t, Sort = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"BU 2\", type text}, {\"Sort\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Prod Master Sorting (Alternate BU)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Alternate BU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e08c759-df85-4002-9a98-b263b809bad0",
            "sourceColumn": "Alternate BU",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b756d311-8bdd-446e-a75d-1ea189b38fa4",
            "sourceColumn": "Sort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "77d57a75-f21c-47bc-bd90-a76feb59953c",
        "partitions": [
          {
            "name": "Prod Master Sorting (Alternate BU)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcs7PLSgtSVXSUTJUitWJVgouyS9KTAfxjcB8jwBnhZhSAwMjMwVHT6CoMVg0oCizLLEkVcE5J780BShqAhZ1y0mtUAjOzyktyczPK1YITi0qy0xOLQbKm4LlXVPABpspxcYCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Alternate BU\" = _t, Sort = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Alternate BU\", type text}, {\"Sort\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "OrdersDetailed",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "WeekNo1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "21bac0fe-fdc8-4d00-952b-d529e691f1d0",
            "sourceColumn": "WeekNo1",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e489d1e-6feb-49d9-82c1-ed073240ffee",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "End Customer Country Entity Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9727dc1e-418e-4a12-a47b-161245c7ace4",
            "sourceColumn": "End Customer Country Entity Id",
            "summarizeBy": "none"
          },
          {
            "name": "End Customer Country Entity Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af83b9a1-d353-4b1d-aa08-f69c1cea9036",
            "sourceColumn": "End Customer Country Entity Name",
            "summarizeBy": "none"
          },
          {
            "name": "Order Create Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "d3ec9786-dae0-45ee-a27d-ead275794558",
            "sourceColumn": "Order Create Date",
            "summarizeBy": "none"
          },
          {
            "name": "End Customer Party Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14ed653c-0393-42d3-a460-6d888747612f",
            "sourceColumn": "End Customer Party Id",
            "summarizeBy": "none"
          },
          {
            "name": "End Customer Party Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ab972e3-ed6e-4860-b907-041a3441bfb6",
            "sourceColumn": "End Customer Party Name",
            "summarizeBy": "none"
          },
          {
            "name": "HPE Opportunity Identifier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44539465-8008-4cb7-a7a3-dd60fa2e355f",
            "sourceColumn": "HPE Opportunity Identifier",
            "summarizeBy": "none"
          },
          {
            "name": "End Customer Account ST ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cff94478-8fab-4350-990c-2882cfe2df0e",
            "sourceColumn": "End Customer Account ST ID",
            "summarizeBy": "none"
          },
          {
            "name": "End Customer Account ST Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "281bdfb6-af3f-470b-95fe-46d88ed46c51",
            "sourceColumn": "End Customer Account ST Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order #",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e899462-3f31-4e39-8099-a217fcce8d97",
            "sourceColumn": "Sales Order #",
            "summarizeBy": "none"
          },
          {
            "name": "NetUSD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d7855a75-f177-4850-bb40-44b89bb8f1d5",
            "sourceColumn": "NetUSD",
            "summarizeBy": "sum"
          },
          {
            "name": "Geokey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c710087-bf48-4cd7-951a-650b371912db",
            "sourceColumn": "Geokey",
            "summarizeBy": "none"
          },
          {
            "name": "CancelledFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f97c68c-c855-4ade-a875-61df50cb2291",
            "sourceColumn": "CancelledFlag",
            "summarizeBy": "none"
          },
          {
            "name": "PrebuildFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21fa5226-9a65-49c0-85ea-488257f2b4d1",
            "sourceColumn": "PrebuildFlag",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "6db1252b-0c4a-4c1d-8982-e9ca3ab543a2",
            "sourceColumn": "WeekNo",
            "summarizeBy": "none"
          },
          {
            "name": "Week No New",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e26d3f9d-5d2e-4e97-a648-0cbab4878673",
            "sourceColumn": "Week No New",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "080972ca-fad1-4a5d-b52b-acfdae2a4422",
        "partitions": [
          {
            "name": "OrdersDetailed",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqldb0050prd.americas.hpqcorp.net,1190\", \"Sales_Cockpit\"),",
                "    rpt_ROF_Ordersdetailed = Source{[Schema=\"rpt\",Item=\"ROF_Ordersdetailed\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(rpt_ROF_Ordersdetailed,{{\"Value\", \"NetUSD\"}, {\"WeekNo\", \"WeekNo1\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"Week_No \", each Text.Combine({\"W\",[WeekNo1]})),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Added Custom\", \"WeekNo\", each if [#\"Week_No \"] = \"W1\" then \"W2\" else if [#\"Week_No \"] = \"W13+1\" then \"W13\" else [#\"Week_No \"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"Week_No \", type text}, {\"WeekNo\", type text}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type\",{{\"Week_No \", \"Week No New\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "QTD Plans",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "be2b6f36-353c-4c87-9781-9c43ac517c84",
            "sortByColumn": "Column2",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "14edbe26-50ef-49f4-95cb-71a870f10b1e",
            "sourceColumn": "Column2",
            "summarizeBy": "sum"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF('QTD Plans'[Column1]=\"Actuals\",1,2)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f4a4653e-ea5e-4116-8009-b773c1d7a4b5",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "aba80d1e-01c8-401b-afef-5d9183ae352d",
        "measures": [
          {
            "name": "Dynamic",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),    ",
              "MAX('QTD plans'[Column1])=\"Actuals\" && MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[Cum Orders],",
              "MAX('QTD plans'[Column1])=\"Actualsn\" && MAX(ColWkSorting[WKDyn]) <>\"CurrWeek-1\",BLANK(),",
              "MAX('QTD plans'[Column1])=\"Monthly Plan\" &&MAX(ColWkSorting[WKDyn])=\"CurrWeek-1\",[Cum M1_M2_M3],",
              "MAX('QTD plans'[Column1])=\"Monthly Plan\" &&MAX(ColWkSorting[WKDyn])<>\"CurrWeek-1\",BLANK())"
            ],
            "formatString": "0.0",
            "lineageTag": "9c8785c8-5b8c-4876-a305-64b3fdf33a3c"
          }
        ],
        "partitions": [
          {
            "name": "QTD Plans",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WckwuKU3MKVbSUTJUitWJVgIyjMAM3/y8koycSoWAnMQ8oKCxUmwsAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact ROF_Actuals_PQ",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e313ac77-bdd9-4277-9512-93f45329f100",
            "sourceColumn": "FiscalQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0b39d13-142a-4a9f-a419-94e28973e0db",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Geography",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8822d1a0-738d-4e4c-8a1a-f73899865082",
            "sourceColumn": "Geography",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46c6e415-1cdb-43d7-9713-03224c4400a2",
            "sourceColumn": "WeekNo",
            "summarizeBy": "none"
          },
          {
            "name": "BackLog",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ef6ebcf1-86d6-4387-a523-c778d7ca5086",
            "sourceColumn": "BackLog",
            "summarizeBy": "sum"
          },
          {
            "name": "execBacklog",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c31ca40f-20d9-47f0-9d30-81b1effdef00",
            "sourceColumn": "execBacklog",
            "summarizeBy": "sum"
          },
          {
            "name": "GeoKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30a05cf1-81bb-464d-8032-2d249cfadc79",
            "sourceColumn": "GeoKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f366857a-1b44-423e-b18e-a665d0d93f85",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "Clari/ROF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9dacf20-53c1-47b7-8f56-980acfe91ea5",
            "sourceColumn": "Clari/ROF",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0",
            "lineageTag": "eaf97bf5-69fe-468d-8148-407cfd86059f",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "ColumnWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5a692cb-ea81-43db-9bba-902b11dcfffa",
            "sourceColumn": "ColumnWeek",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3ebfa857-83a8-4b34-b92b-2d3bd6cec1af",
        "measures": [
          {
            "name": "Orders_PQ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Weekdisplayed = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(RowWkSorting[Week]),",
              "        RowWkSorting[IsCurrentWeek] = \"TRUE\"",
              "    )",
              "VAR DisplayValue = ",
              "    CALCULATE(",
              "        [Forecast Value_PQ],",
              "        KEEPFILTERS(RowWkSorting[Week] = \"W13 + 1\"))",
              "        //*KEEPFILTERS(ColWkSorting[Open/Close] = \"Close\" || ColWkSorting[IsCurrentWeek]=\"True\" && VALUES('rpt dim_current_date_rof'[Actualsavaialble])=\"Y\"),",
              "        //*KEEPFILTERS('ROF Forecast'[Clari/ROF] = \"ROF\")//*",
              "",
              "    ",
              "  VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "RETURN",
              "    IF(",
              "        ISINSCOPE(ColWkSorting[Weeks]), ",
              "        IF(",
              "            SELECTEDVALUE(ColWkSorting[Weeks]) = BLANK(), ",
              "            Weekdisplayed, ",
              "            Result",
              "        ),",
              "        Result",
              "    )"
            ],
            "lineageTag": "4d525e31-e738-4d48-94f0-5fcd2a4b9f1f"
          },
          {
            "name": "Forecast Value_PQ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR DisplayValue =",
              "SUMX(",
              "    SUMMARIZE(",
              "        'fact ROF_Actuals_PQ',",
              "        'fact ROF_Actuals_PQ'[GeoKey],",
              "        'fact ROF_Actuals_PQ'[ProductKey],",
              "        ColWkSorting[SortOrder],",
              "        ColWkSorting[Weeks],",
              "        RowWkSorting[Week],",
              "        RowWkSorting[SortOrder],",
              "        'fact ROF_Actuals_PQ'[Value]",
              "    ),",
              "    'fact ROF_Actuals_PQ'[Value]",
              ")",
              "VAR Result = IF([Sel Decimal]= \"w decimal\",CONVERT(DisplayValue,DOUBLE),",
              "    if([Sel Decimal]= \"no decimal\",FORMAT(IF(DisplayValue=BLANK(),0,DisplayValue),\"#,0\")))",
              "Return",
              "Result"
            ],
            "lineageTag": "0ea00e39-5a62-4f1b-9420-d78dcb79eb97"
          },
          {
            "name": "PQ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE('fact ROF_Actuals_PQ'[Forecast Value_PQ],FILTER('fact ROF_Actuals_PQ','fact ROF_Actuals_PQ'[Clari/ROF]=\"ROF\"))",
            "lineageTag": "6a2ace9e-9dee-4e90-a3ba-47eaae59db2b"
          },
          {
            "name": "Cum orders_pq",
            "expression": [
              "",
              "CALCULATE(",
              "    [Orders_PQ],",
              "    FILTER(",
              "        ALL(ColWkSorting),",
              "        ColWkSorting[SortOrder] <= MAX(ColWkSorting[SortOrder])",
              "    )",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "fca598a2-9235-421b-ab88-97115d7ba7b7"
          }
        ],
        "partitions": [
          {
            "name": "fact ROF_Actuals_PQ",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"sqldb0050prd.americas.hpqcorp.net,1190\"),",
                "    Sales_Cockpit = Source{[Name=\"Sales_Cockpit\"]}[Data],",
                "    fact_ROF_Actuals_PQ = Sales_Cockpit{[Schema=\"fact\",Item=\"ROF_Actuals_PQ\"]}[Data],    ",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"fact_ROF_Actuals_PQ\",{\"CountryCode\", \"BusinessAreaCode\", \"Geo\", \"budget\",  \"id\", \"UpdatedBy\", \"UpdatedTime\", \"Total\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Columns\", \"Clari/ROF\", each \"ROF\"),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Added Custom\", {\"Clari/ROF\", \"GeoKey\", \"ProductKey\", \"FiscalQuarter\", \"Region\", \"Geography\", \"BU\", \"WeekNo\", \"BackLog\",\"execBacklog\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"ColumnWeek\"}}),",
                "     #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"FiscalQuarter\", type text}, {\"Region\", type text}, {\"BU\", type text}, {\"WeekNo\", type text}, {\"GeoKey\", type text}, {\"ProductKey\", type text}, {\"ColumnWeek\", type text}, {\"Value\", type number}, {\"BackLog\", type number}, {\"execBacklog\", type number}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type\",{\"BU\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Metric Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba3238a2-4e1e-49ce-9cb7-6df3e2972d7e",
            "sortByColumn": "Column2",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e7327f76-13bc-4465-aeda-5d95bddfd52a",
            "sourceColumn": "Column2",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "47776a2e-44bd-49fc-855d-788ce746043a",
        "partitions": [
          {
            "name": "Metric Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCghU8C9KSS0qVtJRMlSK1YlWCgxxQQgZgYV8DRUCchLzgHxjCN8IxjeB8I1hfFMw36k0JT21BCZmphQbCwA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Table_OL",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "0922ea5b-efcc-4529-824b-edd78cf5de4f",
            "sortByColumn": "Column2",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5e4fb4ee-fc83-4682-adb1-e70f09450d48",
            "sourceColumn": "Column2",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "9aca1ec2-0b99-44fe-aa6e-aba9a0f10720",
        "partitions": [
          {
            "name": "Table_OL",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WckwuKU3MKVbSUTJUitWJVvI1VAjIScwD8o0gfCMY3xjCN4bxTcB8p9KU9NQSmJipUmwsAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TableNew",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "39ebd487-06ca-4c1b-aa8f-8843713112df",
            "sortByColumn": "Column2",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4e8a066a-97f8-4dfc-8c8e-86730c89bc28",
            "sourceColumn": "Column2",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "0ec1c293-5751-4400-9d0a-f47b1cd4d9e2",
        "partitions": [
          {
            "name": "TableNew",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8kstUfAvSkktKlbSUTJUitWJVvI1VAjIScwD8o3A/LJiBYSQMUSJEYxvAlcCFzKFCTmVpqQDjYcKm4GFA1KL0vKLchPzklOBYuZKsbEA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}