DEFINE
	VAR __DS0FilterTable = 
		TREATAS({"W6"}, 'ColWkSorting'[Weeks])

	VAR __DS0FilterTable2 = 
		FILTER(
			KEEPFILTERS(VALUES('Geo Master'[SubRegion1])),
			NOT('Geo Master'[SubRegion1] IN {BLANK()})
		)

	VAR __DS0FilterTable3 = 
		TREATAS({"w decimal"}, 'w / wo Decimal'[Decimal Pointer])

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL(
				ROLLUPGROUP('Geo Master'[SubRegion1], 'Geo Master'[Sort]), "IsGrandTotalRowTotal"
			),
			'ColWkSorting'[Weeks],
			'ColWkSorting'[SortOrder],
			__DS0FilterTable,
			__DS0FilterTable2,
			__DS0FilterTable3,
			"Orders", 'Calcs'[Orders]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			102,
			SUMMARIZE(__DS0Core, 'Geo Master'[SubRegion1], 'Geo Master'[Sort], [IsGrandTotalRowTotal]),
			[IsGrandTotalRowTotal],
			0,
			'Geo Master'[Sort],
			1,
			'Geo Master'[SubRegion1],
			1
		)

	VAR __DS0SecondaryBase = 
		SUMMARIZE(__DS0Core, 'ColWkSorting'[Weeks], 'ColWkSorting'[SortOrder])

	VAR __DS0Secondary = 
		TOPN(102, __DS0SecondaryBase, 'ColWkSorting'[SortOrder], 1, 'ColWkSorting'[Weeks], 1)

	VAR __DS0BodyLimited = 
		NATURALLEFTOUTERJOIN(
			__DS0PrimaryWindowed,
			SUBSTITUTEWITHINDEX(
				__DS0Core,
				"ColumnIndex",
				__DS0Secondary,
				'ColWkSorting'[SortOrder],
				ASC,
				'ColWkSorting'[Weeks],
				ASC
			)
		)

EVALUATE
	__DS0Secondary

ORDER BY
	'ColWkSorting'[SortOrder], 'ColWkSorting'[Weeks]

EVALUATE
	__DS0BodyLimited

ORDER BY
	[IsGrandTotalRowTotal] DESC,
	'Geo Master'[Sort],
	'Geo Master'[SubRegion1],
	[ColumnIndex]