table 'Sort Forecast Category'
	lineageTag: 8e510414-fa20-404a-826b-6cfbe04ddfa2

	column 'Fcst Category'
		dataType: string
		lineageTag: c7b2de05-c1a2-43d9-8d85-58a18faa8177
		summarizeBy: none
		sourceColumn: Fcst Category
		sortByColumn: 'Sort Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Sort Order'
		dataType: int64
		formatString: 0
		lineageTag: 17f26be4-0060-4afd-bd2c-c8184484664f
		summarizeBy: none
		sourceColumn: Sort Order

		annotation SummarizationSetBy = Automatic

	partition 'Sort Forecast Category-2ab85d3c-563a-4b3b-acf4-4c06195cdf4d' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCs/PU9JRMlSK1YlWcs7Pzc0sAXKNwNzQguLMlFQg1xjMDcgsSM3JzEtVcA0GipmgivmAxEyVYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Fcst Category" = _t, #"Sort Order" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Fcst Category", type text}, {"Sort Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

